### ISSUE TITLE
Add `id` attributes to setting sections in `/settings/extensions` for anchor links

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19869] opened 2023-07-31 15:55 UTC
## Is this feature related to a problem? Please describe.

- When we're linking users to certain settings, we should be able to append an anchor link e.g. `/settings/extensions#api` to present the user with the precise section we need.
- We should ideally have this for all `/settings` but can start here for Pro Tools onboarding purposes

## Describe the solution you’d like

Perhaps, something like the following:

- `#templates` or `#comment-templates` for "Comment templates"
- `#rss` for "Publishing to DEV Community from RSS"
- `monetization` for "Web monetization"
- `api` for "Dev community API keys".

## Definition of Done

- [ ] Add `id` attributes to each section to support anchor links to the specific setting in `/settings/extensions`

## Additional Context

- This is required to make it easy to extract an API key to aid in Pro Tools onboarding

**Comment by 0xJamin** [comment] 2023-08-06 16:59
Hi @PhilipHow  can I take this as my first issue to work on?😃

**Comment by PhilipHow** [comment] 2023-08-08 12:46
Hey @0xJamin sure! Please make sure you've read our [contributors guide](https://developers.forem.com/contributing-guide/forem).

**Comment by KSSaiTeja** [comment] 2023-08-17 09:33
i will work on this. could you please assing me this to me..?

I will complete the work in 5 min

**Comment by 0xJamin** [comment] 2023-08-17 09:37
Hi @PhilipHow  please assign it to @KSSaiTeja  I couldn't set up the project locally. I tried all I could but kept running into errors.

Also the majorly in Ruby but I'm skilled in TypeScript and React so navigating was difficult for me

**Comment by KSSaiTeja** [comment] 2023-08-19 10:29
hello there, i am here to offer my assistance, is anyone there to help me out, that how can i reproduce the issue.?

**Comment by PhilipHow** [comment] 2023-08-20 22:37
Hi @KSSaiTeja - are you able to get the project running locally and have you had a look at the [contributors guide](https://developers.forem.com/contributing-guide/forem)?

This is a new enhancement request, and not a bug to reproduce/fix.

**Comment by KSSaiTeja** [comment] 2023-08-21 06:18
i didn't tried to set up the project locally. but if you guide to fix it up. and i will fix the issue.

**Comment by KSSaiTeja** [comment] 2023-08-21 14:59
@PhilipHow will you please tell me how can i set it locally

**Comment by narender2031** [comment] 2023-08-28 17:19
@KSSaiTeja Can i take this issue please?

**Comment by KSSaiTeja** [comment] 2023-08-28 17:50
actually i fixed the issue so far.. unfortunately due to some personal issues.. i can't raise a PR..

anyway thanks for reminding me..

@PhilipHow assign this to @narender2031 i fixed the issue.. but forgot to raise PR

**Closed** 2023-08-29 17:15 UTC
Labels: good first issue, ready for dev
