### ISSUE TITLE
Title section is covered and hided by tags section on posting screen.

### ISSUE THREAD

**Issue by kakadais** [forem/forem#12022] opened 2020-12-23 19:34 UTC
= I didn't test for specific browser extensions because all browser shows the same thing.

= Can't find.

**Describe the bug**
= Title section is covered and hided by tags section on posting screen.

<MacbookPro Version 11.1 Big  Sur>

-Safari Version 14.0.2 (16610.3.7.1.9)
![image](https://user-images.githubusercontent.com/5265343/103031285-e7255700-45a0-11eb-9e9f-ef1dae664097.png)

-Chrome Version 87.0.4280.88 (Official Build) (x86_64)
![image](https://user-images.githubusercontent.com/5265343/103031307-ed1b3800-45a0-11eb-804a-f421abeef101.png)

-Firefox 82.0.2 (64-bit)
![image](https://user-images.githubusercontent.com/5265343/103031317-f1475580-45a0-11eb-84f8-2260da533d0d.png)

-Edge Version 87.0.664.66 (Official build) (64-bit)
![image](https://user-images.githubusercontent.com/5265343/103031329-f73d3680-45a0-11eb-8428-199dadd8ea7c.png)

**To Reproduce**
It reproduced all the time for me in all browsers.

**Expected behavior**
I just size up the textarea, and it worked.
Should be frontend html/css problem.
![image](https://user-images.githubusercontent.com/5265343/103031237-ca891f00-45a0-11eb-8c2f-38216134488c.png)

**Comment by ludwiczakpawel** [comment] 2021-01-21 12:11
It's a duplicate of an existing issue https://github.com/forem/forem/issues/10114 so I'm closing this one (original has more context in thread).

**Closed by ludwiczakpawel** 2021-01-21 12:11 UTC
Labels: area: articles, bug
