### ISSUE TITLE
Fix width of campaign banner

### ISSUE THREAD

**Issue by lisasy** [forem/forem#11100] opened 2020-10-26 19:59 UTC
**Describe the bug**

On different screen sizes, the width of the campaign shows up in inconsistent ways. On very large screen sizes, the campaign banner is wider than the overall content container; on smaller screen sizes, the campaign banner is narrower than the content container.

**Expected behavior**

The campaign banner should be displayed at 100% width at all times.

**Screenshots**
![Screen Shot 2020-10-26 at 9 58 21 AM](https://user-images.githubusercontent.com/816402/97221767-98b73000-178a-11eb-9f18-66e275be4eff.png)
![Screen Shot 2020-10-26 at 9 58 07 AM](https://user-images.githubusercontent.com/816402/97221772-9a80f380-178a-11eb-89f8-ba0bc10c591a.png)
![Screen Shot 2020-10-26 at 9 58 13 AM](https://user-images.githubusercontent.com/816402/97221769-99e85d00-178a-11eb-8b69-94a9f5b52529.png)

**Additional context**

I know that we currently create banners using HTML variants and using the same markup code each time. A short-term fix would be to make sure we're using 100% width moving forward; a more ideal solution would be to make this campaign banner into a re-usable component so that the outside container is *always* the same, and we can continuing to use varying designs in the inner area.

**Comment by andremacnamara** [comment] 2020-11-09 17:27
I can work on this issue if no one else has yet?

**Comment by rhymes** [comment] 2020-11-09 17:32
@andremacnamara thank you! I'm assigning it to you

**Comment by ludwiczakpawel** [comment] 2021-01-21 12:23
@andremacnamara any updates on this? I'm leaning towards closing this issue because of the following:

I think this is not a bug with Forem itself - it's simply because we (system) allow admins to write their own custom code for these banners. So it's not really something we can control at the moment and definitely not a bug. We should, though, implement a new feature: some constraints for these banners so admin can only edit/adapt the content of the banner instead of coding these by themselves.

**Comment by lisasy** [comment] 2021-01-21 16:56
@ludwiczakpawel Yeah... I made this issue and I think we can close it since we're may be thinking of more systemic updates the force constraints like the ones you mentioned.

**Closed** 2021-01-21 20:18 UTC
Labels: area: design, bug
