### ISSUE TITLE
Welcome tag is not readable in dark theme of forem

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#13206] opened 2021-03-31 17:03 UTC
**Describe the bug**

Welcome tag is not visible in dark theme

**To Reproduce**
1. Go to settings and change to dark theme
2. Go to https://dev.to/thepracticaldev/welcome-thread-v118-1kb0
3. The welcome tag wont be visible 

**Expected behavior**
tag should visible in all themes
**Screenshots**

![IMG_20210331_222530](https://user-images.githubusercontent.com/8092120/113182910-0eab5000-9271-11eb-812a-78710e87ca4d.jpg)

**Smartphone (please complete the following information):**

- Device: Redmi note 6 pro
- OS, version: android 10 
- Browser, version: brave 

**Additional context**

**Comment by cmgorton** [comment] 2021-03-31 17:34
Hey @Rafi993 thanks for opening this issue. Since it is a duplicate of https://github.com/forem/forem/issues/12749 I am going to close this one. 😃

**Closed by cmgorton** 2021-03-31 17:34 UTC
