### ISSUE TITLE
Improved meta title and OG tags

### ISSUE THREAD

**Issue by fuzenco** [forem/forem#13857] opened 2021-05-25 21:22 UTC
I’m new to Dev. One thing I noticed that would make returning to articles that we noted in our note-taking apps better is if your Title and OG meta tags actually referenced the article. Instead, the following page (the index page of a series) uses the default Dev home page meta, which is non-descriptive of the page we bookmarked.

Here’s the bookmarked link:
https://dev.to/dijonmusters/series/12346

Now look at the share preview (taken from Craft app):
![image0](https://user-images.githubusercontent.com/173683/119569883-5d5efd00-bd7d-11eb-93c3-ca6aee6551f9.jpeg)

It would be awesome if that share preview reflected the page title, etc.

**Comment by Link2Twenty** [comment] 2021-05-25 21:38
I think this is a duplicate of #13509

**Comment by rhymes** [comment] 2021-05-26 04:35
Thank you @fuzenco, as @Link2Twenty mentioned, I think we can consider this a duplicate of #13509, there's a pending PR opened to address that as well: https://github.com/forem/forem/pull/13772

**Closed by rhymes** 2021-05-26 04:35 UTC
