### ISSUE TITLE
Overlaying reactions in the sharing menu

### ISSUE THREAD

**Issue by nahtanPNG** [forem/forem#20164] opened 2023-09-23 14:10 UTC
**Overlaying reactions in the sharing menu**

On the desktop, when you scroll down your page to see the comments, and, press the 3 dots for more share options there is a visual bug, where the reaction is above the menu.

**To Reproduce**

1. Go to a post
2. Scroll down to the comments section
3. Press the 3 dots for more options
4. See the bug

**Screenshots**

<img  alt="Screenshot" width=450 src="https://github.com/forem/forem/assets/93049899/32e75b6c-a8b8-4ecb-a706-ada621ba5463"/> <img alt="Gif" width=300 src="https://github.com/forem/forem/assets/93049899/f4208787-185c-48a4-bf0b-a69e33f114e2"/>

**Desktop**

- OS, version: Microsoft Windows 11 Pro, 10.0.22621 Build 22621
- Browser, version: Opera GX, LVL 5 (core: 102.0.4880.55)

**Comment by thomasbnt** [comment] 2023-09-23 14:19
Can reproduce on _Firefox 117_

![Preview bug z-index](https://github.com/forem/forem/assets/14293805/cf142fa8-c5ad-4140-b18d-c59bbf797fbd)

Seems weird, 
`.reaction-drawer` are a z-index of 400, and

![xsr2s](https://github.com/forem/forem/assets/14293805/7b9d4297-6a0a-4d01-bae8-1595b69be17c)

**Comment by thomasbnt** [comment] 2023-09-23 15:07
Okaaaaaaaaaay after some checking of the code, there is the PR about an old issue : 
https://github.com/forem/forem/pull/20035

**Comment by thomasbnt** [comment] 2023-09-23 15:21
I want to fix this issue.

**Comment by jun-low** [comment] 2023-09-26 02:12
Duplicate of #20143

**Closed** 2023-09-26 23:08 UTC
Labels: bug
