### ISSUE TITLE
Hidden comments on a thread hide the rest of the thread

### ISSUE THREAD

**Issue by cherscarlett** [forem/forem#13730] opened 2021-05-11 15:22 UTC
**Describe the bug**

When a comment is deleted because of a CoC violation, the rest of the comments in that thread remain visible, so that way healthy commentary that may have happened around the destructive comments can be read and continue a dialogue. When a comment is hidden by the author, it also hides everything that came after it. My expectation would be, as an author, to able to hide any comments that I feel don't want to be shown within a thread, and allow other comments to be surfaced in the same way deleting a comment does. 

**To Reproduce**

1. Go to a post you are authorized to hide comments on.
2. Find a threaded post with replies.
3. Click "...".
4. Click "Hide"
5. Confirm with "Ok"

**Expected behavior**

I would expect to see that a comment was hidden with the remainder of the thread visible.

When a comment is deleted:
![image](https://user-images.githubusercontent.com/260048/117841307-ca2cb000-b231-11eb-891e-cfc9f7fff664.png)

When a comment is hidden:
![image](https://user-images.githubusercontent.com/260048/117841473-f2b4aa00-b231-11eb-9e01-3812f7591f0f.png)

**Comment by benhalpern** [comment] 2021-06-10 21:44
> I would expect to see that a comment was hidden with the remainder of the thread visible.

I wouldn't be surprised if we justified this as expected behavior, but it doesn't seem so expected after all. 😄

My concern in thinking about this is that if the parent comment is hidden (to protect against abuse?), it might bring in more abuse if the children can be visible. Since the "hide comment" is under the author's control, we try to bring _less_ attention to the hidden-ness of it all as to not promote any kind of mob reaction to the hiding action.

It seems reasonable that this could be _an option_ available in the confirmation dialog.

i.e.

☑️ Hide all child comments too?

**Comment by mstruve** [comment] 2021-06-17 20:27
@benhalpern I think you bring up some really great points. If you are game to execute that above approach you suggested to give users the option we can definitely get this prioritized and worked on. The only hold up was that we wanted some product input 🙂  Let me know what your thoughts are on moving this forward!

**Comment by cherscarlett** [comment] 2021-06-18 18:27
@benhalpern that makes complete sense 👍🏼 this change sounds awesome

**Comment by benhalpern** [comment] 2021-06-21 23:45
So in order to implement this, here are the details of an actual approach....

- Replace the _alert dialog_ with a modal which allows for a full form with the check box for that one more thing being submitted to the form.
- Add one more boolean for this setting on the comment.
- Add alternate display logic which accounts for the two modes.
  - Given that we already essentially have both logical scenarios available in the `deleted` logic as originally pointed out by @cherscarlett, closing the loop on this is mostly a matter of wrapping one's head around the functionality and writing good tests. The logical structure of comment trees already supports this.

This is the rather inelegant dialog we use now, which will be replaced by the nicer designed modal, so we'll leave the functionality in a better place than it was.

<img width="471" alt="Screen Shot 2021-06-21 at 7 35 25 PM" src="https://user-images.githubusercontent.com/3102842/122840306-d6436d00-d2c7-11eb-9be6-411dfc192663.png">

***

Structurally things seem in a good place to accept this functionality, but it will require careful tests and QA to make sure it takes well. 😄

**Comment by lightalloy** [comment] 2021-11-23 08:14
The feature was implemented in #15178

**Closed by lightalloy** 2021-11-23 08:14 UTC
Labels: Forem team, size: estimated S, tech: fullstack, area: comments & notifications
