### ISSUE TITLE
Grammarly extension causing text fields on making a new post disabled

### ISSUE THREAD

**Issue by tolentinoel** [forem/forem#13814] opened 2021-05-20 04:12 UTC
**Describe the bug**
I was trying to write a blog post today and couldn't. Once you're on the New Post page, it wouldn't let me edit the text fields for the title and the body of the blog. I have tried to log in and logout, exit the browser and relaunch it, even copy-paste my entry but nothing seemed to work. When I paste the entry in one text field, it does the trick but won't let me click into the other one after. 

**To Reproduce**

1. Log in
2. Click Write a Post
3. Click one text field.
4. System recognizes the click(The markdown tip on the right shows up). But wouldn't let you edit.

**Expected behavior**
I was expecting a normal behavior in which I can post my article. The only features that are working are the tags, cover photo upload, image upload,

 and putting it on your drafts.

**Screenshots**
![Screen Shot 2021-05-19 at 9 09 31 PM](https://user-images.githubusercontent.com/57022050/118917825-89dec900-b8e6-11eb-88fb-b79473a9c449.png)
You might not see but there is no cursor on any text field yet the markdown tip on the right recognizes that I clicked to edit the text field. It only let me type one letter and it stopped right after that

**Desktop (please complete the following information):**

- OS, version: MacOS Big Sur 11.3
- Browser, version: Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by Nikhil27b** [comment] 2021-05-20 11:01
Same for me unable to write a new blog text filed disabled for me but in my phone its work fine

**Comment by jashgopani** [comment] 2021-05-20 13:07
Even I am unable to edit my existing blogs because of this error

**Comment by Link2Twenty** [comment] 2021-05-20 13:16
@Nikhil27b and @jashgopani are you both on MacOS too?

Are any of you seeing any errors in your consoles (Option + ⌘ + J (on macOS) or Shift + CTRL + J (on Windows/Linux))? I'm unable to reproduce the error.

**Comment by Nikhil27b** [comment] 2021-05-20 13:19
No I am windows user an I check for error but I don't find anything

**Comment by cmgorton** [comment] 2021-05-20 13:47
Hey all, @tolentinoel , @jashgopani @Nikhil27b do any of you have Grammarly installed? We were able to reproduce this yesterday with several team members and ever one of them had Grammarly. We have so far found this to be bug on Grammarly's end. They had a recent update.

**Comment by Nikhil27b** [comment] 2021-05-20 13:55
Thank you now its works I uninstalled the Grammarly  

> Hey all, @tolentinoel , @jashgopani @Nikhil27b do any of you have Grammarly installed? We were able to reproduce this yesterday with several team members and every one of them had Grammarly. We have so far found this to be bug on Grammarly's end. They had a recent update.

**Comment by cmgorton** [comment] 2021-05-20 14:08
Thanks for the confirmation. We are working to see if there is something on our end we can do in the meantime but for now the only course of action is to disable Grammarly until Grammarly releases a bug fix.

**Comment by Link2Twenty** [comment] 2021-05-20 14:16
As a quick patch we could add `data-gramm_editor="false"` to the text area

https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L367-L377

But that really is a bodge.

**Comment by nickytonline** [comment] 2021-05-20 14:55
So there is definitely an issue with Grammarly in Chrome only when using the editor in a Forem instance.

![image](https://user-images.githubusercontent.com/833231/119001038-a1a36500-b959-11eb-82bb-62afe78a2e63.png)

I pretty-printed the Grammarly source code for their extension and found where it blows up, but I don't have the full context as the code is obfuscated. The `82987` function gets called in 3 spots in the obfuscated code.

```
    82987: (e,t,n)=>{
        n.d(t, {
            N: ()=>r
        });
        var r = function() {
            function e() {
                return Error.call(this),
                this.message = "object unsubscribed",
                this.name = "ObjectUnsubscribedError",
                this
            }
            return e.prototype = Object.create(Error.prototype),
            e
        }()
    }
```

I've tested other browsers and so far it doesn't seem to be an issue.

Although it disables Grammarly, we can do what @Link2Twenty is proposing (Grammarly proposes this too when it causes issues). What I would suggest though is we only add this data attribute for Chrome, not all browsers. That way, users who are not affected can still have the benefit of using Grammarly in their preferred browser.

User-agent detection is not usually the way to go these days, but I think this is a valid use case. I would suggest using a regex to detect if Chrome is being used, but ensure it's not Edge, Brave or any other Chromium-based browser.

If we detect Chrome is being used, then add the `data-gramm_editor="false"`.

**Comment by nickytonline** [comment] 2021-05-20 14:57
One other thing to note is that this probably affects comments as well.

**Comment by cmgorton** [comment] 2021-05-20 14:59
@Link2Twenty would you be interested in implementing this fix? Along with the suggestions Nick mentioned.

**Comment by nickytonline** [comment] 2021-05-20 15:03
Tagging @aitchiss so she's in the loop.

**Comment by nickytonline** [comment] 2021-05-20 15:14
Also linking to this comment from another repo having issues with Grammarly. https://github.com/quilljs/quill/issues/574#issuecomment-818525715

**Comment by aitchiss** [comment] 2021-05-20 15:19
Interestingly, it doesn't seem to be affecting comments, only the editor 🤔

**Comment by Link2Twenty** [comment] 2021-05-20 16:01
It looks like it's to do with state changes... But it doesn't really make sense.

```jsx
<Form
  titleDefaultValue={title}
  titleOnChange={linkState(this, 'title')}
  tagsDefaultValue={tagList}
  tagsOnInput={linkState(this, 'tagList')}
  bodyDefaultValue={bodyMarkdown}
  //bodyOnChange={linkState(this, 'bodyMarkdown')}
  bodyHasFocus={false}
  version={version}
  mainImage={mainImage}
  onMainImageUrlChange={this.handleMainImageUrlChange}
  errors={errors}
  //switchHelpContext={this.switchHelpContext}
/>
```

This makes it 'work' but obviously breaks those features.

I can't see anything that should be making the focus be lost (which is what is happening).

**Comment by Link2Twenty** [comment] 2021-05-20 17:20
OK my findings are

Preact redraws the textarea on state change meaning grammarly loses the textarea and sets focus to back to body. Comments don't use preact yet and thusly don't have the same issue.

If Grammarly is not installed preact does not redraw.

I don't really know where to go from here 😅

**Comment by nickytonline** [comment] 2021-05-20 17:44
Thanks for digging @Link2Twenty!

Comments do use Preact as we bootstrap the mention autocomplete in them. The main difference is the comment text area exists before Preact bootstraps.

**Comment by Link2Twenty** [comment] 2021-05-20 17:47
I've implemented the quick if it's chrome don't run grammerly logic but I think we'll need to revisit this.

**Comment by aitchiss** [comment] 2021-05-20 17:54
I've noticed that the issue occurs also in the Connect chat message composer textarea...

Interestingly all three of the affected areas use the auto-resize hook 🤔

**Comment by Link2Twenty** [comment] 2021-05-20 18:26
I noticed that resize was in both too but pulling out

```jsx
useLayoutEffect(() => {
  if (textAreaRef.current) {
    setConstrainToContentHeight(true);
    setTextArea(textAreaRef.current);
  }
}, [setTextArea, setConstrainToContentHeight]);
```

Didn't seem to make a difference.

**Comment by tolentinoel** [comment] 2021-05-20 19:33
Yeah! I have grammarly installed! Does that mean I would have to uninstall that first to have it working for now?

>

**Comment by aitchiss** [comment] 2021-05-21 08:28
@tolentinoel - yes if you disable grammarly for now while you're drafting your posts, it will work fine (you don't need to fully uninstall from your browser extensions, just disable it in the extension settings for that page)

**Comment by aitchiss** [comment] 2021-05-21 08:29
> I noticed that resize was in both too but pulling out
> 
> ```js
> useLayoutEffect(() => {
>   if (textAreaRef.current) {
>     setConstrainToContentHeight(true);
>     setTextArea(textAreaRef.current);
>   }
> }, [setTextArea, setConstrainToContentHeight]);
> ```
> 
> Didn't seem to make a difference.

@Link2Twenty yeah like you said it seems to be something related to the state updates on change. very strange!

**Comment by aitchiss** [comment] 2021-06-25 10:00
As a small update, we contacted Grammarly support about the errors we're seeing, and received a response:

> Unfortunately, we don’t currently have a quick fix, but please rest assured that our team has been made aware of the issue. I can’t provide you with an estimated timeframe right now because the developers need some time to analyze the cause of the issue.
In the meantime, we suggest you use our online Grammarly Editor at https://app.grammarly.com or Grammarly’s desktop app. Also at your disposal: Grammarly for Microsoft Office (available to Windows OS users) and Grammarly for Microsoft Word on Mac.

**Comment by cmgorton** [comment] 2021-09-09 14:53
Since we are waiting on Grammarly for a fix for this one I am going to go a head and close this issue. When we get more information from Grammarly we can open it back up if needed.

**Closed by cmgorton** 2021-09-09 14:53 UTC
Labels: bug, area: publishing experience
