### ISSUE TITLE
Infinte scrolling needs to be fix on https://dev.to/ homepage 

### ISSUE THREAD

**Issue by krishnadevz** [forem/forem#11576] opened 2020-11-23 16:44 UTC
**Is your feature request related to a problem description**
*As we go through the https://dev.to/ homepage we can see one thing like when we scroll down for viewing more articles or else 
if ex I am or any user is curious about dev.to social media links or shop details or reading list podcasts etc all **footer**
stuff then from the home page we cannot do that like infinite scroll is there I think we do one thing we can show first 100 articles to the users then one **show more** button that will be fine. 

**Describe the solution you'd like**
*As we go through the https://dev.to/ homepage we can see one thing like when we scroll down for viewing more articles or else 
if ex I am or any user is curious about dev.to social media links or shop details or reading list podcasts etc all **footer**
stuff then from the home page we cannot do that like infinite scroll is there I think we do one thing we can show first 100 articles to the users then one **show more** button that will be fine. 

* infinite scroll issue in the homepage for articles and problem to see footer content.

* GIF/picture  issue description 
![descripfeaturesss](https://user-images.githubusercontent.com/42638797/99989715-f74aea80-2dd8-11eb-9a08-d6f4863669ac.gif)

**Desktop:**

- OS, version: windows version 20H2 os build 19042.630
- Browser, version: firefox=83.0 (64-bit)/chrome=Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by cmgorton** [comment] 2020-11-23 18:14
Hey @krishnadevz thanks for opening this issue. It is a duplicate of #9034 . Please feel free to add to the discussion in that issue. I am going to go a head and close this one :)

**Closed by cmgorton** 2020-11-23 18:14 UTC
