### ISSUE TITLE
Need feature to see who liked, viewed

### ISSUE THREAD

**Issue by nehrakln07** [forem/forem#10204] opened 2020-09-04 11:10 UTC
**Is your feature request related to a problem? Please describe.**

feature to see a list of the people who liked view for a post while seeing stats on the dashboard.

You can refer twitter feed where when click on the numbers neer icon you can see the list of people who liked, retweeted.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment] 2020-09-04 12:08
Hi @nehrakln07. I'm going to close this as as duplicate of https://github.com/forem/forem/issues/6608 - Feel free to leave your comment over and thank you!

**Closed by rhymes** 2020-09-04 12:08 UTC
