### ISSUE TITLE
Unable to log in via twitter.

### ISSUE THREAD

**Issue by dpaulino** [forem/forem#5003] opened 2019-12-04 06:50 UTC
**Describe the bug**

Unable to log in using Twitter. The "good news, bad news" webpage is displayed when I try.
![image](https://user-images.githubusercontent.com/7649589/70119320-dfee7c80-161e-11ea-94b3-f16174f92d2c.png)

**To Reproduce**

1. Go to dev.to using chromium edge
2. click the log in via twitter button
3. the "good news, bad news" webpage is displayed.

**Expected behavior**

I expect to be able to sign in.
**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chromium edge
- Version: 80.0.334.4

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**
Side note, I found it funny how the webpage says I'm offline when I am clearly online 😂 Does the webpage not check if I have internet before posting that comment? 
![image](https://user-images.githubusercontent.com/7649589/70119430-217f2780-161f-11ea-9c73-285eaf85fb59.png)

**Comment by maestromac** [comment] 2019-12-04 16:45
Sorry for this issue @dpaulino . Are you able to reproduce this issue on another browser on your machine?

**Comment by dpaulino** [comment] 2019-12-04 18:08
I am now able to reproduce the bug reliably. Updated repro steps:

1. Launch Microsoft Edge Dev: https://www.microsoftedgeinsider.com/en-us/download/
2. Open settings menu > Privacy
3. Enable strict tracking prevention
![image](https://user-images.githubusercontent.com/7649589/70168472-cb8d9c80-167d-11ea-99ff-57006361d65e.png)
4. Navigate to dev.to
5. Click on twitter sign in button
6. Error page.

Is dev.to doing something that is considered as non-standard or malicious when logging in?

Also, here's my console while getting this error.
![image](https://user-images.githubusercontent.com/7649589/70168560-f972e100-167d-11ea-85a4-fef6bde2f8f0.png)

**Comment by maestromac** [comment] 2019-12-04 20:09
Thank you for the detailed reproduction steps. I believe this is more of a browser support issue as the login is functional on Chrome and Firefox.

**Comment by christyram99** [comment] 2019-12-09 12:22
Hi @maestromac, I am interested in contributing. Can I contribute to this issue?

**Comment by sai-chai** [comment] 2019-12-10 02:49
I reproduced it on my own machine and it looks like the warnings that you're getting are actually about the drawing mini-game. It looks like that mini-game might not work on a touch device running in Chromium Edge.

**Comment by sai-chai** [comment] 2019-12-10 03:51
As for the twitter auth error itself, the console was being cleared between page loads so I checked Preserve Log, and tried it again. I got this error: 

<img width="591" alt="Screen Shot 2019-12-09 at 8 44 01 PM" src="https://user-images.githubusercontent.com/27644730/70491276-7e1e8e80-1ac6-11ea-94ad-4a5e1acba955.png">

So it doesn't look like Edge is actually blocking Twitter or Dev.to from setting any cookies or such, and Twitter isn't being navigated to either. In fact, I went into the "blocked trackers" list in Settings and neither showed up. 🤔

It could be an unknown Edge bug that only affects serviceworkers while strict tracking prevention is turned on. 
Here's the request that's causing that failure:
```
request: Request	
method: "GET"	
url: "https://dev.to/users/auth/twitter?callback_url=https://dev.to/users/auth/twitter/callback"	
headers: Headers {}	
destination: "document"	
referrer: "https://dev.to/"	
referrerPolicy: "strict-origin-when-cross-origin"	
mode: "navigate"	
credentials: "include"	
cache: "reload"	
redirect: "manual"	
integrity: ""	
keepalive: false	
signal: AbortSignal {aborted: false, onabort: null}	
isHistoryNavigation: false	
bodyUsed: false	
__proto__: Request
```

Could it be the referrer policy that's causing Edge to block it?

**Comment by FreekVR** [comment] 2019-12-12 09:00
Just to confirm, am getting the same errors in Chromium Edge (Beta 79x). Github login is working fine. Unfortunately, it doesn't look like anything that Edge tracking prevention does is logged to the console :(

I added a tracking prevention exception for dev.to to workaround the issue (was set to "strict" as reported earlier): edge://settings/privacy/trackingPreventionExceptions

**Comment by sai-chai** [comment] 2019-12-12 22:28
> Unfortunately, it doesn't look like anything that Edge tracking prevention does is logged to the console :(
You have to change the console to show verbose errors to see those logs. Unfortunately, the error that dev.to is encountering with tracking prevention is rather cryptic and is being thrown by Dev's service worker, not by Edge itself. So it seems like a bug, not a feature.

**Comment by sai-chai** [comment] 2019-12-13 02:45
Okay, I think this might be a clue. The auth endpoints on dev.to for Github and Twitter use different parameters. 

The Twitter endpoint uses `/auth/twitter?callback_url=https://dev.to/users/auth/twitter/callback`
The Github endpoint on the other hand uses `/auth/github?state=navbar_basic`

I have a theory (and I'm pretty sure this is a bug) that Edge is blocking the twitter endpoint because it passes a complete URL as a URL parameter. Maybe we could encode the callback URL before passing it to `/auth/twitter`? Also, if we're only using one URL as the callback for twitter authentication, then the `callback_url` parameter is unnecessary.

**Comment by rhymes** [comment] 2020-03-20 12:37
Hi @dpaulino, I saw you closed the issue. Is it because you've find a solution? If so, which? It might help the other ones that have experienced it as well. Thank you!

**Comment by dpaulino** [comment] 2020-03-20 16:06
Oops, that was accidental. I did a bulk close and I missed this. Reopening now

**Comment by rhymes** [comment] 2020-10-01 08:16
I'm closing this as I believe it's not an issue anymore as we've since reworked login and params and was definitely able to login with Twitter on Edge

**Closed by rhymes** 2020-10-01 08:16 UTC
Labels: ready for dev, type: bug
