### ISSUE TITLE
Copy image to Clipboard not working on Safari

### ISSUE THREAD

**Issue by dmahely** [forem/forem#11298] opened 2020-11-06 13:47 UTC
**Describe the bug**

While writing a new post in Safari, I uploaded an image and the site generated the markdown tag with the placeholder alt text and url. When clicking on the 'copy' icon, no message is shown. Trying to paste will paste whatever was copied before the image tag. 

**To Reproduce**

1. Go to dev.to/new on Safari
2. Click on upload image
3. When the image tag is generated, click on the copy icon
4. Paste anywhere

**Expected behavior**

The image tag will be pasted

**Desktop**

- OS, version: macOS Mojave 10.14.6
- Browser, version: Safari 13.0.5

**Additional context**

I read a few other issues that commented on the same problem, and it seems that it was fixed in other browsers and Android, e.g. https://github.com/forem/forem/issues/7251. I tried to replicate the issue in Chrome 86.0.4240.183 but wasn't able to.

I also noticed this error in the console:
`Unhandled Promise Rejection: Unsupported device unable to copy to clipboard`

**Comment by fdoxyz** [comment] 2020-11-06 23:48
I was unable to reproduce on dev.to with Safari `Version 14.0 (15610.1.28.1.9, 15610)`. Looking at [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) it seems like the `navigator.clipboard` API is supported on Safari starting with version `13.1`.

The easiest solution seems to be to update to a more recent version of Safari (recommended for security updates too).

I understand it's sometimes not possible, so a possible workaround is to add another fallback to the [copyToClipboard](https://github.com/fdoxyz/forem/blob/master/app/assets/javascripts/initializers/runtime.js#L62-L79) function. Since the API is currently not supported on that browser the rejection goes unhandled. This is where the error log mentioned in the console comes from (`Unhandled Promise Rejection: Unsupported device unable to copy to clipboard`).

An example of the previous API used to support this in older browsers:

```
// input represents a DOM input element
input.setSelectionRange(0, input.value.length);
document.execCommand('copy');
```

**Comment by dmahely** [comment] 2020-11-08 13:53
Thank you for your response @fdoxyz.
I did think of updating Safari first, but I think that's not possible with the OS version I'm on and I don't want to update at the moment.

**Comment by dmahely** [comment] 2020-11-09 17:35
FYI for anyone else facing the same issue: dragging and dropping an image into the editor (markdown editor at least) will add the image tag where your cursor was, which makes for a much better experience.

**Comment by aitchiss** [comment] 2022-08-12 12:11
Closing this one since the image upload flow for the main editor doesn't rely on this copy text field any more, and newer versions of safari are working with the old-style copy/paste flow in the v1 editor 🙂

**Closed by aitchiss** 2022-08-12 12:11 UTC
Labels: bug, area: publishing experience
