### ISSUE TITLE
`[missing "en.core.edit_profile" translation]` error message shown on right sidebar

### ISSUE THREAD

**Issue by vinitshahdeo** [forem/forem#14851] opened 2021-09-29 09:07 UTC
While visiting one of my `Dev.to` [post](https://dev.to/vinitshahdeo/calling-out-beginners-for-a-community-led-mentorship-opportunity-for-hacktoberfest-16gh), I am seeing `[missing "en.core.edit_profile" translation]` on the right sidebar - seems like an error message getting surfaced.

- Here's the [link](https://dev.to/vinitshahdeo/calling-out-beginners-for-a-community-led-mentorship-opportunity-for-hacktoberfest-16gh) to blog post
- Here's my `DEV` [profile](https://dev.to/vinitshahdeo)

**Screenshot**

![Screenshot 2021-09-29 at 2 32 01 PM](https://user-images.githubusercontent.com/20594326/135238307-7c1165ac-ace7-48a7-8ddd-3f80b7487b83.png)

**Comment by vinitshahdeo** [comment] 2021-09-29 09:09
I can reproduce the same on the profile page too.

[![Screenshot 2021-09-29 at 2 38 14 PM](https://user-images.githubusercontent.com/20594326/135238849-bca533b5-ad87-4c1b-82d2-984faa859c60.png)](https://dev.to/vinitshahdeo)

**Comment by rhymes** [comment] 2021-09-29 10:46
@vinitshahdeo taking a look, thank you!

**Comment by rhymes** [comment] 2021-09-29 11:10
Mmm I can't reproduce as in I see the actual text if I go to your profile on DEV:


![Screenshot 2021-09-29 at 13-09-02 Vinit Shahdeo — DEV Community Profile](https://user-images.githubusercontent.com/146201/135257270-36ad55a8-1bc0-4e50-8a2b-7ac956bc5780.png)

I wonder if it's a caching issue. Can you try with a fresh cache or another browser?

I'll keep investigating.

**Comment by vinitshahdeo** [comment] 2021-09-30 04:56
@rhymes Thanks. Now I'm unable to reproduce this. Maybe it's a cache issue.

**Comment by citizen428** [comment] 2021-09-30 05:06
Thanks for the feedback @vinitshahdeo, I'll close this issue then, feel free to reopen it if you experience this problem again.

**Closed** 2021-09-30 06:52 UTC
Labels: bug, area: internationalization/localization
