### ISSUE TITLE
Website broken in Safari 13.1, infinite hang right from the get-go

### ISSUE THREAD

**Issue by wrldwzrd89** [forem/forem#6902] opened 2020-03-27 00:59 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.4
- Browser: Safari
- Version: 13.1

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Likely related to changes in 13.1. Worked just fine with 13.0. Cookie handling, perhaps?

**Comment by citizen428** [comment] 2020-03-27 04:14
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment] 2020-03-27 04:15
Thank you @wrldwzrd89. I haven't updated yet, so can't currently verify this. If nobody else picks this up I'll circle back to it as soon as I'm on the new macOS/Safari.

**Comment by rhymes** [comment] 2020-03-27 07:57
I have Safari 13.1, I can confirm the website does not load with it. Taking a look right now

**Comment by rhymes** [comment] 2020-03-27 08:00
After a couple of refreshes the website appeared again, and I'm unable to reproduce nor I have anything logged as the console was wiped out with the refreshes :(

@wrldwzrd89 are you still experiencing this?

**Comment by hnk** [comment] 2020-03-27 10:53
To chip in: I had the same issue.

Deleting the 'website data' for dev.to immediately fixed the issue.

This workflow is translated from German, so it may not be 100% correct:
Settings -> Privacy -> Manage website data -> Search for dev.to -> Remove

**Comment by rhymes** [comment] 2020-03-27 10:59
> To chip in: I had the same issue.
> 
> Deleting the 'website data' for dev.to immediately fixed the issue.
> 
> This workflow is translated from German, so it may not be 100% correct:
> Settings -> Privacy -> Manage website data -> Search for dev.to -> Remove

This is a huge clue! That setting allows the user to delete the cache, the cookies and the local storage. 🕵

**Comment by wrldwzrd89** [comment] 2020-03-27 20:15
OK, I will try deleting the website data for dev.to and report back.

**Comment by wrldwzrd89** [comment] 2020-03-27 20:18
Success - doing that got both Mac Safari and iOS Safari working again. Still not sure why it broke, though.

**Comment by cadonau** [comment] 2020-03-27 20:44
> To chip in: I had the same issue.
> 
> Deleting the 'website data' for dev.to immediately fixed the issue.
> 
> This workflow is translated from German, so it may not be 100% correct:
> Settings -> Privacy -> Manage website data -> Search for dev.to -> Remove

I was having the same issues on iOS and now macOS today and thought that the website was down, at first.

For me, [this type of bug actually startet happening some 600+ days ago](https://twitter.com/mcadonau/status/1026485898333048832) in Safari View Controller on iOS, which is really annoying when you mostly discover/read posts through a Twitter client. If I remember correctly, this was after some PWA offline stuff was implemented.

I'm still hoping it can be fixed. Good luck!

**Comment by stltt** [comment] 2020-04-03 13:30
Same issue on my iPad. 

Including pertinent details from the issue I opened ([#7057](https://github.com/thepracticaldev/dev.to/issues/7057)) and closing it.


The problem does not manifest on Chrome or Firefox

    OS: IOS 13.4
    Browser: Safari
    Version: N/a
    non-default Safari settings: DuckDuckGo search

**Comment by atsmith813** [comment] 2020-07-14 14:21
I think this may actually be covered by #9250. What do you think @fdoxyz?

**Comment by fdoxyz** [comment] 2020-07-14 20:42
I think it may be @atsmith813, thank you for flagging this so we can close all these issues as soon as the fix is confirmed!

The PR was merged and deployed, but I have been running into some weird behavior and I think our cache is the culprit. The easiest solution I think is to wait until the older version expires organically, because [https://dev.to/serviceworker.js](https://dev.to/serviceworker.js) still shows the outdated version for me (even with a hard refresh 🤔).

I'll be sure to check back to all these linked issues if this changes, hopefully tomorrow.

**Comment by ludwiczakpawel** [comment] 2021-01-25 14:05
I've just tested it with older versions of Safari (including 13.1) and can't repro this issue. Also, it's been some time since it was originally reported and since that time, we've made lots of changes around this area. For that reason, I've decided to close this issue but I'll leave the conversation open - if this still happens to someone we can dig deeper.

**Closed by ludwiczakpawel** 2021-01-25 14:05 UTC
Labels: bug
