### ISSUE TITLE
Change the default page

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#10666] opened 2020-10-06 15:36 UTC
**Is your feature request related to a problem? Please describe.**

I have as shortcut "https://dev.to/latest" and not "https://dev.to" because I prefer to look at the last posts and then after the most noticed ones. It doesn't bother on computer, but on phone or even on the application it's very slightly annoying. It's just a question of speed, nothing more.

**Describe the solution you'd like**
^

Have a choice in settings to change the default page.

**Comment by rhymes** [comment] 2020-10-06 16:23
I think this is a duplicate of https://github.com/forem/forem/issues/9045 - please add your comment there @thomasbnt, thank you!

**Closed by rhymes** 2020-10-06 16:23 UTC
