### ISSUE TITLE
Navigation Bar Overlapping 

### ISSUE THREAD

**Issue by jatin2003** [forem/forem#11223] opened 2020-11-01 14:35 UTC
**Describe the bug**

When visiting the user profile (here [Ben](https://dev.to/ben)), the content on the side is overlapping with the navigation bar.

**Screenshots**

![Ben Halpern - DEV Community)](https://user-images.githubusercontent.com/56562571/97805575-f365f580-1c7c-11eb-9f65-4857a6a37c88.gif)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 86

**Comment by citizen428** [comment] 2020-11-02 04:37
Closing this as a duplicate of #11202

**Closed by citizen428** 2020-11-02 04:37 UTC

**Comment by jatin2003** [comment] 2020-11-02 08:07
Sorry, I didn't saw that issue earlier 😅
