### ISSUE TITLE
Fullscreen button on article code block has huge svg icon path viewbox size

### ISSUE THREAD

**Issue by matrixx** [forem/forem#11747] opened 2020-12-04 17:49 UTC
This issue only rises up when some of the scripts fail to load. Apparently one of those failed to load scripts include css which overrides this svg path viewbox size which is huge by default. Here's a screenshot (from my colleague) from Firefox which does not use any ad blockers. The screenshot is a little bit scaled down for the context, but as you can see the fullscreen icon is huge.

![image](https://user-images.githubusercontent.com/1188929/101196237-24b15700-3669-11eb-9125-46a6f01f5583.png)

The size is 448 x 512 even though normally the icon is shown as 16 x 16:
```
<div class="highlight__panel-action js-fullscreen-code-action">
    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 448 512" class="highlight-action highlight-action--fullscreen-on"><title>Enter fullscreen mode</title>
        <path fill="#fff" d="M0 180V56c0-13.3 10.7-24 24-24h124c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12H64v84c0 6.6-5.4 12-12 12H12c-6.6 0-12-5.4-12-12zM288 44v40c0 6.6 5.4 12 12 12h84v84c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12V56c0-13.3-10.7-24-24-24H300c-6.6 0-12 5.4-12 12zm148 276h-40c-6.6 0-12 5.4-12 12v84h-84c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h124c13.3 0 24-10.7 24-24V332c0-6.6-5.4-12-12-12zM160 468v-40c0-6.6-5.4-12-12-12H64v-84c0-6.6-5.4-12-12-12H12c-6.6 0-12 5.4-12 12v124c0 13.3 10.7 24 24 24h124c6.6 0 12-5.4 12-12z"></path>
    </svg>
</div>
``` 

And here are some console log from my colleague which probably points out the failed script which has the correct size of the fullscreen icon:
```
13:28:59.784 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/runtime~Search-5ec5f41eb3c09400436a.js”. my-first-date-with-tailwind-57d7:28:1
13:28:59.852 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/assets/hello-dev-a33d069dda0cc1cfef81b71ac053adb1c4cfb617ad4140d02892b548b3081161.js”. my-first-date-with-tailwind-57d7:1591:1
13:28:59.921 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/assets/base-7b4225a18255cd93f336b035a111a621d1f896f66fa18e26141c1958a7dbeabb.js”. my-first-date-with-tailwind-57d7:31:1
13:28:59.992 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/Search-5b0e630aa6f089abbc66.chunk.js”. my-first-date-with-tailwind-57d7:30:1
13:28:59.993 Loading failed for the <script> with source “https://practicaldev-herokuapp-com.freetls.fastly.net/packs/js/vendor-2db052da96e92ab3c700.chunk.js”. my-first-date-with-tailwind-57d7:29:1
13:29:00.004
Uncaught TypeError: window.InstantClick is undefined
    254 responseTemplates.js:3
    Webpack 4
responseTemplates.js:3
13:29:00.218
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
```

Anyway, this does not probably happen very often, and in his case this fixed by reload, but I think that the root cause, the huge svg viewbox size could be changed smaller, if there is no real reason to be that big.

**Comment by matrixx** [comment] 2020-12-04 17:54
And actually I just checked the dimensions from the screenshot. The icon is even bigger than the viewbox size (over double, because the screenshot is scaled down). I don't understand where the size this big comes from, but you probably have, so letting you figure out the rest :)

**Comment by ludwiczakpawel** [comment] 2020-12-14 08:34
@matrixx Cheers, I think I know what's going on and I'll try to fix it asap :)

**Comment by matrixx** [comment] 2020-12-21 21:11
When you're able to confirm the cause, I would be interested to know what was it, and how was the fix like :)

**Comment by ludwiczakpawel** [comment] 2020-12-22 14:16
@matrixx I believe it was caused by the actual SVG code weirdness and the fact that it's "hardcoded" into existing posts - which means that if you make a change now in the SVG, it will probably not affect older posts but the new ones.. For some reason we hardcode icons into posts markdown I think. 

I've tried to fix the SVG and add some constraints to the CSS to make it a bit more bulletproof but it may not fix the existing posts, but only prevent it from happening in future (I hope!:))

**Comment by chiubaca** [comment] 2021-01-03 13:50
@ludwiczakpawel is there anyway that this can resolved for older posts?

**Comment by rhymes** [comment] 2021-01-04 11:39
@ludwiczakpawel @chiubaca if I'm not mistaken the change lies in `app/labor/code_block_parser.rb` which is included in the `MarkdownParser`, right?

https://github.com/forem/forem/pull/12010/files#diff-8edf6552df437adf8a42a5a2b1c74e09797c5a1af02136c14501e01e2826058c

That said, we need a data update script to re-save all existing articles once that change is merged.

 HTML is generated by a callback in the `Article` model, re-saving them will trigger the changed code and all should be well.

**Comment by ludwiczakpawel** [comment] 2021-01-04 14:33
> That said, we need a data update script to re-save all existing articles. It can be added to #12010. Let me know if you need help @ludwiczakpawel

@rhymes yea, I'll definitely need help with that.. Wanna push it to that PR? 

Also, out of curiosity: "data update script to re-save all existing articles" sounds like a very expensive task in terms of resources... Would that make our servers' fans fly? :D

**Comment by rhymes** [comment] 2021-01-04 15:05
@ludwiczakpawel ahhahaha probably. I'll update the PR with it :)

**Closed** 2021-01-13 14:17 UTC
Labels: area: design, type: bug
