### ISSUE TITLE
Not able to comment on Dev.To

### ISSUE THREAD

**Issue by ivanjeremic** [forem/forem#10281] opened 2020-09-11 10:08 UTC
I'm still not able to comment on DEV.to after months of trying, When I try to send my comment endless loading animation is showing up and nothing happens, I think this has something to do the way I signed up (GitHub), I already switched browsers and devices and everywhere the same. But interesting is I can create Posts but not comment.

The account is a bit older 2018 and I think in the beginning I was able to comment but then I changed the name username and email on GitHub.com maybe this has something to do with it?

Please can anyone from the Dev.to team take a look at my account and let me comment again. Thanks

**Comment by rhymes** [comment] 2020-09-11 10:13
Hi @ivanjeremic, have you contacted yo@dev.to ? It seems the issue is only related to your account. Thank you!

**Comment by ivanjeremic** [comment] 2020-09-11 10:14
> Hi @ivanjeremic, have you contacted [yo@dev.to](mailto:yo@dev.to) ? It seems the issue is only related to your account. Thank you!

Yes a while ago but no one responded.

**Comment by rhymes** [comment] 2020-09-11 13:10
Ok, going to close this in the meantime. Thank you!

**Closed by rhymes** 2020-09-11 13:10 UTC
