### ISSUE TITLE
bug - changing settings doesn't update profile until refresh on profile page

### ISSUE THREAD

**Issue by nhidtran** [forem/forem#5018] opened 2019-12-05 21:48 UTC
How - change the color of your profile in settings
Behavior - still the previous color. Needs to refresh on profile page to pull in settings changes
Expected - after changing settings --> navigating to profile will automatically update page

**Comment by carlows** [comment] 2019-12-11 00:52
I stumbled across this the other day, I'd like to take this issue, does anyone have any suggestions on what could cause this? Looks like some sort of caching issue to me 🤔

**Comment by carlows** [comment] 2019-12-11 23:22
I did a little research on this and what I found was that:

1. the first thing that gets executed is here: https://github.com/thepracticaldev/dev.to/blob/master/app/views/layouts/_user_config.html.erb#L3

The theme class is loaded from `localStorage`, which means that if there's not an existing value, the user will see the default theme.

2. This file does an asynchronous request to fetch the user data from the backend: https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initializeBodyData.js#L38

After it receives the response it calls `browserStoreCache` which in turn sets the user data in `localStorage`.

---

So the frontend is constantly fetching the previous value the user had in localStorage. 

As an idea, maybe we can delay the theming logic in `_user_config.html.erb` until after we have received the latest user data? However that way, I think the user will see an initial theme being applied, and then a second theme being rendered.

Thoughts on this, anyone?

**Comment by mikenath223** [comment] 2020-07-16 19:38
Good day,

I have an idea on how to tackle this issue. May I work on this?

Best Regards,
Michgolden Ukeje

**Comment by rhymes** [comment] 2020-07-17 05:44
@mikenath223 sure, what's your plan? I'm going to assign you the issue

**Comment by rhymes** [comment] 2020-10-01 08:13
@mikenath223 do you still plan on working on this issue?

**Comment by mikenath223** [comment] 2020-10-02 20:16
Yes, I do. However, I wasn't able to reproduce the issue on my browser(Chrome). I would be glad to receive better info as regards what the issue is.
Here is a gif of what I observed, as seen it actually updates the color of the profile after changing it in settings:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/33323077/94965860-28532100-04f4-11eb-93d0-a0828b0fd74a.gif)

Kindly let me know what the issue is, so I could begin fixing it.

Best regards,

**Comment by rhymes** [comment] 2020-10-04 14:08
I guess this one has been solved automatically :-( 

I think the most visible of these UI changes that needs refreshing is the theme change. For example:

![refresh](https://user-images.githubusercontent.com/146201/95017731-67e84d00-065b-11eb-9636-b8fd2164f63f.gif)

but it's outside of the scope of this issue and has its own issue: https://github.com/forem/forem/issues/3613

I'm going to close this, thanks @mikenath223

**Closed by rhymes** 2020-10-04 14:08 UTC
Labels: area: settings, difficulty: easy, ready for dev, type: feature request
