### ISSUE TITLE
Continue Button on "Onboarding Welcome Message" is not working

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9195] opened 2020-07-08 03:27 UTC
**Issue**: Continue button on "onboarding welcome message" is not working

**Platform**: Gitpod
**Oauth**: Github

Did I miss configuring something?

---

> ### New cases which raised through the comment section

### Case 01 

**OS**: CentOS 7.7
**Platform**: Hyper V, Virtual machine (local)

**Comment by Ridhwana** [comment] 2020-07-08 09:37
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Ridhwana** [comment] 2020-07-08 09:39
Hi @akhil-naidu, thank you for this issue. Can you please elaborate or provide a gif/screenshot? Is the `Continue` button not showing up completely, or is it when you tick the terms and conditions and code of conduct, is the button still disabled?

**Comment by akhil-naidu** [comment] 2020-07-08 10:01
I can see, but the button is disabled.
My instance link: https://3000-e59e57f8-6366-4e22-896a-41477593bf93.ws-us02.gitpod.io
You can log in through your GitHub, to see it for yourself

Also, here are some logs in my running console, which can give you more idea.
This is a log when I click on the continue button.

![Screenshot 2020-07-08 at 3 27 28 PM](https://user-images.githubusercontent.com/11688537/86905349-91aed800-c12f-11ea-9113-aa045ca85608.png)


Here is the screenshot of the onboard welcome message.
![Screenshot 2020-07-08 at 3 25 09 PM](https://user-images.githubusercontent.com/11688537/86905159-4c8aa600-c12f-11ea-9e09-4688cc3c84e9.png)

**Comment by joshpuetz** [comment] 2020-07-08 14:31
Hey @akhil-naidu, sorry this is happening to you! We have a number of open issues with Gitpod right now. I'm curious: are you running a workspace based on master? If not, can you try making sure you are caught up to at least this PR: https://github.com/thepracticaldev/dev.to/pull/8747 (it fixed an issue on Gitpod with allowing local requests).

**Comment by cainwatson** [comment] 2020-07-17 02:57
Hey @joshpuetz, I ran into this as well and was running the latest code on master.

**Comment by 0xC000005** [comment] 2020-08-26 14:53
@akhil-naidu 
I tried internal switch, external switch and NAT on hyper-v, and couldn't avoid the same error message.  **Golden Command** works, but `bin/container-setup` does not. 😥

I bought a fresh new vultr VPS running ubuntu 18.04 to make sure that the error is not caused by my hyper-v configuration, but I keep getting `connection refused.` on this brand new VPS if I run `bin/container-setup`. 
I tried various things in two days to determine the initial error message, but the error messages from `seed_1` and `sidekiq_1` started repeating the moment I ran `bin/container-setup`, so I guessed something is wrong with the script in `container-setup`.

However, I'm using a native installation on ubuntu 18.04 and the `bin/setup` works fine, except my welcome message interface still doesn't work. When I click the continue button, the server responds, but nothing happens on the web page.

This pic shows the error I reproduced on my ubuntu 18.04 hyper-v machine:
![](https://raw.githubusercontent.com/0xC000005/image-hosting/master/20200822054510.gif)


But I did locate the first line of log related to this event,  which I pasted below 👇. Hope it is helpful. 🥰

```
14:06:03 web.1       | Started PATCH "/onboarding_checkbox_update" for 24.85.193.170 at 2020-08-26 14:06:03 +0000
14:06:03 web.1       | Cannot render console from 24.85.193.170! Allowed networks: 127.0.0.0/127.255.255.255, ::1
14:06:04 web.1       | Processing by UsersController#onboarding_checkbox_update as */*
14:06:04 web.1       |   Parameters: {"user"=>{"checked_code_of_conduct"=>true, "checked_terms_and_conditions"=>true, "text"=>nil}}
14:06:04 web.1       | HTTP Origin header (http://137.220.40.98:3000) didn't match request.base_url (http://137.220.40.98:3000)
14:06:04 web.1       | Completed 422 Unprocessable Entity in 11ms (ActiveRecord: 0.0ms | Allocations: 1237)
14:06:04 web.1       |
14:06:04 web.1       |
14:06:04 web.1       |
14:06:04 web.1       | ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
14:06:04 web.1       |
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'
14:06:04 web.1       | devise (4.7.2) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `block in make_lambda'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
14:06:04 web.1       | actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:201:in `block in halting'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `block in invoke_before'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `each'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `invoke_before'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:110:in `block in run_callbacks'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:139:in `run_callbacks'
14:06:04 web.1       | actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
14:06:04 web.1       | activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
14:06:04 web.1       | actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
14:06:04 web.1       | actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
14:06:04 web.1       | omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
14:06:04 web.1       | omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
14:06:04 web.1       | omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
14:06:04 web.1       | omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
14:06:04 web.1       | bullet (6.1.0) lib/bullet/rack.rb:15:in `call'
14:06:04 web.1       | jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
14:06:04 web.1       | jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
14:06:04 web.1       | rack-attack (6.3.1) lib/rack/attack.rb:111:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/deflater.rb:44:in `call'
14:06:04 web.1       | warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
14:06:04 web.1       | warden (1.2.8) lib/warden/manager.rb:34:in `catch'
14:06:04 web.1       | warden (1.2.8) lib/warden/manager.rb:34:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/etag.rb:27:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/head.rb:12:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
14:06:04 web.1       | rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
14:06:04 web.1       | activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
14:06:04 web.1       | better_errors (2.7.1) lib/better_errors/middleware.rb:59:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
14:06:04 web.1       | web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
14:06:04 web.1       | web-console (4.0.4) lib/web_console/middleware.rb:19:in `block in call'
14:06:04 web.1       | web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
14:06:04 web.1       | web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
14:06:04 web.1       | ddtrace (0.39.0) lib/ddtrace/contrib/rails/middlewares.rb:17:in `call'
14:06:04 web.1       | honeycomb-beeline (2.1.1) lib/honeycomb/integrations/rack.rb:48:in `block in call'
14:06:04 web.1       | honeycomb-beeline (2.1.1) lib/honeycomb/client.rb:65:in `start_span'
14:06:04 web.1       | honeycomb-beeline (2.1.1) lib/honeycomb/integrations/rack.rb:36:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
14:06:04 web.1       | railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
14:06:04 web.1       | railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
14:06:04 web.1       | railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
14:06:04 web.1       | ahoy_matey (3.0.4) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
14:06:04 web.1       | sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
14:06:04 web.1       | rack-timeout (0.6.0) lib/rack/timeout/core.rb:151:in `block in call'
14:06:04 web.1       | rack-timeout (0.6.0) lib/rack/timeout/support/timeout.rb:19:in `timeout'
14:06:04 web.1       | rack-timeout (0.6.0) lib/rack/timeout/core.rb:150:in `call'
14:06:04 web.1       | request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/method_override.rb:24:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/runtime.rb:22:in `call'
14:06:04 web.1       | activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
14:06:04 web.1       | rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
14:06:04 web.1       | actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
14:06:04 web.1       | honeybadger (4.7.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
14:06:04 web.1       | honeybadger (4.7.2) lib/honeybadger/agent.rb:403:in `with_rack_env'
14:06:04 web.1       | honeybadger (4.7.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
14:06:04 web.1       | honeybadger (4.7.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
14:06:04 web.1       | honeybadger (4.7.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
14:06:04 web.1       | rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
14:06:04 web.1       | ddtrace (0.39.0) lib/ddtrace/contrib/rack/middlewares.rb:85:in `call'
14:06:04 web.1       | webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
14:06:04 web.1       | rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
14:06:04 web.1       | railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
14:06:04 web.1       | puma (4.3.5) lib/puma/configuration.rb:228:in `call'
14:06:04 web.1       | puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
14:06:04 web.1       | puma (4.3.5) lib/puma/server.rb:472:in `process_client'
14:06:04 web.1       | puma (4.3.5) lib/puma/server.rb:328:in `block in run'
14:06:04 web.1       | puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
14:06:04 web.1       |   User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 11], ["LIMIT", 1]]
14:06:04 web.1       |   Profile Load (0.2ms)  SELECT "profiles".* FROM "profiles" WHERE "profiles"."user_id" = $1 LIMIT $2  [["user_id", 11], ["LIMIT", 1]]
14:06:04 web.1       |   ↳ app/models/user.rb:37:in `block (4 levels) in <class:User>'
```

**Comment by akhil-naidu** [comment] 2020-08-26 15:15
try these solutions, it will remove them.

If you have a domain, then most of the things will go smoothly, at least that is how I solved my issue. 

I will explain, how I solved this issue, but this might not be the actual solution.

1. I have a domain in Cloudflare, so I created a CNAME record on the subdomain(ex: dev.leewardslope.com) and attached the external IP address.
2. As the Forem service is running on port 3000, we need to look at this issue, so I installed Nginx and port forwarded the fort 3000 to 80, so no need to use the port 3000 anymore. Here is a more detailed [guide](https://www.digitalocean.com/community/questions/how-do-i-point-my-custom-domain-to-my-ip-port-41-111-20-36-8080) which might be useful in configuring IP: PORT to a domain name.
3. In .env file, change the APP_DOMAIN to your domain, in my case: dev.leewardslope.com
4. Also, don't forget to update these in GitHub too, the URL for authentication, I guess you used localhost:300o or your IP:3000.

I'm a bit hurry and using mobile, so this might not look like formal and well-formatted instructions, but the overall essence is the same. Let me know if you have any doubts.

Also if you don't have a domain, you can use this site to create [free domain](https://www.freenom.com/) name.

**Comment by mirie** [comment] 2023-07-14 19:40
Looks like this issue is relatively resolved with a workaround. We're prioritizing local/remote development options this quarter, so closing this issue

**Closed by mirie** 2023-07-14 19:40 UTC
Labels: bug, area: containers, area: systems, tech: frontend
