### ISSUE TITLE
Improve dark-theme compatibility on /mod

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11647] opened 2020-11-28 16:37 UTC
**Is your feature request related to a problem? Please describe.**
As a user who 1) uses a dark theme, and 2) has access to `/mod` (I have `trusted`) status, I'm having trouble seeing all of the information on this page.

**Describe the solution you'd like**
Better compatibility (light text, etc) for dark themes on `/mod`.

**Additional context**
Here's a screenshot, I've selected some elements of the page to help "highlight" the issue.

<img width="1308" alt="mod page in dark mode" src="https://user-images.githubusercontent.com/9434801/100520827-a08d3a00-3165-11eb-916e-746c146c998a.png">

**Comment by dominicduffin1** [comment] 2020-12-01 20:53
I'd like to work on this!

**Comment by nickytonline** [comment] 2020-12-01 20:54
Great! Assigning this to you @dominicduffin1.

**Comment by dominicduffin1** [comment] 2020-12-04 18:22
My thinking is to add a `color` property to `.article-published-at`. There seems to be two options, either to use `var(--base-80)` or `var(--button-secondary-color)`. Looking through the code it appears the `--base` variables are used quite a bit but I also notice the pink theme varies which base is used in some circumstances, so using `--button-secondary-color` might be better. What are the team's thoughts on this?

**Comment by nickytonline** [comment] 2020-12-04 18:40
> My thinking is to add a `color` property to `.article-published-at`. There seems to be two options, either to use `var(--base-80)` or `var(--button-secondary-color)`. Looking through the code it appears the `--base` variables are used quite a bit but I also notice the pink theme varies which base is used in some circumstances, so using `--button-secondary-color` might be better. What are the team's thoughts on this?

cc : @ludwiczakpawel, @lisasy

**Comment by ludwiczakpawel** [comment] 2020-12-07 08:34
@dominicduffin1 

The `.article-published-at` element sounds like a class that could be used  elsewhere (not sure though!:P) so I wouldn't apply any extra styles to it so they don't potentially affect other places.

In this case it seems the bug is due to some weirdness going on with how this view has been implemented. Each row of this "table" seems to be a `button` element and buttons come with some default browser-based styling, that seems  like we haven't overwritten. I'd recommend adding `color: var(--base-100)` to [that button](https://github.com/forem/forem/blob/126c2401e30e3950e93bbfef0f7518de33615e0f/app/assets/stylesheets/views/mod-center.scss#L42-L52) and it should do the trick I believe.

It would be a bit more bulletproof and "safe" solution because if we ever add a column to this "table" it won't require similar fix anymore.

**Comment by dominicduffin1** [comment] 2020-12-07 14:07
@ludwiczakpawel That makes sense, I'll do that!

**Comment by Glennmen** [comment] 2020-12-07 15:10
Duplicate of #5738 ? 🤔

**Comment by ludwiczakpawel** [comment] 2020-12-07 20:08
@Glennmen Kinda I guess.. Original description of that issue was about old (in terms of design) mod tools... This is a bit more up-to-date I think.

**Closed** 2020-12-08 09:33 UTC
Labels: area: moderation, area: themes, tech: html/css, type: bug
