### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by RDIL** [forem/forem#12471] opened 2021-01-28 19:16 UTC
**Describe the bug**

On the homepage, you can never get to the footer because more articles just keep loading in.

**To Reproduce**
Go to dev.to signed out, try to get to the footer at the bottom of the page.

**Expected behavior**

n/a - there should be a better way of doing this (load more button?)

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Firefox nightly

**Additional context**

**Comment by cmgorton** [comment] 2021-01-28 19:24
Hey @RDIL this is a known issue and a duplicate of #8256. #5670 is also similar. If you would like to add any comments to those issues please do. I plan on adding issue #8256 to our internal review board this next week.

**Closed by cmgorton** 2021-01-28 19:24 UTC
