### ISSUE TITLE
New post appears liked by default in Notifications on Forem.dev

### ISSUE THREAD

**Issue by Amorpheuz** [forem/forem#10120] opened 2020-09-01 05:42 UTC
**Describe the bug**
A new post on Forem.dev is appearing in my notification feed as `liked` even though I hadn't read the post yet. URL to post:
https://forem.dev/ben/new-starter-state-coming-soon-5gmn. I think it is a visual bug since when I open the article itself, the reactions load correctly, i.e. no reactions (no hearts, unicorns).

Another article after the bugged article didn't have this bug and appears correctly.

**To Reproduce**
Not sure how this can be reproduced. 🤔 Maybe if you got a similar notification for the post and it's also bugged?

**Expected behavior**
Notification renders correctly with no heart.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/91798980-bf9e2d80-ec43-11ea-9681-f8ae0c44c7fb.png)
![image](https://user-images.githubusercontent.com/22113778/91798992-c6c53b80-ec43-11ea-8571-16de1e55ba19.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: v85

**Smartphone (please complete the following information):**

- Device: Nokia 6.1
- OS, version: Android 10
- Browser, version: Chrome v85

**Additional context**

**Comment by msarit** [comment] 2020-09-14 18:16
Hi @Amorpheuz I'm unable to reproduce this bug; are you still experiencing this behavior?

**Comment by Amorpheuz** [comment] 2020-09-14 18:55
Hey @msarit, I haven't noticed similar behavior on Dev.to or Forem.to since opening the bug. I still have no clue as to how one might reproduce it. 

I would like to mention that the notification shown in the example above no-longer appears as "liked" on my end though. (I never reacted to it since the beginning in case it could help solve the bug)

**Comment by Amorpheuz** [comment] 2020-09-16 04:46
Funny stuff. It occurred again on dev.to for me: 😅
![image](https://user-images.githubusercontent.com/22113778/93293424-95349e80-f805-11ea-9654-4e503244a62b.png)
![image](https://user-images.githubusercontent.com/22113778/93293434-9b2a7f80-f805-11ea-85f6-7db36c913289.png)

**Comment by mirie** [comment] 2023-07-14 19:57
Can't reproduce this issue unfortunately so closing for now

**Closed by mirie** 2023-07-14 19:57 UTC
Labels: bug, ready for dev, area: comments & notifications
