### ISSUE TITLE
Comment children of delete comments are not editable or able to be replied to.

### ISSUE THREAD

**Issue by EmNudge** [forem/forem#3971] opened 2019-09-09 05:38 UTC
**Describe the bug**
If someone deletes the comment you replied to, this isn't shown. Your comment is shown as if it is top-level. Any replies you have made further in the comment chain will also display as if they are top level.

The comments you posted will remain, but are not editable. You will get the 404 page ("You have lost your way."). If you try to reply to the comment, it will just stall and show as if it is loading. 

It is deleteable though. That much you can do.

**To Reproduce**

I haven't tested it out, so it is possible that the comments were from some sort of deleted account and not just deleted comments, but I would try making comments in a chain and deleting the top level one.

MP4 showing replying: https://i.gyazo.com/582e6df2c3e340eb9a5c19e5bb693022.mp4
MP4 showing editing: https://i.gyazo.com/28e83b4d1eaa44511adbcbeb16c4ec3a.mp4

- OS: Windows 10
- Browser: Chrome
- Version: 76

**Comment by mstruve** [comment] 2020-11-06 22:26
Since we haven't been able to reproduce this I am going to close it. Let us know if you come across it again, thanks!

**Closed by mstruve** 2020-11-06 22:26 UTC
Labels: type: bug
