### ISSUE TITLE
Cover image on post doesn't show up on Chrome for Android

### ISSUE THREAD

**Issue by faraazahmad** [forem/forem#4765] opened 2019-11-10 10:23 UTC
**Describe the bug**
In the feed and the posts themselves, the cover image is not present, instead, there is a 'white box'. The bug is not present on Desktop.

An empty white box appears in place of the post cover image in the feed and the post page.

**To Reproduce**
1. Scroll through feed to find a post with a cover image
2. Open a post that has a cover image

**Expected behavior**
The assigned cover image should appear instead of the 'white box'

**Screenshots**
![image](https://user-images.githubusercontent.com/19265077/68542293-44783c00-03d1-11ea-9d6a-7d388d2c915a.png)

**Smartphone (please complete the following information):**

- Device: Moto G4 Plus
- OS: Android 7.0
- Browser: Chrome for Android
- Version: 78.0.3904.96

**Additional context**
I have checked on Chrome for Android, Firefox for Android and Firefox Desktop.
The bug is only present in Chrome for Android.

**Comment by mukherjee96** [comment] 2019-11-12 10:35
### Here are my findings
I was investigating the issue and I will post my findings here. I looked at the console logs generated from Chrome Android via Remote Devices in Chrome DevTools.

### I found this 404 error:
`GET https://res.cloudinary.com/practicaldev/image/fetch/s--vZaEoA0L--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/jicx5wil9bcwtc8q4qrt.jpg 404`

That's the URL to a certain cover image. I tried visiting the URL on Chrome Windows and it works just fine.

### But the URL fails in Chrome Android:
***
![Screenshot_2019-11-12-15-28-04-685_com android chrome](https://user-images.githubusercontent.com/40653099/68662289-8f758900-0562-11ea-819f-22087cd44ae2.png)
***

### Deconstructing the URL
This is the original URL of a typical cover image:
`https://res.cloudinary.com/practicaldev/image/fetch/s--vZaEoA0L--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/jicx5wil9bcwtc8q4qrt.jpg`

The actual link to the resource on AWS does work on both Desktop and Android:
`https://thepracticaldev.s3.amazonaws.com/i/jicx5wil9bcwtc8q4qrt.jpg`

Dev.to is using [Cloudinary](https://cloudinary.com/solutions/image_management) for image management. Since the resource can be fetched normally from Dev.to's cloud storage, the problem probably lies with Cloudinary's image delivery system.

### Response headers
Looking at the response headers I found one which indicated that the resource wasn't found:
`x-cld-error: Resource not found`

Here's a full snapshot:
![Annotation 2019-11-12 155628](https://user-images.githubusercontent.com/40653099/68663879-65719600-0565-11ea-8df6-19e0fc1116ce.png)

There's a lot of [discussion](https://support.cloudinary.com/hc/en-us/articles/202520452-I-m-getting-a-404-or-other-40x-errors-for-my-transformed-image-while-other-versions-of-that-image-work) going on about this on Cloudinary Support. But no one appears to have a solution yet.

**Comment by rhymes** [comment] 2019-11-12 10:52
It looks like a concurrency bug to me. The resource is being accessed at the final URL before the image is fully uploaded, thus the 404. What I still don't understand is why it happens only for some user agents, there must be some browser specific code in their caching logic. Maybe it's 404 just for that combination because the first time it was accessed bby that browser + OS, the image wasn't uploaded yet?

**Comment by mukherjee96** [comment] 2019-11-12 11:22
I don't think its a concurrency issue. I experimented by pulling up a random three-week-old Dev.to post from my laptop, texted the link to my Android phone and opened it via Chrome. It still shows an empty box.

What makes this bug even more delicious is that the problem does **not** occur on Brave browser for Android, which is based on Chromium. I checked the Chromium version being used by Brave and it turned out to be the **same** `version 78.0.3904.90` as Chrome for Android on which this issue is occurring.

**Comment by rhymes** [comment] 2019-11-12 11:44
@mukherjee96 I meant a concurrency issue on upload+fetch, not on fetch, but it'd be odd if it were if you can reproduce it again.

>  I checked the Chromium version being used by Brave and it turned out to be the same version 78.0.3904.90 as Chrome for Android on which this issue is occurring.

They have different user agents though, I don't think it's about which browser technology you have, I think it's a bug in Cloudinary which _could_ be related to the specific user agent.

Last test: if you go to https://www.whatsmyua.info/ with your phone, copy the verbatim user agent and try to use that user agent from a different browser overriding the default (from a desktop browser is fine as well), do you still get the 404?

**Comment by mukherjee96** [comment] 2019-11-12 12:33
> Last test: if you go to https://www.whatsmyua.info/ with your phone, copy the verbatim user agent and try to use that user agent from a different browser overriding the default (from a desktop browser is fine as well), do you still get the 404?

@rhymes No, I don't get the 404. These are the exact steps I followed for clarity:
1. Visited https://www.whatsmyua.info/ from Chrome Android (browser with the issue)
2. Copied the UA text
3. Set it in User Agent field in desktop Chrome via Network Conditions in DevTools
4. Visited a Dev.to post with cover image in the **same** tab.

### Reversed the test
By the way, I reversed the test and even then got a 404. Steps followed:
1. Connected my Android phone to my laptop
2. Accessed the DevTools of a Dev.to post tab via Remote Devices
3. Switched to the Network Conditions tab and tested with various preset user agents (Chrome Desktop, Firefox Android Mobile, Chrome Mac) and all of the tests **resulted in 404**.

So, does this indicate that it's not the bug is not UA specific?

**Comment by rhymes** [comment] 2019-11-12 14:16
> So, does this indicate that it's not the bug is not UA specific?

It looks so, I'm honestly lost for words, but maybe it has to do with your own specific combination for device and browser?

**Comment by MohamedElidrissi** [comment] 2019-11-14 22:12
+1, was about to submit this, its been bugging me for a few days thought it was on my end

**Comment by cmgorton** [comment] 2021-03-30 15:54
@faraazahmad @MohamedElidrissi has this still been an issue for you. We have had a lot of changes with mobile lately and want to make sure this is still a bug. I am going to close this issue but if you are still experiencing it please let me know and I will reopen it and see if we can prioritize it. Thanks!

**Closed by cmgorton** 2021-03-30 15:54 UTC
Labels: bug, mobile, ready for dev

**Comment by MohamedElidrissi** [comment] 2021-03-30 18:27
@cmgorton Just checked now, everything seems fine.

**Comment by cmgorton** [comment] 2021-03-30 19:02
Thanks for the confirmation @MohamedElidrissi
