### ISSUE TITLE
Date appears wrong on posts.

### ISSUE THREAD

**Issue by ScottYates** [forem/forem#10586] opened 2020-10-05 01:28 UTC
I just made a comment on a post, and noticed that the displayed date was Oct 5, even though it was Oct 4 when i posted it, and the tooltip when i hover over that date appears to have the correct date in it.

In this case, i just clicked on the "Add to discussion" box and entered my comment, then pressed save.

**Expected behavior**
I expected the date displayed next to the comment to be correct.

**Screenshots**
Here is a capture of the issue:
https://www.screencast.com/t/ZLT50QsXtM1

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 85.0.4183.121

**Additional context**
Here is the comment in question:
https://dev.to/beernutz/comment/160li

This is the full page:
https://dev.to/maggiecodes_/problem-solving-during-interviews-for-anxious-people-2kpp/comments

**Comment by Link2Twenty** [comment] 2020-10-05 08:07
What time zone are you in? It looks like the post was published at 2am on the 5th using UTC and perhaps `readable_publish_date` is based on that.

**Related code:**

https://github.com/forem/forem/blob/4e591fea1c8e062176fb79b1ed5546fa947fee1f/app/views/comments/_comment_date.erb#L1-L7

https://github.com/forem/forem/blob/10efa25c0a35b69248dbebe6fe828a201607ca45/app/models/comment.rb#L118-L124

**Comment by rhymes** [comment] 2020-10-05 08:09
Hi @ScottYates, thanks for the report, unfortunately this is a known issue. I'm going to close this as a duplicate of https://github.com/forem/forem/issues/7561

**Comment by ScottYates** [comment] 2020-10-05 08:10
I should have put that in the report, sorry.  I am CST.

**Closed by rhymes** 2020-10-05 08:09 UTC

**Comment by ScottYates** [comment] 2020-10-05 08:11
I can copy it over there.  I did not see that issue during a cursory search.

Thank you.
