### ISSUE TITLE
Improve Following tags

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [forem/forem#12037] opened 2020-12-25 14:01 UTC
The [following tags](https://dev.to/dashboard/following) page needs a redesign to make it more user friendly.

As a user, I find it frustrating to be setting a value and saving one at a time. And it refreshes the entire page too which is quite bad.
![Screen Shot 2020-12-25 at 7 29 03 PM](https://user-images.githubusercontent.com/1699753/103136563-7a68a480-46e7-11eb-9a24-f38b529c8ad9.png)

**Describe the solution you'd like**
I would like the page to be a "list" of tags having the tag and the weight on each line and a single save button at the top.

**Describe alternatives you've considered**
If the component updates without refreshing the entire page, atleast I can type in multiple values and then save one by one (which isn't very elegant but it's atleast less frustrating).

**Comment by rhymes** [comment] 2020-12-26 18:18
Hi @SaifurRahmanMohsin thanks for opening this and voicing the issue. I'm going to close this only because I believe it's a duplicate of https://github.com/forem/forem/issues/1346 which has an opened PR that should close the issue https://github.com/forem/forem/pull/11454 - let me know if that doesn't cover your initial report.

Please subscribe to the other issue to be notified upon closing.

Thanks again for the report!

**Closed by rhymes** 2020-12-26 18:18 UTC
Labels: area: design, area: settings, tech: html/css, type: bug
