### ISSUE TITLE
Enable "Unflag user" on mod panel

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17754] opened 2022-05-24 01:36 UTC
# Background

Currently when flagging a user using the `flag user` button from the mod panel, it doesn't change into `unflag user` to reverse the action, like other buttons on the mod panel. We would like to add this functionality to it so mod panel is more functional.

![Image](https://user-images.githubusercontent.com/11730007/169930367-fe72b7f1-3715-4bc2-b314-eec6019e8531.png)

# Definition of done
Implement necessary code change for the expected behavior to happen.

# To do
1. Button text should reflect the status of the user, whether being flagged or not.
2. The unflag button should remove the user flag from the user.

# Expected behavior

- When the author of a post is not flagged, the `Flag user` button remains unchanged; 
- When the author of a post is flagged, the `Flag user` button should change into `Unflag user`, with the button fully functioning to unflag the user

# Additional context
The unflag functions we found working are:
1. From the user profile `/{user_name}`
2. From the abuse report in `/admin/moderation/reports?state=abuse-reports`

![image](https://user-images.githubusercontent.com/11730007/169932147-f8c001f0-5a25-4832-bec9-5235bdebe999.png) ![image](https://user-images.githubusercontent.com/11730007/169932092-440b8c84-d409-4f16-9259-032e2175c30c.png)

**Comment by joaoGabriel55** [comment] 2022-05-31 19:20
I can do this task @amywtlin!

**Comment by jeremyf** [comment] 2022-06-02 03:32
@joaoGabriel55 I've assigned this to you and me; that way we both don't lose track of this work.

This is on a nice-to-have portion of a project that's in active work.  There's a possibility that this work and the other project work may collide, so brace yourself for handling merge conflicts.

**Comment by msarit** [comment] 2022-06-24 18:47
I am taking over this task, as communicated [here](https://github.com/forem/forem/pull/17817#issuecomment-1165835575) and [here](https://forem-team.slack.com/archives/C03CHBBMTJP/p1656096362424629).

**Comment by msarit** [comment] 2022-06-27 23:06
@amywtlin @michael-tharrington

I would like us to discuss this functionality a bit more.

Right now, admins have the ability to unflag a user. @michael-tharrington I am assuming that you want the Moderator Role to have this ability also? If they do, they will not have it from the `/admin` space, only from the Actions Panel (and the user's profile) correct?

Trusted users can flag but cannot unflag, of course.

So when we say we want to toggle Flag User and Unflag User, this means that the Unflag User should only be available to Admins and Moderators. Meaning, after a Trusted User flags an author, the Unflag button must be hidden from them and only showed to admins and moderators.

This is complex behavior. How high on our priority list is this [Nice-To-Have](https://github.com/forem/forem/issues/17754) from the Moderator Role [project](https://github.com/orgs/forem/projects/58/views/2)? It would be more straightforward for me to implement the Flag User action, and leave the Unflagging in the `/admin` space and the author's profile.

Thanks for answering.

**Comment by amywtlin** [comment] 2022-06-28 01:42
@msarit This issue is about making the reverse action of flagging available on the mod/action panel in general - not specifically for the mod role. Meaning that this issue doesn't really grant/take away a right; simply making an easier access to performing an action that a role is already authorized to. 

> Trusted users can flag but cannot unflag, of course.

Why can't trusted users unflag though? My assumption was that if you have the right to flag, you also should have the right to unflag; now I am not sure. @michael-tharrington can you tell us your expectation here?

**Comment by msarit** [comment] 2022-06-28 12:18
@amywtlin When Trusted users flag, the flag needs to be confirmed by an admin before it takes effect - from my understanding. What I need to check is if an unflag from a trusted user removes the “confirm this flag” notification from the admin portal.

**Comment by michael-tharrington** [comment] 2022-06-28 13:40
> When Trusted users flag, the flag needs to be confirmed by an admin before it takes effect - from my understanding

This is correct. For the flag to take effect, an admin must confirm it.

My expectation isn't really that admin and moderators need to be able to unflag users on the mod panel, but rather just that admin need a way to remove the flag on flagged users in general. Currently, there is no way.

In the additional context section:

> The unflag functions we found working are:
>
> 1. From the user profile /{user_name}
> 2. From the abuse report in /admin/moderation/reports?state=abuse-reports

On #1, this is technically correct in specific circumstances, but generally doesn't work. As an admin, I can only remove the flag from the user profile if I was the one to add it. Hit me up on Slack if you'd like to see a video of this in action.

On #2, this is technically correct, but almost impossible in practice because as an admin I can only look back at the last 10 confirmed Flag Reactions (including 🧐 on posts and comments which frequently occur) to undo them. So, 99% of the time, I cannot use this to remove a flag. It would only really work if I accidentally flagged a user and realized right then in the moment. I don't think that increasing the number of things we can look back at it is really the solution either because there's so much uncertainty — when was the user flagged? are they indeed flagged (since we have no easy way to see if they were)

Ideally, I'd like us to have a way for admin to both _easily_ see that is user is flagged from their `/admin/member_manager/users/###` page (i.e. not have to filter to `?tab=flags` and browse through all the flags to see if they were flagged) and easily remove the flag from the user. I'd like it to present itself similar to how `suspend`, `comment suspend`, and `warned` present themselves because I see it as being most similar to those actions.

I don't think that a moderator needs to have the visibility into who is flagged/unflagged. They should be able to remove the flagged action if they took the action, but not remove it if anyone else took the action. This would be the same as how they are able to flag post and comments OR reverse those actions.

I'd be happy to walk y'all through this and talk about it if you wanna meet up!

**Closed** 2022-07-27 14:47 UTC
Labels: area: moderation, changelog: rollup
