### ISSUE TITLE
Add a 'Back To Top' button

### ISSUE THREAD

**Issue by msarit** [forem/forem#2618] opened 2019-04-29 18:02 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes, the posts members create get very long. It then becomes a hassle scrolling back up to the control bar which has the 'Markdown' and 'Save Post' buttons

**Describe the solution you'd like**
I think a 'Back To Top' button that appears after a certain scroll-down distance would be very appreciated

**Describe alternatives you've considered**
Maybe make the control bar 'sticky' so that it is always in view regardless of how long the post content is?

**Additional context**
None

**Comment by msarit** [comment] 2019-04-29 18:03
Good for `good-first-issue` in my opinion 😄

**Comment by jessleenyc** [comment] 2019-04-30 19:00
Thanks for the request. Not sure if you know about the v2 of the editor (you can toggle it your /settings/misc) but it has a sticky buttons for preview/save/post. Regardless, we still think this issue makes sense for navigating to the top for other things. 

For anyone interested in taking this, please let us know what you're thinking design-wise so we can get on the same page before implementation.

**Comment by esquith** [comment] 2019-05-02 15:38
Would be interested in taking this. I was thinking just adding it in another line below the "code of conduct - report abuse" text @jessleenyc

**Comment by msarit** [comment] 2019-05-07 12:52
@jessleenyc Ahh I didn't know about v2! Let me toggle it now 😄

**Comment by Danielshow** [comment] 2019-06-09 20:41
Has this been implemented @msarit and @esquith

**Comment by jessleenyc** [comment] 2019-08-07 23:52
@Danielshow hasn't been implemented!

**Comment by aorelhas** [comment] 2020-06-30 16:50
Is this issue solved?

**Comment by rhymes** [comment] 2020-07-01 09:14
@aorelhas no, the issue is still open :)

**Comment by kfatmakausar** [comment] 2020-07-26 23:06
I'd like to work on this issue

**Comment by qojrag-muCroj-4demru** [comment] 2020-07-27 00:17
![image](https://user-images.githubusercontent.com/68495777/88493034-f914b680-cf7c-11ea-8082-64d7559651a6.jpeg)

**Comment by rhymes** [comment] 2020-07-27 08:49
@kfatmakausar thank you! I've assigned you the issue

**Comment by kfatmakausar** [comment] 2020-07-28 15:19
I noticed that the control bar is implemented as 'sticky', so no matter how far the user scrolls down, the control bar still remains on the left side of the page. So would a "'Back to Top' button still be needed? 
Also, does anyone know which file implements the single view of an article?
Also, I was suggesting a 'Back to Top' for the home page?

**Comment by ludwiczakpawel** [comment] 2020-07-29 09:15
I think there are several issues mixed up in this one :D

1. I believe the original issue created by @msarit was to add "Back to top" button on `/new` view (which is post editor). This is no longer needed because we have redesigned that view since then and now the _everything_ is sticky (no need to scroll).
2. @esquith has suggested adding "back to top" button on the Article view itself - but that should be reported as separate issue. But I'd love to have more info/details to understand why **not** having this button is an issue - we literally have almost everything on article view sticky :)
3. @kfatmakausar has suggested adding "back to top" button on the home page - which also seems like a separate issue that could be reported - so lets have a discussion there about how it should be implemented and how it should behave and look like. 

Therefor, because of what I mentioned in point 1., I think this issue can be closed.

**Comment by Link2Twenty** [comment] 2020-10-08 15:46
Back to top can be achieved on any screen by pressing the home button.

There is an issue asking for scroll to top on articles here #1952

**Comment by ludwiczakpawel** [comment] 2020-10-08 18:27
@Link2Twenty what's the "home button"? :)

**Comment by Link2Twenty** [comment] 2020-10-08 18:46
@ludwiczakpawel on your keyboard. Actually on a Mac it's fn Left

**Comment by cmgorton** [comment] 2020-11-24 15:26
We seem to have a couple duplicate issues regarding this feature. Since #1952 is still open and this one looks like it should be closed let's move any more conversation around this feature to that issue. I am going to close this one.

**Closed by cmgorton** 2020-11-24 15:26 UTC
Labels: difficulty: easy, ready for dev, type: feature request
