### ISSUE TITLE
Showing duplicate header & footer while trying to access authenticated URLs before login

### ISSUE THREAD

**Issue by nisusam** [forem/forem#11205] opened 2020-10-31 16:06 UTC
**Describe the bug**

- I do not have dev account, I was checking this issue on github https://github.com/forem/forem/issues/10937.
- When I suddenly open https://dev.to/listings/dashboard in new tab, it redirects me to Login screen with heading `Welcome to DEV` with `Continue with Github` & `Continue with Twitter` buttons.
- I can see duplicate header and footer. PFA screenshots for your reference.

**To Reproduce**

1. DO NOT LOGIN to dev account.
2. Go to https://dev.to/listings/dashboard.
3. It will show duplicate header & footer over here.
4. After refresh it will be redirect to https://dev.to/enter & duplicate header and footer will disappear.

**Expected behavior**

It should not show duplicate header or footer in before login screens as well

**Screenshots**

![Screenshot 2020-10-31 at 9 11 51 PM](https://user-images.githubusercontent.com/16205473/97783767-d61f2180-1bbf-11eb-93cb-cd699b8b4c59.png)

![Screenshot 2020-10-31 at 9 13 36 PM](https://user-images.githubusercontent.com/16205473/97783772-de775c80-1bbf-11eb-8464-bafea9cc7e5b.png)

![Screenshot 2020-10-31 at 9 24 26 PM](https://user-images.githubusercontent.com/16205473/97783782-edf6a580-1bbf-11eb-874f-0186766ebbc6.png)

![Screenshot 2020-10-31 at 9 24 51 PM](https://user-images.githubusercontent.com/16205473/97783783-f058ff80-1bbf-11eb-8687-bb4599797fc0.png)

**Desktop (please complete the following information):**

- OS, version: MacOS Catalina Version 10.15.6 (19G2021)
- Browser, version: Google Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Additional context**

I am able to reproduce this issue on my smartphone as well... 
This issue mostly coming from Notification module as we can see in the above screenshot.

**Comment by gladyscodes** [comment] 2020-10-31 17:02
I'm working on the fix, should be up soon cc @rhymes @pkfrank

**Comment by citizen428** [comment] 2020-11-02 04:34
Thanks @gladyscodes! I assigned you this issue so other potential contributors know that it's being worked on already.

**Comment by pkfrank** [comment] 2020-11-17 17:08
Additional replication paths:
- This is impacting _brand new Forems_ upon confirming email for user `#1`
- Another way to reproduce is after a "redirect," IE:
    - Set up campaign banner that links to `/staff/article-abc`
    - Move article from `/staff` (individual) to `/org` (organization)
    - _Do not_ update the link in the campaign banner
    - Click link in campaign banner will "redirect" you from `/staff/article-abc` to `/org-article-abc`
    - That "redirect" seems to cause this issue to fire

**Comment by mstruve** [comment] 2020-11-17 22:04
Hey @gladyscodes, are you still planning on completing this? It has become a little bit higher priority and we would love for you to help us with it but if you don't have the time then we completely understand and will give it to someone on our internal team. Let us know!!! Thanks!

**Comment by gladyscodes** [comment] 2020-11-17 23:58
Hi @mstruve I was already working on it but if I don't have enough time to complete it, due to the urgency please go ahead and assign it to your internal team.

**Comment by mstruve** [comment] 2020-11-18 00:39
@gladyscodes do you have a timeline on when you think you will be done? If you have a PR ready to go we would love to see it. If not, then I think it would be best to turn it over to the internal team. Let me know!!!

**Comment by gladyscodes** [comment] 2020-11-19 03:28
@mstruve Hi, yes it would be better to turn it over to the internal team because I haven't finished, I'm sorry i'm having trouble with my computer memory.

**Comment by rhymes** [comment] 2020-11-19 11:27
Thank you @gladyscodes and good luck with your computer!

**Comment by nickytonline** [comment] 2021-01-08 14:09
I just tested this by opening a private window and navigating to https://dev.to/listings/dashboard. It redirects properly to https://dev.to/enter and there is no duplications of any UI anywhere. I'm going to close this for now. Feel free to reopen if the issue occurs again.

**Closed by nickytonline** 2021-01-08 14:09 UTC
Labels: EOY priority, Forem team, area: design, type: bug

**Comment by nisusam** [comment] 2021-01-12 19:09
@nickytonline Footer is still duplicate on https://dev.to/listings/dashboard.

![Screenshot 2021-01-13 at 12 38 06 AM](https://user-images.githubusercontent.com/16205473/104360807-a08ba280-5537-11eb-9683-5e6e86d46278.png)
