### ISSUE TITLE
Pages don't display correctly because some elements can be dowloaded (403 errors)

### ISSUE THREAD

**Issue by Bktero** [forem/forem#12556] opened 2021-02-03 14:09 UTC
**Describe the bug**

Pages don't display correctly (images for profiles are missing, styles looks weird, etc) because some elements can't be dowloaded. The screenshot below shows that 403 errors are encountered.

**To Reproduce**

Browse to any page (the home page is enough).

**Expected behavior**

The page should display correctly.

**Screenshots**

![dev_to_403](https://user-images.githubusercontent.com/1047370/106757660-eae0da80-6630-11eb-9abe-012666c993cf.png)

**Desktop:**

- OS=Windows 10
- Browser=Chrome 88.0.4324.104, Firefox 85.0 (64 bits)

**Additional context**

The problem started a few days ago. I would say maximum 2 weeks ago.
I am browsing dev.to from my entreprise network, behind a quite aggressive proxy (by zscaler). If I try to access the URL of the ressource directly in Chrome, I have an error message from the proxy.

I understand you will probably not be able to change the proxy's rules.

Missing images are acceptable.

The issue is how author displays next to the title of the articles. Texts mess up and sometimes it is not possible to understand. Example:

![dev_to_sandor](https://user-images.githubusercontent.com/1047370/106758978-77d86380-6632-11eb-84fe-17be19052b23.png)

In particular, the date of publication is often hidden. Example:
![dev_to_tomek](https://user-images.githubusercontent.com/1047370/106759091-9c344000-6632-11eb-8907-2c73802465ac.png)

**Comment by cmgorton** [comment] 2021-04-30 20:34
Hey @Bktero thanks for reporting this. Want to follow up here and see if this is something you have noticed recently. I haven't been able to reproduce the bug yet.

**Comment by Bktero** [comment] 2021-05-17 15:37
Hell @cmgorton 

The problem is no longer reproducible on my computer. I believe the proxy's configuration has been changed and now files from "https://res.cloudinary.com/practicaldev/" are correctly downloaded.

I guess you can reproduce the bug by setting up a custom proxy with rules to block the image provider.

**Comment by nickytonline** [comment] 2021-05-17 23:41
@Bktero since this was a custom proxy issue I'm going to close this for now.

**Closed by nickytonline** 2021-05-17 23:41 UTC
Labels: area: homepage, bug
