### ISSUE TITLE
Dashboard: article links break after username update

### ISSUE THREAD

**Issue by NV404** [forem/forem#13663] opened 2021-05-05 12:39 UTC
**Describe the bug**

When we change our username. links of old article break in dashboard. For example if you change your username from abc to xyz, links of old article change from dev.to/abc/hiii-devs(Working) to dev.to/xyz/hiii-devs(Not Working) in dashboard.

**To Reproduce**

To Reproduce
1. write some articles
2. change your username
3. Now if you go in dashboard and try to open or edit article it will show you an 404 error.

**Expected behavior**
Article link remain same and edit link update after username change.

Can you assign this to me?

**Comment by cmgorton** [comment] 2021-05-05 13:18
Thanks @NV404 . This might be somewhat connected to https://github.com/forem/forem/issues/6610. I will assign it to you. Going to add the bug smash label to this too if you would like to participate in the bug smash you can read more details in [this DEV post.](https://dev.to/devteam/join-us-for-the-first-dev-community-bug-smash-3plm)

**Comment by cmgorton** [comment] 2021-05-05 13:34
@NV404 Looks like this might be a repeat of an older open issue. https://github.com/forem/forem/issues/3234

Since I already assigned you to this one I am going to leave it open and close the older issue but you may want to reference it as you work on it as one of our engineers added more information there. :)

**Comment by aitchiss** [comment] 2021-07-20 09:10
@NV404 As I mentioned on your PR, I've unassigned you from this issue for now as we're not sure if you're still keen to continue working on this. If you would still like to contribute with this issue, please just let us know and we'll assign you again 🙂 

Thanks again for all your efforts so far on this issue!

**Comment by squarebat** [comment] 2021-07-23 06:38
Hey, I was looking to take a stab at this issue but found out that the error doesn't occur any more. The URLs of all articles changes post username update and the new URL works. Furthermore, the article loads correctly with the old URL as well. If someone else can verify this, this issue can be closed.

**Comment by aitchiss** [comment] 2021-07-23 08:52
I just tried reproducing and found the same as you @squarebat 🎉 

I'll go ahead and close this issue as you suggest and if anyone finds that it is still persisting in any way, then please go ahead and reopen the issue!

**Closed by aitchiss** 2021-07-23 08:52 UTC
Labels: area: articles, area: publishing experience, bug, bug smash, ready for dev
