### ISSUE TITLE
"Flag user" button was not shown in moderator panel but shows up on refresh

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#11134] opened 2020-10-28 12:40 UTC
**Describe the bug**

"Flag user" button was not shown in moderator panel but showed up on refresh. This was happening due to css property overflow: hidden;

**To Reproduce**
1. Go to article
2. Open moderator panel
3. "Flag user" button won't be visible
4. Refresh the app and try again it will show up

**Expected behavior**
"Flag user" button should always show up

**Screenshots**
![flag_user](https://user-images.githubusercontent.com/8092120/97436658-59364280-1948-11eb-90a7-b01fca1427b8.gif)

**Desktop:**
- OS, version: Ubuntu 20.04
- Browser, version: Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)

**Comment by fdoxyz** [comment] 2020-10-28 15:15
Thank you for the report @Rafi993. 

I can't see this happening in any production Forem where I'm a moderator, and I can see your GIF is from a localhost. Maybe this only happens because of the "missing configurations" label at the top? Maybe not a bug that will come up in production but may be something valuable to fix 👍

**Comment by Rafi993** [comment] 2020-10-28 15:17
> Thank you for the report @Rafi993.
> 
> I can't see this happening in any production Forem where I'm a moderator, and I can see your GIF is from a localhost. Maybe this only happens because of the "missing configurations" label at the top? Maybe not a bug that will come up in production but may be something valuable to fix

This issue happens to me in moderator view too. when I open the articles in the list.

**Comment by nickytonline** [comment] 2020-11-02 19:10
I'm not seeing the issue in production either. I tried it from the mod center as well as an individual article page.

![image](https://user-images.githubusercontent.com/833231/97908579-e4cb1d00-1d14-11eb-8f85-1eb7f5992a91.png)

![image](https://user-images.githubusercontent.com/833231/97908613-f0b6df00-1d14-11eb-93dd-629e59fb8acc.png)

Even if I shrink the window a lot or go to mobile view, it's still present.

![image](https://user-images.githubusercontent.com/833231/97908721-117f3480-1d15-11eb-8f3d-d642938a8caa.png)

![image](https://user-images.githubusercontent.com/833231/97908768-2360d780-1d15-11eb-988c-d857992201c3.png)

**Comment by Rafi993** [comment] 2020-11-03 01:40
> Thank you for the report @Rafi993.
> 
> I can't see this happening in any production Forem where I'm a moderator, and I can see your GIF is from a localhost. Maybe this only happens because of the "missing configurations" label at the top? Maybe not a bug that will come up in production but may be something valuable to fix

@fdoxyz you were right this issue does not always it happens only when the "missing configuration" is show at the top. I was able to verify this now by fixing the "missing configuration" now.

**Comment by fdoxyz** [comment] 2021-01-11 16:23
In an attempt to close the loop here: Since the issue does not affect properly configured production or local environments (where the "configuration missing" banner is not visible) I'm closing the issue.

If anyone feels this should be reopened feel free to share your thoughts or open a new issue.

**Closed by fdoxyz** 2021-01-11 16:23 UTC
Labels: area: design, area: moderation, tech: html/css, type: bug
