### ISSUE TITLE
Post Options Not Saving

### ISSUE THREAD

**Issue by jdgamble555** [forem/forem#18622] opened 2022-10-24 00:15 UTC
**Describe the bug**

When creating a post, the Canonical URL does not save.  It seems this is a bigger issue, as all Post Options don't seem to save. You have to publish, and then immediately go back and re-edit your post options.  I believe it might be related to this problem:

https://github.com/forem/forem/issues/18609

**To Reproduce**

1. Create a test post
2.  Type something in `canonical_url`
3.  Click save... 
4.  See that the value was not saved
5.  Edit post
6.  Add it again
7.  It may or may not save... it took me 3 tries

**Expected behavior**
The `canonical_url` would save on the first try.  This could definitely be an issue if people believe their post would have the:

```html
<link rel="canonical" href="..." />
```
in their site.

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Latest Chrome Version, Brave, or Edge (all same error)

**Additional context**

There seems to be some kind of form-field error as well that might be related.  When you type something in that field, it disappears sometimes.  Odd behavior.

J

**Comment by lightalloy** [comment] 2022-11-02 12:25
Hey, @jdgamble555 , thank you for reporting the issue.
Are you still experiencing it? If it's relevant, could you add more details: 
- if you fill in the canonical url in the post options, then click "Done", then go to the "Post options" again (without saving), is it disappearing or remains there?
- do you fill other post options when the bug is happening (e.g. schedule a post), and were they saved?

As for the linked issue https://github.com/forem/forem/issues/18609 , I explored and fixed it: it was related to the `published_at` validation and shouldn't be directly related to this one.

**Comment by michael-tharrington** [comment] 2022-11-02 13:18
Heyo! Just wanted to relay that I tried to reproduce this bug using both versions of our editors but was unable to do so. Here's a loom that shows my experience:

https://www.loom.com/share/5393f2b897f2424aa3239a694190e857

**Comment by lightalloy** [comment] 2022-11-02 14:08
Closing for now because "couldn't reprocude".

**Comment by jdgamble555** [comment] 2022-11-02 21:55
![devto](https://user-images.githubusercontent.com/8333090/199609902-b7993b8f-b563-4e7d-8974-b15f15aa5c9e.gif)

As you can see, this does not work.

J

**Comment by lightalloy** [comment] 2022-11-03 12:18
Thanks for the video, @jdgamble555

**Comment by lightalloy** [comment] 2022-11-03 12:23
The bug occurs when a user pastes in the "canonical url" field using the "right click => paste", so the `onKeyUp` is not triggered, so `onConfigChange` is not executed, and the data is not passed to the backend. 

@jdgamble555 for now, you can paste the value to the canonical url field with "ctrl"+"v" until we fix the bug, this way should work.

**Closed** 2022-11-14 14:16 UTC
Labels: bug
