### ISSUE TITLE
Not able to create post on Dev.to

### ISSUE THREAD

**Issue by SavvyShivam** [forem/forem#18817] opened 2022-12-07 04:09 UTC
**Describe the bug**
I am not able to create posts on dev.to. I have only the option of Title but not the adding tags and post content.

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: chrome,108.0.5359.95 (Official Build) (64-bit)
- 
![dev_post](https://user-images.githubusercontent.com/85667548/206086075-1d327b9e-dec1-4748-a32d-3a315aa9f194.jpg)

**Comment by Ogzhnsfgl** [comment] 2022-12-16 10:53
I have the same issue.

**Comment by johnmaclain789** [comment] 2022-12-17 08:38
Hi,
John here,
Facing same problem. Dev.to does not allow me to create new posts[.](https://thecourtdirect.com/brown-county-municipal-court/) It only allows me to add a title, but not tags or post content.

**Comment by mirie** [comment] 2023-07-28 17:16
Unfortunately we are unable to reproduce with the information reported in this issue, so I'm closing as a can't reproduce.

**Closed by mirie** 2023-07-28 17:16 UTC
