### ISSUE TITLE
Notifications merged with landing page

### ISSUE THREAD

**Issue by laurieontech** [forem/forem#7362] opened 2020-04-17 13:32 UTC
**Describe the bug**

When I have more than a certain number of notifications (in this case 11) when I scroll down on the notifications screen things start going out of whack.

**To Reproduce**

1. Click on notifications
2. Scroll down

**Expected behavior**

The notifications should show only notifications (old or new)

**Screenshots**

<img width="778" alt="Screen Shot 2020-04-17 at 9 29 29 AM" src="https://user-images.githubusercontent.com/15000607/79574531-4e901c00-808e-11ea-86c2-47ba640ac422.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave
- Browser: Google Chrome
- Version: Version 80.0.3987.132 

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment] 2020-04-17 14:02
Hi @laurieontech, thanks for the report. I can't reproduce it which might mean it's a caching issue. What happens if you hard refresh the page?

**Comment by laurieontech** [comment] 2020-04-17 14:17
It works ok then, but the test case isn't the same. I believe this only happens when you have unread notifications.

**Comment by rhymes** [comment] 2020-04-17 17:15
Tried with my account now that I have 4 of them but can't reproduce it:

![notifications](https://user-images.githubusercontent.com/146201/79595794-c3d80d00-80df-11ea-9306-854868c2a643.gif)

:-(

**Comment by laurieontech** [comment] 2020-04-17 17:57
I suppose it may have been temporary weirdness then. I can close and come back to it if I see it again!

**Comment by laurieontech** [comment] 2020-04-24 17:13
Happened again. I had 10 notifications, wondering if that is the threshold.
<img width="618" alt="Screen Shot 2020-04-24 at 1 12 09 PM" src="https://user-images.githubusercontent.com/15000607/80238960-58d18d80-862d-11ea-942b-377478fb7fb7.png">

**Comment by mstruve** [comment] 2020-11-09 00:53
Hey @laurieontech! We have revamped a lot of our notifications page so I decided to recheck this. I went on to DEV, marked 28 of my notifications as unread, and scrolled down the notifications page and the formatting issue seems to have been fixed. I am going to go ahead and close this. Please reopen if you see this continuing to happen! 🤗

**Closed by mstruve** 2020-11-09 00:53 UTC
Labels: area: notifications, type: bug
