### ISSUE TITLE
Isn't this over-complicated?

### ISSUE THREAD

**Issue by rehmatworks** [forem/forem#9883] opened 2020-08-19 22:19 UTC
For over a year, I'm still struggling to deploy the CMS on a test server :) I start deploying it and I give up when a weird issue comes up, and then I try again a month or two later once I get some spare time because I love this software.

Being a web developer, I feel this software is over-complicated. Maybe it's due to Ruby? I am not sure. I only know Python and PHP but I believe that the software can be replicated in Python fairly easily and cleanly. Being a straightforward CMS, why does this software need so many dependencies? Even with the docker solution, the build fails. The dependencies required for the functionality of this CMS should not be so complex to install and configure (at least when I think about the same in Python).

If the deploy process can be simplified that'd be great. I know the software is not ready for public self-hosted servers, but still, I'd love to see where does this software go. If this topic is irrelevant, please pardon me. Thank you so much for developing an amazing place for developers.

**Comment by juniorRubyist** [comment] 2020-08-19 23:24
The project does use some obsoleted versions of dependencies, which could be part of the problem.

**Comment by citizen428** [comment] 2020-08-20 04:13
Hi @rehmatworks and thanks for opening this issue. I think it would be better to have this discussion over at https://forem.dev/. Would you mind posting it there and closing this issue?

**Comment by jdoss** [comment] 2020-08-21 00:54
Hey @rehmatworks I didn't see a post on [forem.dev](https://forem.dev) on this topic, so I wanted to post a quick follow up here to let you know that we hear you. Setting up Forem is pretty tough right now. I share similar thoughts and feelings on the matter too. Part of the reason I joined the Forem Company was to give the the systems side of the house a bunch of tough love to get it into a place where it is an easy and reproducible setup that can be maintained over time. 

We have been making a lot of progress in this area, but none of it is ready to be opened sourced. We hope to have it polished enough so you can setup your own Forem without much frustration. The easy self hosting use case for Forem is a very important goal for us as a team. Personally it is one of my most important goals that I really care about.

Come join us on [forem.dev](https://forem.dev). I have some [posts](https://forem.dev/jdoss) on there that explain more if you are interested.

**Closed by jdoss** 2020-08-21 00:54 UTC
Labels: type: discussion, type: forem creation

**Comment by rehmatworks** [comment] 2020-08-21 03:45
@jdoss Thank you so much for your response. I've created a post on forem.dev site.
