### ISSUE TITLE
GitHub liquid tag: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by jmfayard** [forem/forem#13768] opened 2021-05-14 16:49 UTC
**Describe the bug**

**To Reproduce**

- New article with this content
```
{% github https://github.com/jmfayard/from-java-to-kotlin/pull/1 %}
```
- Save draft
- Fails with `incompatible character encodings: UTF-8 and ASCII-8BIT`

**Expected behavior**

It works

**Screenshots**

<img width="907" alt="Edit_Post_-_DEV_Community_👩💻👨💻" src="https://user-images.githubusercontent.com/459464/118302789-f2900500-b4e4-11eb-85a6-0c83bc34b249.png">

**Desktop (please complete the following information):**

- OS, version: macOS latest
- Browser, version: Firefox latest

**Comment by cmgorton** [comment] 2021-05-17 15:16
This is a weird one. I can reproduce it with the above repo but not with any other similar repository. Going to investigate more. Thanks for opening this issue.

**Comment by Link2Twenty** [comment] 2021-05-17 15:37
So this is caused by the images names in the body, weird right?

The body contains this image

```md
<img width=\"844\" alt=\"from-java-to-kotlin_–_PinGuesser_java_and_Training_on_The_observed_PIN___Codewars_and_From_Java_to_Kotlin_in_20_minutes_and_GitHub_Desktop\" src=\"https://user-images.githubusercontent.com/459464/118158571-42ef6000-b41c-11eb-89df-c32de3ffe8f0.png\">\r\n\r\n<img width=\"673\" alt=\"Kotlin_is_not_configured_in_the_project_and_from-java-to-kotlin_–_PinGuesser_java\" src=\"https://user-images.githubusercontent.com/459464/118158602-4d115e80-b41c-11eb-8cb6-ee85143251ae.png\">
```

Rather than using a hyphen the file uses an en dash `–` and that causes the ruby to not like it (as it's not ascii 8bit).

**Comment by thomasbnt** [comment] 2021-10-05 17:06
Hello ! The bug is still there :c

**Comment by PhilipHow** [comment] 2023-07-14 09:54
Closing as fixed.

**Closed by PhilipHow** 2023-07-14 09:54 UTC
Labels: bug, ready for dev, area: media
