### ISSUE TITLE
Rendering bug in title on https://dev.to/new when uBlock Origin is enabled

### ISSUE THREAD

**Issue by sshine** [forem/forem#12453] opened 2021-01-27 12:32 UTC
**Description:**

The title does not render fully in the area given to it.

Note that the browser is using the default font size.

Resizing the font preserves the broken ratio.

**To Reproduce**

1. Enable uBlock Origin (Chrome)
1. Go to https://dev.to/new
2. Observe title

**Expected behavior**

I should be able to see the post title text area fully.

**Screenshots**

![image](https://user-images.githubusercontent.com/50879/105990637-1567ec00-60a3-11eb-9248-18c75bc246ba.png)

**Desktop:**

- OS, version: MacOS 10.15.7
- Browser, version: Chrome 87.0.4280.141 + uBlock Origin

**Comment by sshine** [comment] 2021-01-27 12:38
I should add that the only thing uBlock Origin blocks on this page is Google Analytics:

​https://www.google-analytics.com/analytics.js

This question can be closed if the page should not render properly unless one submits to tracking.

**Comment by cmgorton** [comment] 2021-01-27 16:27
Hey @sshine . I think this is a duplicate of #10114. I am going to close this issue in favor of continued discussion on that issue. Thanks!

**Closed by cmgorton** 2021-01-27 16:27 UTC
Labels: area: articles, area: publishing experience, bug
