### ISSUE TITLE
Briefly able to 'like' my own comment twice

### ISSUE THREAD

**Issue by 31piy** [forem/forem#4587] opened 2019-10-25 11:14 UTC
**Describe the bug**

When you open your own comment by clicking on the timestamp of it in the thread, it appears as you've loved your own comment.

**To Reproduce**

1. Post a comment.
1. Click on comment's timestamp to see it. The page's URL will be something like https://dev.to/your_username/comment/comment_id.
1. Observe the heart icon. It appears as filled initially, which denotes that you've loved your own comment.
1. Click on the heart icon. The count will increase.
1. Click the icon again, the count will decrease and the heart icon will be hollow. This denotes that you've not loved your own comment.

**Expected behavior**

The comment should not appear as loved (filled heart icon) at first, until you've not already loved it.

**Screenshots**

In the snap below, my own comment appears as loved by me, though I've not done it:

![image](https://user-images.githubusercontent.com/3369637/67566894-8012d500-f746-11e9-992d-47ce9bfec9e0.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojave v10.14.6
- Browser: Brave Version 0.70.121, Chromium: 78.0.3904.70 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

Didn't test it on smartphone.

**Additional context**

When the page is reloaded, the heart appears hollow first, and after some time, it becomes filled. I suspect an XHR call is doing that.

**Comment by Glennmen** [comment] 2019-10-25 11:51
There was an issue about this before but was closed by the OP: #4315

**Comment by jessleenyc** [comment] 2019-10-28 14:44
Hey @31piy, it is intended behavior to have the author auto-like their own comment. However, what your describing with it incrementing despite already being liked sounds like a bug.

**Comment by jessleenyc** [comment] 2019-10-28 14:46
Just updated the title of the issue for more clarity.

**Comment by sibis** [comment] 2019-11-22 00:18
@jessleenyc I have tried replicating it, the functionality works fine to me every time. I would like to debug further and work on this(if it is an issue).

**Comment by 31piy** [comment] 2019-11-22 05:19
@sibis I don't think it is resolved yet. I just tried reproducing this and got the same behavior.

**Steps to reproduce:**
1. Post a comment
2. Click on comment's timestamp to navigate to the comment details page.
3. The comment should appear like you've liked it (which is desired).
4. Try un-liking it.

**Desired behavior:**
When I click on the heart icon, the comment should get unliked.

**Actual behavior:**

The comment appears as liked (with count 1) initially. Unliking it increases the counter to 2 (with filled heart icon). Clicking on the heart icon again illustrates that the comment has been unliked, but the counter remains 1.

Also, try refreshing the page and repeating these steps. Should result in the same behavior.

**Comment by sibis** [comment] 2019-11-22 07:34
@31piy Can you please share your environment where you observe this issue?

**Comment by 31piy** [comment] 2019-11-22 08:51
@sibis -- The environment is the same as I shared in the original comment, except that I used **Firefox 70.0.1 (64-bit)** while reproducing the bug (in my comment above).

**Comment by cmgorton** [comment] 2021-01-22 18:30
This appears to work as intended now. I am going to close this issue but can open it back up if this continues for anyone else. Thanks.

**Closed by cmgorton** 2021-01-22 18:30 UTC
Labels: bug, ready for dev
