### ISSUE TITLE
Images Blocked When Accessing Cover Images via API Fetch

### ISSUE THREAD

**Issue by Pratyush-Nirwan** [forem/forem#21293] opened 2024-09-26 11:49 UTC
**Describe the bug**

Unable to access any image using a `fetch` GET request. Receiving the error: "This asset is blocked. Contact dev.to if this is a mistake."

**To Reproduce**

1. Fetch articles using the API: `https://dev.to/api/articles?username=pratyushnirwan`.
2. In the returned JSON, observe that there are URLs for cover images (e.g., `cover_img`).
3. Attempt to access the cover images via those URLs.
4. The page will display "This asset is blocked. Contact dev.to if this is a mistake."

**Expected behavior**

The cover images should be publicly accessible when fetching the data via the API.

**Desktop:**

- **OS:** Windows 11
- **Browser:** Chrome 129.0.6668.71 (Official Build) (64-bit)

**Comment by garpunkal** [comment] 2024-09-27 14:51
I'm seeing the same issue recently.

**Comment by calumk** [comment] 2024-09-29 19:32
Duplicate of : https://github.com/forem/forem/issues/21292

**Comment by benhalpern** [comment] 2024-10-02 17:14
Hi, sorry for the inconvenience! We had to deploy some overly aggressive edge security to deal with some excessive bot traffic. We have since been able to roll that back and focus on more precise mitigation.

Related: https://github.com/forem/forem/pull/21301

**Closed by benhalpern** 2024-10-02 17:14 UTC
Labels: bug
