### ISSUE TITLE
Dev.to Generates A Service Worker Error in Desktop Safari

### ISSUE THREAD

**Issue by nameplatedigital** [forem/forem#9254] opened 2020-07-10 18:11 UTC
**Describe the bug**

In desktop Safari on MacOS Catalina, the URL https://dev.to will not open. Most of the time Safari just hangs without completing a connection and without offering an explanation. Occasionally, however, Safari will return with the following message:

>_Safari can’t open the page._
>_The error is: “Service Worker context closed” (WebKitInternal:0)_

**To Reproduce**

- In the "Cookie" app (https://cookieapp.com) on MacOS 10.15.5 Catalina, configure the deletion of Safari's history and cache every time Sarfari quits. (I do development testing in Safari so I want that.)
- If it is open, quit Safari.  (its history and cache are deleted)
- Launch Safari.
- Disable all Safari extentions except for 1Password.
- Open https://dev.to (success)
- In the Safari "Develop" menu, manually "Empty Caches"
- Refresh the dev.to window. (Safari hangs. The page will not reload.)
- In the Safari File menu, select "New Window" (a second window opens, empty)
- In the second window, open https://dev.to (success)
- Set the second window aside
- Back in the first window (still hung) stop the attemped reload. (The current iteration of he page remains.)
- Still im the first window, reload again. (now with success)
- Still in the first window, reload yet one more time (and with success again)
- Return to the second window and refresh it for the first time (success)
- In the Safari "Develop" menu, manually "Empty Caches" again.
- In the second window, attempt a refresh. (Safari hangs)
- In the first window, attempt a refresh (success)
- In the second window, stop the hung reload (the existing iteration remains)
- In the second widow, refresh again (success)
- Quit Safari  (history and caches deleted)
- Re-launch Safari.
- Open https://dev.to (success)
- Refresh the window (success)
- In the Safari "Develop" menu, manually "Empty Caches"
- Refresh the window (Safari hangs. The page does not reload.)
- Stop the hung reload (existing iteration remains)
- Refresh the window (success)
- Quit Safari, update bug report.

**Expected behavior**

https://dev.to should always open

**Desktop Configuration:**

- OS: MacOS  10.15.5 ("Catalina")
- Browser:  Safari
- Version:  13.1.1 (15609.2.9.1.2)

**Additional context**

- This Safari is used heavily, over a wide range of URLs, and has no known problem with any other address.
- On the same machine, in Firefox, Edge, and Chrome, https://dev.to will open and behave normally.
- On an iPhone connected to the same LAN, https://dev.to will open and behave normally.

**Troubleshooting Attempted**

- Disabled all extensions in desktop Safari.  No Help.
- Disabled all network filters (Little Snitch). No Help
- Shut down and relaunch MacOS:  No Help.

**Comment by rhymes** [comment] 2020-07-11 08:28
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment] 2020-07-11 08:28
@fdoxyz would https://github.com/thepracticaldev/dev.to/pull/9250 address this as well?

**Comment by nameplatedigital** [comment] 2020-07-11 12:47
@rhymes and @fdoxyz The Safari error I have reported may indeed be related to the issue addressed by PR #9250 because I often manually delete Safari's cache when testing web projects.

**Comment by fdoxyz** [comment] 2020-07-11 13:41
Hey, thank you both for keeping an eye out and confirming this! I actually hadn't realized CI failed on that PR from yesterday, it's now passing.

I hope that whenever we can get that one merged will fix this 👍🏼

**Comment by atsmith813** [comment] 2020-07-14 13:58
This should be good to go with #9250. @fdoxyz is it okay to close this now?

**Comment by nameplatedigital** [comment] 2020-07-15 17:21
@rhymes and @fdoxyz I was hopeful that yesterday's merging of PR #9250 would squash this bug, but, at least for me, it did not. I believe _something_ has changed, however, because I am now able to open and reload https://dev.to with considerably less friction than previously. I have updated the steps to reproduce the problem, showing it's elusive nature.

**Comment by atsmith813** [comment] 2020-07-15 17:27
@nameplatedigital I believe this comment is related:


https://github.com/forem/forem/issues/6902#issuecomment-658402926

**Comment by fdoxyz** [comment] 2020-07-15 18:44
Okay, this is a very weird problem, thank you for helping us figure it out @nameplatedigital ! 

The Service Worker problem was fixed, and like you mentioned it was a problem we no longer have but it still hangs for me too. A bit of a simplified test I ran was this:

1. Open dev.to website (should load normally)
1. Click 'Develop' > 'Empty Caches'
1. Refresh (it should hang indefinitely)
1. Stop the load and refresh again (it loads normally)

I looked up the Safari dev tools and I can't see any Network calls being made. Not even in the service worker devtool window. Here's a video of what I see:

https://share.getcloudapp.com/4gujEGWK
(try to watch the entire video it's less than a minute long)

I'm starting to think this may be a Safari problem, mostly because I ran out of ideas why this is happening 🤔

**Comment by joshpuetz** [comment] 2020-07-17 14:51
Confirmed that this also happens with the latest Safari tech preview (v110) on Catalina/MacOS 10.15

**Comment by maestromac** [comment] 2020-07-17 17:05
I think what's happening is that service work is checking for cached shelltop and shellbottom. It couldn't find it after us emptying the cache and terminated early.

https://github.com/maestromac/dev.to/blob/master/app/views/service_worker/index.js.erb#L45-L49

**Comment by fdoxyz** [comment] 2020-07-17 17:16
I had tested deleting app data on Chrome and this didn't happen, but I just tried it out again with Firefox by deleting all data manually (one by one on the image below) and I ran into the bug there too.

I'll look into this suggestion @maestromac thank you!

![Screen Shot 2020-07-17 at 11 13 43](https://user-images.githubusercontent.com/6045239/87813189-a7528a80-c81e-11ea-94e3-957f815a22db.png)

**Comment by joshpuetz** [comment] 2020-07-17 19:25
I can't get this to happen in Safari with an incognito window by the way! (I found this inadvertently while trying to debugging handing 404 pages in Safari)

**Comment by nickytonline** [comment] 2020-07-17 20:19
I haven't had time to look at this yet and I'm off next week. I'll take a peek when I'm back from vacation if this is still open.

**Comment by mstruve** [comment] 2021-03-02 02:08
Hi there! We recently removed the majority of our Service Worker caching in #12834 With that change, I believe that this should no longer be an issue going forward. I am going to close this, please feel free to reopen if you continue to see this problem.

**Closed by mstruve** 2021-03-02 02:08 UTC
Labels: area: homepage, area: service worker, bug

**Comment by phamthohongduong** [comment] 2023-08-25 17:01
Having the same issue symptom now with https://www.unrealengine.com/en-US on Safari version 16.6 (18615.3.12.11.2)
