### ISSUE TITLE
Blogs on profile page are not showing in chronological order

### ISSUE THREAD

**Issue by technoglot** [forem/forem#13580] opened 2021-04-29 12:47 UTC
**Describe the bug**

The order of the posts on my profile page is not chronological. I've observed this behavior on other profiles as well.

**To Reproduce**

Go to the profile page, scroll down to view posts. Notice how they are not chronologically ordered (pay attention to publish date).

**Expected behavior**

I expect posts to appear in chronological order on my profile, with the oldest post at the bottom of the list, and the most recent post at the top (ignoring pinned posts).

**Screenshots**

![image](https://user-images.githubusercontent.com/36389797/116552468-0c1b3500-a8c7-11eb-815c-2c6795ce1b79.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 PRO
- Browser, version: Chrome, version 90.0.4430.85

**Additional context**

Visit my [profile](https://dev.to/technoglot) or any other user's profile (so long they have posted multiple blog posts) and take a closer look.

**Comment by Link2Twenty** [comment] 2021-04-29 12:56
I believe they're in order of last update as opposed to created.

**Comment by technoglot** [comment] 2021-04-29 13:15
If that's the case, should it not be made clear that that's how they are ordered? It's very confusing as is, in my experience.

**Comment by Link2Twenty** [comment] 2021-04-29 13:30
I'm not sure if the ordering by last updated is the intended behaviour or not but I agree that ordering by created time makes more sense.

**Comment by rhymes** [comment] 2021-04-29 14:18
Hi @technoglot, @Link2Twenty I'm going to look into it and let you know :)

**Comment by technoglot** [comment] 2021-04-29 14:24
Looking forward to your findings @rhymes !

**Comment by rhymes** [comment] 2021-04-29 14:34
Hi @technoglot, I found a bug in our new search backend that populates profiles, I deactivated it while I fix the bug. I'll report back when that's done, in the meantime I see the posts in https://dev.to/technoglot in the correct order :)

**Comment by technoglot** [comment] 2021-04-29 14:36
Awesome! Thanks for your efforts! Looking forward to the fix 😁

**Comment by rhymes** [comment] 2021-04-29 17:52
Hi @technoglot, sorry for the delay! I double checked and your profile looks fine. We deployed a fix :-)

**Comment by rhymes** [comment] 2021-04-29 17:52
Closed by #13577

**Closed by rhymes** 2021-04-29 17:52 UTC
Labels: Forem team, area: search/indexing, bug
