### ISSUE TITLE
User failing validation is prevented from update user to pass validation

### ISSUE THREAD

**Issue by mrloop** [forem/forem#10172] opened 2020-09-02 19:50 UTC
**Describe the bug**

A user record which is invalid can't update user record to make valid, or if they log out they are unable to login again, via github.

I've some how been able to update my account settings with an invalid url for both website and employer. 

**To Reproduce**

I'm not sure how to reproduce initial invalid state where I've entered an invalid url for website and employer. However with a user record in an invalid state the steps to reproduce are 
1. Go to https://dev.to/enter
2. Click 'Continue with github'
3. Follow github auth flow
4. Get error when auth flow takes you back to dev.io

**Expected behavior**

1. Go to https://dev.to/enter
2. Click 'Continue with github'
3. Follow github auth flow
4. Login successfully 

Or maybe not get into the user invalid state to start with.

**Screenshots**

![dev to login-error](https://user-images.githubusercontent.com/12345/92029240-2e22de80-ed5d-11ea-9726-15bbdada0036.png)

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04
- Browser, version: Firefox 80.0, Chrome 85.0 tried in both regular and private browsing mode.

**Additional context**

Seeing this for user https://dev.to/mrloop

**Comment by mrloop** [comment] 2020-09-02 19:57
Maybe related to #10135?

**Comment by msarit** [comment] 2020-09-14 17:59
@mrloop hello! I tried to reproduce this bug, but was unsuccessful. No matter how I try to persist invalid entries for `Website Url` or `Employee Url`, the validation prevents me from saving my updated profile (and my profile retains its former state, without logging me out).

Are you still experiencing this bug?

**Comment by mrloop** [comment] 2020-09-15 10:03
@msarit sorry I've no way of checking, I also couldn't reproduce persisting an invalid entry, I could only reproduce the step after an invalid entry was created. If you can manually create an invalid entry in the db you maybe able to reproduce issue where an invalid entry prevents updating that entry.

**Comment by citizen428** [comment] 2020-09-15 10:18
@mrloop and @msarit We have deployed code that should stop this from happening in the meantime, which is probaby why you can't reproduce this.

**Comment by msarit** [comment] 2020-09-16 15:43
According to @citizen428's message above, this issue has been prevented with a previous code deployment. I'm closing this issue.

cc @mrloop

**Closed by msarit** 2020-09-16 15:43 UTC
Labels: area: auth, area: profile, type: bug
