### ISSUE TITLE
"Write your first Post" needs contrast in NightMode

### ISSUE THREAD

**Issue by maximepiard** [forem/forem#2349] opened 2019-04-09 12:24 UTC
When going to my dashboard in nightmode, I get a page for inciting me to write my first post

![image](https://user-images.githubusercontent.com/13153190/55800002-f6195c80-5ad2-11e9-9cf7-9e775649cb02.png)

The text is hidden as the background is white. I would change the background color to `--theme-container-accent-background` but the image would need to be updated. What about a .png with transparency here ?
![image](https://user-images.githubusercontent.com/13153190/55800089-29f48200-5ad3-11e9-8b98-fbfc00f56e4c.png)

**Comment by lianafelt** [comment] 2019-04-09 16:04
I believe this is sloan with a transparent background. ![sloan-transparent](https://user-images.githubusercontent.com/34452847/55816095-8483e300-5abf-11e9-8a51-bf858c89acbe.png)

**Comment by venarius** [comment] 2019-04-09 19:41
Will work on that if okay

**Comment by maestromac** [comment] 2019-04-09 19:45
Give it whirl @venarius !

**Comment by lornatumuhairwe** [comment] 2019-04-10 00:14
I'm trying to follow this story, so that I understand how things work and get to contribute soon. 

I followed [this](https://dev.to/mercxry/dark-theme-for-devto-14e9) post, and the nightmode gives a different look from what is posted in this image so I figured I'm missing something. How do I activate nightmode this nightmode? 
i saw another post that recommended I do `document.body.className = 'night-theme';` in the console but it didn't work for me either. 

All help is appreciated. Thank you!

**Comment by jessleenyc** [comment] 2019-04-10 00:18
Hey @lornatumuhairwe! You should be able to activate nightmode by visiting: https://dev.to/settings/misc

This post might also have some good info: https://dev.to/devteam/contributors-wanted-night-mode-themes-on-dev-i8n

**Comment by lornatumuhairwe** [comment] 2019-04-10 00:21
@jessleenyc thank you so much!

**Comment by maximepiard** [comment] 2019-04-13 13:57
I think the PR didn't introduce the transparent version of sloan, as I see this now
![image](https://user-images.githubusercontent.com/13153190/56080708-ae614080-5e04-11e9-8e84-28152605fece.png)

I can't re-open the issue, should I make another one then ?

**Comment by venarius** [comment] 2019-04-13 14:08
This could be a caching issue on your side. Did you try a hard refresh? Shift + F5

**Comment by maximepiard** [comment] 2019-04-16 09:46
> Just checked and it seems like the old sloan is still getting delivered by the CDN

Yes it seems this is the problem :confused:

**Comment by NikoLewis** [comment] 2019-06-14 19:02
This seems to be working fine for me now.  
<img width="752" alt="Screen Shot 2019-06-14 at 3 00 25 PM" src="https://user-images.githubusercontent.com/20360382/59531994-77b3af00-8eb5-11e9-9804-bb6266ff236b.png">

**Comment by maestromac** [comment] 2019-06-17 16:42
Hello @venarius & @maximelafarie , are you able to see transparent sloan now?

**Comment by maximelafarie** [comment] 2019-06-18 13:23
> Hello @venarius & @maximelafarie , are you able to see transparent sloan now?

I guess you wanted to mention @maximepiard instead of me! 😉

**Comment by NikoLewis** [comment] 2019-06-21 16:10
@maestromac Nope, he's still not transparent on the live site. To reproduce the issue I had to log into an account that has never made a post. 

I believe the issue is the CDN is serving up an old non-transparent sloan to the web dev.to but our local dev.to project accesses the proper transparent sloan from assets.

**Comment by jessleenyc** [comment] 2019-08-07 20:39
Just a note that I cleared cache via fastly on dev.to/dashboard but the issue is still there.

**Comment by Fmressel** [comment] 2020-09-05 01:39
@maximepiard Just checked and it looks like this issue has been resolved. The transparent version of the sloan is being used!
<img width="1009" alt="Screenshot of Dev's Dashboard" src="https://user-images.githubusercontent.com/3860405/92294119-d069d000-eedd-11ea-99a2-31f22c8bf7b6.png">

**Comment by rhymes** [comment] 2020-09-05 15:13
Thanks for checking @Fmressel 

I'm going to close it @maximepiard, please let me know if I should otherwise reopen it

**Closed by rhymes** 2020-09-05 15:13 UTC
Labels: area: themes, hacktoberfest, ready for dev, type: bug
