### ISSUE TITLE
Can't load the cover images

### ISSUE THREAD

**Issue by Theyashsawarkar** [forem/forem#21297] opened 2024-09-28 20:56 UTC
the bug is i can't see the cover images using the url provided by the dev api . it shows 502 bad get way .

to reproduce : 
 1. fetch the data using the dev api 
 2. try to access the cover images using their urls

example : 

url : https://dev.to/api/articles?username=theyashsawarkar

try to see it's cover image using it's url

**Comment by calumk** [comment] 2024-09-29 19:33
Duplicate of : https://github.com/forem/forem/issues/21292

**Comment by benhalpern** [comment] 2024-10-02 17:14
Hi, sorry for the inconvenience! We had to deploy some overly aggressive edge security to deal with some excessive bot traffic. We have since been able to roll that back and focus on more precise mitigation.

Related: https://github.com/forem/forem/pull/21301

**Closed by benhalpern** 2024-10-02 17:14 UTC
Labels: bug
