### ISSUE TITLE
Comments do not render the correct date

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#11383] opened 2020-11-12 00:35 UTC
**Describe the bug**

While viewing a comment on a post on a Forem instance, I noticed that the comment editor box's "notion" of date was _different_ than my local date (it was one day ahead):

<img width="723" alt="Screen_Shot_2020-11-11_at_4_06_34_PM" src="https://user-images.githubusercontent.com/6921610/98879950-82240080-243b-11eb-89b1-d0ee4eff44a7.png">

I took a screenshot of my local system clock immediately after I noticed this:
<img width="297" alt="Screen_Shot_2020-11-10_at_8_19_41_PM" src="https://user-images.githubusercontent.com/6921610/98879970-8b14d200-243b-11eb-922f-3b991a5eb41a.png">

After I posted the comment, the comment's date still rendered incorrectly/one day ahead:
<img width="1532" alt="Screen_Shot_2020-11-10_at_8_19_35_PM" src="https://user-images.githubusercontent.com/6921610/98879930-79cbc580-243b-11eb-8418-9607a0483495.png">

**To Reproduce**

Not sure the _best_ way to reproduce this aside from writing a comment and checking what date/time the app "interprets" it as, but what I _can_ tell you is that it was 8:19pm _my local time_ when I was writing this comment.

**Expected behavior**

I expect the date of the comment to match the date that I wrote it :)

**Screenshots**

See the description for screenshots 😉

**Comment by mstruve** [comment] 2020-11-12 00:41
This bug has occurred in a few places, we will want to make use of the `local_date` helper such as is done in this PR, https://github.com/forem/forem/pull/11028 to fix it.

**Comment by rhymes** [comment] 2020-11-12 07:41
Hi @vaidehijoshi, I'm closing this a duplicate of https://github.com/forem/forem/issues/7561 - unfortunately it's a known bug (some possible solutions are also debate in the discussion) 😊

**Closed by rhymes** 2020-11-12 07:41 UTC
Labels: type: bug
