### ISSUE TITLE
Save (bookmark) does not create proper notification

### ISSUE THREAD

**Issue by maestromac** [forem/forem#19356] opened 2023-04-19 17:50 UTC
**Describe the bug**

When an article is saved/bookmarked by a user, the author will not receive a "bookmark" notification. Instead, they will receive a previous "like" notification.

**To Reproduce**
1. reader clicks save on an article.
2. author receives a notification.
3. author will not realize it's not supposed to be a "like" notification, but supposed to be a "save".

**Expected behavior**

Author should receive a "save" notification.

**Screenshots**
n/a

**Additional context**

**Comment by mirie** [comment] 2023-04-20 14:49
@maestromac should this be on the Product board instead of Platforms?

**Comment by maestromac** [comment] 2023-05-01 14:13
yes I can move it over

**Comment by filleduchaos** [comment] 2023-05-04 19:55
I've investigated this and the root problem is that we don't actually have a design (or even clear intent) for notifying authors when their articles are bookmarked.

However, since we internally model bookmarks as reactions, bookmarking an article unintentionally triggers the worker that sends notifications for reactions to the author - this then shows up as a `[User] reacted to [article]` notification because we don't have any other copy for that.

<details>
<summary>Technical details under the cut</summary>
There's a single service object for creating "reaction" notifications - `Notifications::Reactions::Send` - and it currently builds a notification by querying all the `public_category` reactions an article or comment has received and serializing them in the `Notification` object. The `notifications/aggregated_reactions` view then renders a summary of the reactions (e.g. "Jane and 50 others reacted to your article", with the icons of their reactions). Since a bookmark isn't a `public_category` reaction, this query is just yielding whatever reactions already exist on the reactable as data for the notification, resurfacing whatever the last reaction was as a "new" notification.

This also means that reproducing this bug is a bit complicated: you first need to find an article or comment that already has reactions (since if the query doesn't find any `public_category` reactions, no notification will be created). Bookmarking it will then cause a reaction notification to be sent.
</details> 

For now I'm pushing a fix to stop bookmarks from triggering a notification at all. I'm leaving this issue open until we reach a consensus on whether we want to notify authors about bookmarks and, if so, what that notification should look like. cc @pkfrank

**Comment by PhilipHow** [comment] 2023-05-19 16:07
@filleduchaos Moved the spec of the proper notification to https://github.com/forem/forem/issues/19510 - happy for you to close this with the merging of the fix for the existing issue.

**Closed** 2023-05-30 23:12 UTC
Labels: bug
