### ISSUE TITLE
Prevent users from losing their unfinished comments when interacting with an article

### ISSUE THREAD

**Issue by danielw93** [forem/forem#10533] opened 2020-10-02 14:05 UTC
**Is your feature request related to a problem? Please describe.**
Writing a long, thought out comment on a post is frustrating at times, because it is really easy to lose your work if you leave the current page without realizing it. 
I often find myself re-reading parts of the article I'm commenting on and will often try to see a bigger version of an image or absentmindedly click a link in the article which will both cause me to leave the current page and lose my comment.

**Describe the solution you'd like**
My favorite solution would be to save comments to local storage as you write them and offer to restore any unfinished work when you return to the article you started writing the comment on.
Drafts are cleared from local storage when they have been posted.

**Describe alternatives you've considered**
An easier solution would be to open any link in a post with `target="_blank" rel="noopener noreferrer"` to open them in a new tab.

The least ideal option (imho) would be to show a warning modal when you are about to leave the page and have unsaved work.

**Comment by cmgorton** [comment] 2021-03-01 20:06
Looks like this is a duplicate of #10533 . Going to close this issue in favor of that one. Thanks!

**Closed by cmgorton** 2021-03-01 20:06 UTC
Labels: area: comments, potential RFC, type: discussion

**Comment by danielw93** [comment] 2021-03-02 11:17
> Looks like this is a duplicate of #10533 . Going to close this issue in favor of that one. Thanks!

Hey I think you linked the wrong issue. #10533 is this one :D

**Comment by cmgorton** [comment] 2021-03-02 14:47
You are right! Going to go search again for the correct one. Sorry about that😅

**Comment by cmgorton** [comment] 2021-03-02 15:03
Related: issue #9121
