### ISSUE TITLE
Embedded GitHub Gists change their order in an unpredictable way

### ISSUE THREAD

**Issue by luvejo** [forem/forem#14428] opened 2021-08-06 01:59 UTC
## Problem

Sometimes, when I open one of my [tutorials](https://dev.to/luvejo/how-to-build-a-carousel-from-scratch-using-vue-js-4ki0), I find the embedded [gists](https://gist.github.com/luvejo/0936b7c33a07592d1706818e89abda04) have changed their order. For example, if I specify `snippet-1.js`, `snippet-5.js` gets rendered instead, and so on. They change their order in an unpredictable way.

Needless to say what this means for readers. Specially in a long tutorial.

## Steps to reproduce

It happens sometimes, even if I open the post in incognito mode and no browser extensions. I just can't tell when.

**Desktop:**

- Browser: Google Chrome 92.0.4515.131
- Browser: Firefox 90.0.2 (64 bit)
- OS: Ubuntu 21.04

**Smartphone:**

- OS: Android
- Browser: Google Chrome 92.0.4515.131

By the way, I haven't found another way to show sample code with line numbers. I tried to upload screenshots of my snippets, but tall images are scaled because of their `max-height` rule. That's why I opened this [feature request](https://forem.dev/luvejo/code-blocks-with-line-numbers-3ae0).

**Comment by rhymes** [comment] 2021-08-06 08:33
Ah! This reminded me of something, so I went digging. Apparently https://github.com/forem/forem/issues/1679 didn't fix it as we thought it would, or it regressed in some way. 

:-/

**Comment by tuang3142** [comment] 2021-08-08 08:23
Hi @rhymes. I'd love to take a look at this!

**Comment by vishaldeepak** [comment] 2021-08-29 15:03
someone trying to recreate the issue I have noticed that, simply refreshing the page does not cause the problem. Here how I got it reproduced
- Goto This [Turorial Page](https://dev.to/luvejo/how-to-build-a-carousel-from-scratch-using-vue-js-4ki0)
- On the right hit the author
- In the author's page simply click on the same article found in the first page
- Gists should now be mixed up.

Can I be assigned this, would take a shot

**Comment by nickytonline** [comment] 2021-08-29 15:38
Assigning this to you @vishaldeepak.

**Comment by vishaldeepak** [comment] 2021-08-30 15:30
@rhymes 
The problem seems to be happening because of [this code ](https://github.com/forem/forem/blob/3b67810b9dd4768a69020b16e4bf9042fecfbb9f/app/javascript/utilities/gist.js#L33)

```
  for (const gistTag of gistTags) {
    postscribe(gistTag, gistTag.firstElementChild.outerHTML, {
      beforeWrite(text) {
        return gistTag.childElementCount > 3 ? '' : text;
      },
    });
  } 
```
Looks like the HTML pages already have `script` tag on the page. The (postscibe pacakge)[https://github.com/krux/postscribe#how-to-use-postscribe-to-render-an-ad-after-load] suggests that we create script tags on the fly(not inserted in the dom).

A fix could be store `span` tags instead of `script` in the processed_html attributes of an Article model. Then  in the js dynamically string replace `span` to `script`. This fixed the problem on my local

What do you think?

**Comment by vishaldeepak** [comment] 2022-07-06 08:24
PR was merged, and should have solved the issue .

**Comment by vishaldeepak** [comment] 2022-07-06 09:50
Do you have the steps on how to create this on your local, maybe I can help out, its been some time since Ive worked on this

**Comment by nsbarsukov** [comment] 2022-07-06 12:12
> Do you have the steps on how to create this on your local, maybe I can help out, its been some time since Ive worked on this

I sincerely appreciate your help!

Unfortunately, I don't know how to reproduce it locally (I dont even know how launch forem-app locally).
But you can use [this article](https://dev.to/angular/sliders-are-like-onions-three-gradient-layers-of-a-single-slider-1nia).
It contains a lot of github snippets. And sometimes this snippets are shown in incorrect order (see video above).

**Comment by natepelzel** [comment] 2022-08-08 02:14
Hello!  I'd like to help out with this.  Would that be okay?

**Comment by vishaldeepak** [comment] 2022-08-08 04:24
@natepelzel I have not started work on this, so its ok from me

**Comment by natepelzel** [comment] 2022-08-08 15:48
@vishaldeepak I have WIP PR that I'd like some feedback on.  I was able to fix the issue but I wanted to make sure I went about it in an agreeable way

#18289

**Comment by vishaldeepak** [comment] 2022-08-09 04:30
@natepelzel Hey I think a core member will be able to help you out on this.

**Closed** 2022-08-30 21:11 UTC
Labels: bug, ready for dev, bug smash, area: media
