### ISSUE TITLE
Chat stays the same while navigating between various users

### ISSUE THREAD

**Issue by harshilparmar** [forem/forem#12190] opened 2021-01-09 19:11 UTC
**Describe the bug**
I don't know whether it is a bug or not 😅  but whenever I write a text in chat and change person it's copying that text to another person. 

**To Reproduce**

1. Go to the chat option.
2. Write chat to person A.
3. Navigate to person B without sending a chat to person A.

**Expected behavior**

It should clear text when navigating between users while chatting.

**Screenshots**

![devfirst](https://user-images.githubusercontent.com/45915468/104106299-b5b7c580-52da-11eb-92f5-3cd67180b5a1.PNG)
![devsecond](https://user-images.githubusercontent.com/45915468/104106310-c36d4b00-52da-11eb-8b82-00efc54846b4.PNG)

**Desktop (please complete the following information):**

- OS, version: windows 10
- Browser, version: Mozilla Firefox 84.0.2

**Additional context**

If this is a bug. We can clear current chat text while navigating between users.
(suggestion) we can also persist text as a draft for a particular sender and receiver.

 I would love to contribute to this issue if it's a valid bug 🤗

**Comment by harshilparmar** [comment] 2021-01-12 10:07
Can I take this issue?

**Comment by cmgorton** [comment] 2021-01-19 16:45
I can reproduce this issue. @harshilparmar thanks for volunteering! I will assign it too you but let me first confirm that this is not intended behavior!

@forem/frontend Can any one confirm whether this is a bug or intended behavior?

**Comment by katiedavis** [comment] 2021-01-19 16:47
@cmgorton This does not sound like intended behavior to me 🙃

**Comment by cmgorton** [comment] 2021-01-19 17:18
Haha, thanks @katiedavis.
I would agree but wanted to make sure 😅

@harshilparmar if you would still like to work on this I will assign it too you.

**Comment by harshilparmar** [comment] 2021-01-19 17:51
@calebmer Let me know whether it's intended or not. I would love to help if it's a bug.

**Comment by cmgorton** [comment] 2021-01-19 18:11
I do not believe it is intended @harshilparmar . I will assign this issue to you. Let us know if you need any more details or help here.

**Comment by harshilparmar** [comment] 2021-01-23 10:32
@cmgorton I am facing an issue while setting dev environment.
I just install all dependencies via `yarn`.
We are using a storyboard for the development right?
I ran `yarn run storybook` and it shows me an error.
Correct me If I am wrong !! 
#### OS : windows 10

### Error
![dev](https://user-images.githubusercontent.com/45915468/105575784-1e4f7980-5d94-11eb-8b27-ed8a22707f5e.PNG)

**Comment by rhymes** [comment] 2021-01-24 18:21
Hi @harshilparmar - I think this other issue is unrelated to the one in the title. Given that, I think that's a legit bug and it should have its own separate issue. I think it's due to the fact that the JS script you're referring to only works in a Unix-like environment, it can be fixed probably :) Can you open the issue ticket?

**Comment by harshilparmar** [comment] 2021-01-24 18:42
> 
> 
> Hi @harshilparmar - I think this other issue is unrelated to the one in the title. Given that, I think that's a legit bug and it should have its own separate issue. I think it's due to the fact that the JS script you're referring to only works in a Unix-like environment, it can be fixed probably :) Can you open the issue ticket?

@rhymes Yeah sure 😁

**Comment by harshilparmar** [comment] 2021-02-27 11:04
Can anyone please explain how to set up a dev environment?
I have figured out which piece of code causing this error. Getting trouble to start this repo locally !!

**Comment by citizen428** [comment] 2021-03-01 06:50
@harshilparmar Have you consulted our docs at https://docs.forem.com/, they should answer most of your questions. If not, please let us know what's missing.

**Comment by cmgorton** [comment] 2021-09-09 16:58
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)

**Closed by cmgorton** 2021-09-09 16:58 UTC
Labels: bug, ready for dev, area: connect, tech: frontend
