### ISSUE TITLE
Random notifications shown

### ISSUE THREAD

**Issue by chinchang** [forem/forem#4398] opened 2019-10-13 18:02 UTC
**Describe the bug**

The notification bell shows random numbers often. Once I click it and reach `https://dev.to/notifications`, sometimes there are no notifications, sometimes there are old notifications on top, basically anything random.

**To Reproduce**
1. I suppose it isn't related just to me. Randomly refresh the homepage and bell count should change.

**Expected behavior**

Newest notifications should show on top.

**Screenshots**

![Screenshot 2019-10-13 23 31 44](https://user-images.githubusercontent.com/379918/66719775-a7e26e80-ee11-11e9-87cb-8356937b70a9.png)

I see this right now, but there are surely new notifications above that top notification which I have seen before. Now they are gone!

**Desktop (please complete the following information):**

- OS: Mac OSX 10.14.6
- Browser: Firefox
- Version: 69.0.1

**Comment by jessleenyc** [comment] 2019-10-16 19:17
For anyone interested in tackling this, check the logic on milestone notifications. We've also noticed some inconsistencies there (like a bunch of milestones coming in at once). There might also be inconsistencies in notifications that might update -- i.e. X people followed you.

**Comment by mstruve** [comment] 2020-11-08 16:45
@chinchang thank you so much for reporting this! Since being reported we have updated a lot of our notification code and I have not been able to reproduce this with the new code so I am going to close this issue. If you can still reproduce this please let us know and we will look further into it! Thanks for being a part of the Forem community!

**Closed by mstruve** 2020-11-08 16:45 UTC
Labels: area: notifications, area: search/indexing, type: bug
