### ISSUE TITLE
After a user has been unflagged, the article-score does not update immediately

### ISSUE THREAD

**Issue by rt4914** [forem/forem#19588] opened 2023-06-07 05:48 UTC
**Describe the bug**

When as admin or trusted user marks the user as flagged, the user-score as well as article-score drops. Now if the admin or trusted user marks the same user unflagged, the user-score resets immediately but the article-score gets updated after like 1 or 2 days (not sure about this value but definitely it takes a long time). 

[Supporting Loom Video](https://www.loom.com/share/1e129a9be82b44459ecdc98993a410a9)

[Starting conversation](https://github.com/forem/forem/pull/19558#issuecomment-1573659240)

**Expected behavior**

The article-score should get updated immediately as soon as user is marked as unflagged.

**Comment by jaw6** [comment] 2023-09-21 09:56
I'm unable to replicate this. Or, rather, the article-score-update happens in a background job, rather than _immediately_, but I see it happen quite fast on local development (though I imagine it'll be slower on Uffizzi). I _think_ this is currently "working as intended". 

The relevant background job is [here](https://github.com/forem/forem/blob/1933f0445aecb30c4988daa6dd8fab1f8ffad6bb/app/workers/reactions/update_relevant_scores_worker.rb#L19-L23) and [it's called whenever a reaction is created or destroyed](https://github.com/forem/forem/blob/1933f0445aecb30c4988daa6dd8fab1f8ffad6bb/app/models/reaction.rb#L170-L172).

I'm going to close the issue for now, but please re-open if I've missed something!

**Closed by jaw6** 2023-09-21 09:56 UTC
Labels: bug
