### ISSUE TITLE
The 'more' link on the navigation links menu doesn't work when you return to the home page.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#11913] opened 2020-12-15 10:35 UTC
**Describe the bug**

On a fresh forem page load, the more link (which displays all the navigation links) works fine. However, when you navigate away from the home page and then return home by hitting the Forem logo (top left main svg logo), the more link stops working. 

**To Reproduce**

On desktop (have replicated on pwa yet)

1. Load a forem homepage
2. On the nav menu on the left, hit more, watch the list expand.
3. Click on an article.
4. Return home by clicking on the main logo, top left (not by hitting the back button on the browser)
5. On the nav menu on the left, hit more, note that is doesn't expand.

**Expected behavior**

The nav menu should expand in all cases.

**Comment by rhymes** [comment] 2020-12-15 12:09
Hi @leewynne, thanks for the issue report! I'm going to close this as a duplicate of https://github.com/forem/forem/issues/11897 which also contains a video

**Closed by rhymes** 2020-12-15 12:09 UTC
Labels: area: homepage, type: bug

**Comment by leewynne** [comment] 2020-12-15 14:30
Thanks Rhymes!
