### ISSUE TITLE
Search bar is sometimes disappears from the UI

### ISSUE THREAD

**Issue by fdocr** [forem/forem#16998] opened 2022-03-24 15:48 UTC
**Describe the bug**

When clicking on the top nav search icon a few times the bar hides or gets removed and never reappears.

**To Reproduce**

1. Open dev.to in a mobile browser (not mobile app)
2. Click on the search icon from the top nav
3. repeat previous step a few times

**Expected behavior**

The search bar shouldn't disappear

**Screenshots**

https://user-images.githubusercontent.com/6045239/159955496-5a580b06-7fb8-4318-b967-66f50887b97c.mov

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS, version: `iOS 15.3.1`
- Browser, version: Safari/Chrome (both webkit based)

**Additional context**

I wasn't able to reproduce it on the iOS mobile app but did happen to me on a mobile browser.

**Comment by MrFuku** [comment] 2022-03-27 17:15
I also confirmed the bug under the following conditions.

- iPhone: Safari
- iPhone: Chrome
- macOS(M1): Safari
- macOS(M1): FireFox

However, I could not reproduce it on macOS Chrome.

It seems that chrome on mac os renders the `SearchFormSync` component every time the search button is pressed, but not on other browsers.

It appears that the results of element comparisons vary from browser to browser.
I have observed different results with the following code.
```
// Chrome on macOS:
console.log(element.isEqualNode(mobileSearchContainer));
=> false

// Other Browsers: true
console.log(element.isEqualNode(mobileSearchContainer));
=> true
```
I am not sure how this search form came to its current specifications, so I will look into it some more.

I will report back when I have a better idea of how to fix it. Thank you :)

**Comment by juliannatetreault** [comment] 2022-04-26 12:54
Thank you so much for digging into this bug a bit, @MrFuku, and apologies that we missed your comment on this issue!

Since a fix for this issue has already been implemented by @ubaidisaev, I’m going to go ahead and assign this bug to them. This being said though, while we sincerely appreciate your contribution, @ubaidisaev, in the future, please ensure that the issue is first assigned to you prior to working on a fix and opening a pull request to ensure that all interested folks get a fair opportunity to work on issues! 😊

**Comment by adxy** [comment] 2022-12-28 10:38
@juliannatetreault @aitchiss I would like to work on this.

**Closed** 2023-01-09 08:51 UTC
Labels: bug, area: search/indexing, tech: frontend, tech: javascript
