### ISSUE TITLE
Layout problems on the "Write a Post" page

### ISSUE THREAD

**Issue by mauricioklein** [forem/forem#11619] opened 2020-11-25 16:15 UTC
**Describe the bug**

When writing a new post on the "Write a new post" page, the layout is presenting the following problems:

### 1. The title gets almost completely covered when the tag field is clicked. The only way to restore the layout is refreshing the page

Before:
![Screen Shot 2020-11-25 at 17 03 42](https://user-images.githubusercontent.com/11538662/100252475-30ea3580-2f40-11eb-8a5d-ff456cdcde37.png)

After selecting the tags field:
![Screen Shot 2020-11-25 at 17 01 53](https://user-images.githubusercontent.com/11538662/100252523-419aab80-2f40-11eb-8c40-66b1c02647d9.png)

**To Reproduce**

1. Go to 'Write a new post' page
2. Add a random title
3. Click on the tags box

### 2. The frontmatter menu isn't available on the rich editor

For example, to move a post back to "Draft", I need to go to settings, switch to basic editor and edit the Frontmatter headers manually. Sometimes the editor type switch is also not working on settings, which blocks me to adjust the visibility. This is necessary when the publish post button is clicked by accident and I need to revert the action.

**Desktop (please complete the following information):**

- OS, version: macOS Catalina 10.15.7
- Browser, version: 
  - Chrome 87.0.4280.67
  - Firefox 78.4.1esr

**Comment by krishnadevz** [comment] 2020-11-26 07:40
I just check this issue in Firefox I am not getting that UI issue you can clear cache and other stuff and check again then ping again here or I guess that dark theme is having an issue 
![descripfeaturessss](https://user-images.githubusercontent.com/42638797/100321445-b0cbda80-2fe8-11eb-8612-3f93af4d1a09.gif)

**Comment by cmgorton** [comment] 2021-01-19 16:41
Hey @mauricioklein I tested this with the dark theme on Firefox and Chrome and cannot reproduce this issue. I agree with Krishna. Could you try clearing your cache. I am going to close this issue but let me know if it is still persisting for you and I will open it back up. Thanks!

**Closed by cmgorton** 2021-01-19 16:41 UTC
Labels: area: design, area: publishing experience
