### ISSUE TITLE
Old username still able to be accessed after username updated

### ISSUE THREAD

**Issue by sekti92** [forem/forem#12522] opened 2021-02-02 06:19 UTC
**Describe the bug**

Old username still able to be accessed after the username already updated

**Expected behavior**
This page does not exist

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 

**Additional context**
After username updated, the old username still can be accessed. It supposed to be produce 404 This page does not exist

**Comment by Miguel-Enrique13** [comment] 2021-03-05 22:14
@cmgorton - Could you assign me to this issue

**Comment by citizen428** [comment] 2021-03-08 04:56
@Miguel-Enrique13 Before you start, we should ensure that this is not expected behavior: on `User` we don't only store the current username but also the last 2 (`old_username` and `old_old_username` IIRC), so what is described here may be intentional. cc @forem/product.

**Comment by benhalpern** [comment] 2021-03-23 18:35
Yeah, this is intended behavior. There are SEO reasons, but also just keeping old links available reasons. If I @ mentioned maestromac and you change to mac, this will keep the old mention valid.

I wouldn't say this is _never changing this under any circumstance_, maybe we could be convinced to modify it.

Since this issue was first presented, we have modified some service worker functionality where in the past, the URL did not appear to redirect under all circumstances, leading this functionality to be more confusing. But we have removed that functionality.

I'll close the issue as intended behavior, but if you want to open up a discussion on how this could possibly change, you can pop open a thread on http://forem.dev/, thanks!

**Closed by benhalpern** 2021-03-23 18:35 UTC
Labels: bug
