### ISSUE TITLE
NoMethodError at `/api/listings`: undefined method `delete' for nil:NilClass

### ISSUE THREAD

**Issue by karvounis** [forem/forem#16927] opened 2022-03-19 20:27 UTC
**Describe the bug**

I am trying to create a new listing through the API following [this guide](https://developers.forem.com/api#operation/createListing). I am running a local Docker installation of Forem, that is listening on `http://localhost:3000`. However, when I am trying to send the example API curl request, I get an error `NoMethodError at /api/listings`.

**To Reproduce**

1. Have the `docker-compose` services up and running for Forem.
```
        Name                       Command               State                     Ports                  
----------------------------------------------------------------------------------------------------------
forem_bundle            ./scripts/entrypoint.sh ./ ...   Exit 0                                           
forem_postgresql        docker-entrypoint.sh postgres    Up       0.0.0.0:5432->5432/tcp,:::5432->5432/tcp
forem_postgresql_test   docker-entrypoint.sh postgres    Up       5432/tcp                                
forem_rails             dockerize -wait tcp://db:5 ...   Up       0.0.0.0:3000->3000/tcp,:::3000->3000/tcp
forem_redis             docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp,:::6379->6379/tcp
forem_seed              dockerize -wait tcp://db:5 ...   Exit 0                                           
forem_sidekiq           dockerize -wait tcp://db:5 ...   Up                                               
forem_webpacker         dockerize -wait file:///op ...   Up                                               
forem_yarn              ./scripts/entrypoint.sh ya ...   Exit 0                                           
```

2. Send the following curl request to the API

```
curl  -X POST -H "Content-Type: application/json" -H "api-key: <your_key>" -d '{"listing":{"title":"Title","body_markdown":"Body","category":"cfp","tags":["python"]}}' "http://localhost:3000/api/listings"
```

**Expected behavior**

The expected behavior would be to successfully create a new listing through the API endpoint `api/listings`.

The `API_KEY` I am using is a key I created for the admin Forem user and it has 69 credits. I have successfully managed to create a listing from the browser but not through the API.

**Desktop (please complete the following information):**

- OS, version: Ubuntu 20.04.4 LTS (focal) 
- API, version: DEV API (beta) (0.9.7)

**Additional context**

```
$ curl  -X POST -H "Content-Type: application/json" -H "api-key: ${FOREM_API_KEY}" -d '{"listing":{"title":"Title","body_markdown":"Body","category":"cfp","tags":["python"]}}' "http://localhost:3000/api/listings"

NoMethodError at /api/listings
==============================

undefined method `delete' for nil:NilClass

> To access an interactive console with this error, point your browser to: /__better_errors


app/controllers/concerns/listings_toolkit.rb, line 40
-----------------------------------------------------

   35       expires_at location organization_id action
   36     ].freeze
   37   
   38     # Filter for a set of known safe params
   39     def listing_params
>  40       tags = params["listing"].delete("tags")
   41       if tags.present?
   42         params["listing"]["tag_list"] = tags.join(", ")
   43       end
   44       params.require(:listing).permit(ALLOWED_PARAMS)
   45     end

App backtrace
-------------

 - app/controllers/concerns/listings_toolkit.rb:40:in `listing_params'
 - app/controllers/api/v0/listings_controller.rb:100:in `listing_params'
 - app/controllers/concerns/listings_toolkit.rb:8:in `create'

Full backtrace
--------------

 - app/controllers/concerns/listings_toolkit.rb:40:in `listing_params'
 - app/controllers/api/v0/listings_controller.rb:100:in `listing_params'
 - app/controllers/concerns/listings_toolkit.rb:8:in `create'
 - actionpack (6.1.4.6) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 - actionpack (6.1.4.6) lib/abstract_controller/base.rb:228:in `process_action'
 - ddtrace (0.54.2) lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb:127:in `process_action'
 - actionpack (6.1.4.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
 - actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 - activesupport (6.1.4.6) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 - ahoy_matey (4.0.3) lib/ahoy/controller.rb:45:in `set_ahoy_request_store'
 - activesupport (6.1.4.6) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 - activesupport (6.1.4.6) lib/active_support/callbacks.rb:137:in `run_callbacks'
 - actionpack (6.1.4.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
 - actionpack (6.1.4.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
 - actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 - activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `block in instrument'
 - activesupport (6.1.4.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 - activesupport (6.1.4.6) lib/active_support/notifications.rb:203:in `instrument'
 - actionpack (6.1.4.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 - actionpack (6.1.4.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 - activerecord (6.1.4.6) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 - actionpack (6.1.4.6) lib/abstract_controller/base.rb:165:in `process'
 - actionview (6.1.4.6) lib/action_view/rendering.rb:39:in `process'
 - actionpack (6.1.4.6) lib/action_controller/metal.rb:190:in `dispatch'
 - actionpack (6.1.4.6) lib/action_controller/metal.rb:254:in `dispatch'
 - actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 - actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
 - actionpack (6.1.4.6) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
 - actionpack (6.1.4.6) lib/action_dispatch/routing/mapper.rb:49:in `serve'
 - actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 - actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `each'
 - actionpack (6.1.4.6) lib/action_dispatch/journey/router.rb:32:in `serve'
 - actionpack (6.1.4.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:202:in `call!'
 - omniauth (2.0.4) lib/omniauth/strategy.rb:169:in `call'
 - bullet (7.0.1) lib/bullet/rack.rb:15:in `call'
 - jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
 - jquery-fileupload-rails (0.4.7) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
 - rack-attack (6.6.0) lib/rack/attack.rb:127:in `call'
 - flipper (0.24.0) lib/flipper/middleware/memoizer.rb:77:in `memoized_call'
 - flipper (0.24.0) lib/flipper/middleware/memoizer.rb:42:in `call'
 - rack (2.2.3) lib/rack/deflater.rb:44:in `call'
 - warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
 - warden (1.2.9) lib/warden/manager.rb:34:in `catch'
 - warden (1.2.9) lib/warden/manager.rb:34:in `call'
 - rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
 - rack (2.2.3) lib/rack/etag.rb:27:in `call'
 - rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
 - rack (2.2.3) lib/rack/head.rb:12:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
 - rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
 - rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
 - activerecord (6.1.4.6) lib/active_record/migration.rb:601:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 - activesupport (6.1.4.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 - ddtrace (0.54.2) lib/ddtrace/contrib/rails/middlewares.rb:18:in `call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:87:in `protected_app_call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:82:in `better_errors_call'
 - better_errors (2.9.1) lib/better_errors/middleware.rb:60:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 - web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
 - web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
 - web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
 - web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
 - honeycomb-beeline (2.8.2) lib/honeycomb/integrations/rack.rb:79:in `call_with_hook'
 - honeycomb-beeline (2.8.2) lib/honeycomb/integrations/rails.rb:94:in `call_with_hook'
 - honeycomb-beeline (2.8.2) lib/honeycomb/integrations/rack.rb:52:in `block in call'
 - honeycomb-beeline (2.8.2) lib/honeycomb/client.rb:62:in `start_span'
 - honeycomb-beeline (2.8.2) lib/honeycomb/integrations/rack.rb:36:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 - railties (6.1.4.6) lib/rails/rack/logger.rb:37:in `call_app'
 - railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `block in call'
 - activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
 - activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:37:in `tagged'
 - activesupport (6.1.4.6) lib/active_support/tagged_logging.rb:99:in `tagged'
 - railties (6.1.4.6) lib/rails/rack/logger.rb:26:in `call'
 - ahoy_matey (4.0.3) lib/ahoy/engine.rb:22:in `call_with_quiet_ahoy'
 - sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 - rack-timeout (0.6.0) lib/rack/timeout/core.rb:151:in `block in call'
 - rack-timeout (0.6.0) lib/rack/timeout/support/timeout.rb:19:in `timeout'
 - rack-timeout (0.6.0) lib/rack/timeout/core.rb:150:in `call'
 - request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
 - rack (2.2.3) lib/rack/method_override.rb:24:in `call'
 - rack (2.2.3) lib/rack/runtime.rb:22:in `call'
 - activesupport (6.1.4.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/static.rb:24:in `call'
 - rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
 - actionpack (6.1.4.6) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
 - rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
 - ddtrace (0.54.2) lib/ddtrace/contrib/rack/middlewares.rb:88:in `call'
 - honeybadger (4.11.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
 - honeybadger (4.11.0) lib/honeybadger/agent.rb:426:in `with_rack_env'
 - honeybadger (4.11.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
 - honeybadger (4.11.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
 - honeybadger (4.11.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
 - webpacker (5.4.3) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
 - rack-proxy (0.7.0) lib/rack/proxy.rb:63:in `call'
 - railties (6.1.4.6) lib/rails/engine.rb:539:in `call'
 - puma (5.6.2) lib/puma/configuration.rb:252:in `call'
 - puma (5.6.2) lib/puma/request.rb:77:in `block in handle_request'
 - puma (5.6.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
 - puma (5.6.2) lib/puma/request.rb:76:in `handle_request'
 - puma (5.6.2) lib/puma/server.rb:441:in `process_client'
 - puma (5.6.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

Logs from the `rails` service:

```
rails_1      | Started POST "/api/listings" for 172.23.0.1 at 2022-03-19 20:14:57 +0000
rails_1      |    (0.8ms)  SELECT "flipper_features"."key" AS feature_key, "flipper_gates"."key", "flipper_gates"."value" FROM "flipper_features" LEFT OUTER JOIN "flipper_gates" ON "flipper_features"."key" = "flipper_gates"."feature_key"
rails_1      | Processing by Api::V0::ListingsController#create as JSON
rails_1      |   Parameters: {"listing"=>{"title"=>"Title", "body_markdown"=>"Body", "category"=>"cfp", "action"=>"draft"}, "locale"=>nil}
rails_1      |   ApiSecret Load (0.6ms)  SELECT "api_secrets".* FROM "api_secrets" WHERE "api_secrets"."secret" = $1 LIMIT $2  [["secret", "LG8JJHEuA56FdPZhNBSv8ng6"], ["LIMIT", 1]]
rails_1      |   ↳ app/controllers/api/v0/api_controller.rb:102:in `authenticate_with_api_key'
rails_1      |   User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 11]]
rails_1      |   ↳ app/controllers/api/v0/api_controller.rb:102:in `authenticate_with_api_key'
rails_1      | Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.3ms | Allocations: 4056)
rails_1      | 
rails_1      | 
rails_1      | 
rails_1      | NoMethodError - undefined method `delete' for nil:NilClass:
rails_1      |   app/controllers/concerns/listings_toolkit.rb:40:in `listing_params'
rails_1      |   app/controllers/api/v0/listings_controller.rb:100:in `listing_params'
rails_1      |   app/controllers/concerns/listings_toolkit.rb:8:in `create'
```

**Comment by djuber** [comment] 2022-03-28 15:09
I'm able to reproduce this locally (outside of docker, running the rails app on port 3000)

```
~/src/forem$ curl -X POST -H "Content-Type: application/json" -H "api-key: $API_KEY"  -d '{"listing":{"title":"Title","body_markdown":"Body","category":"cfp"}}'   http://localhost:3000/api/listingsNoMethodError at /api/listings
==============================

undefined method `delete' for nil:NilClass

> To access an interactive console with this error, point your browser to: /__better_errors


app/controllers/concerns/listings_toolkit.rb, line 40
-----------------------------------------------------

   35       expires_at location organization_id action
   36     ].freeze
   37   
   38     # Filter for a set of known safe params
   39     def listing_params
>  40       tags = params["listing"].delete("tags")
   41       if tags.present?
   42         params["listing"]["tag_list"] = tags.join(", ")
   43       end
   44       params.require(:listing).permit(ALLOWED_PARAMS)
   45     end
```

I used nearly the exact curl example from the api docs (I added $API_KEY in place of API_KEY so the shell would expand the header value, and changed the target from https://dev.to/api to http://localhost:3000/api). This looks like it rules out the docker setup (and points to either a bug in forem's api for this use case, or a drift in the api requirements and the documentation). 

Putting a breakpoint in that location (in the listings toolkit helper, just before the tags assignment where the error occurs) shows params has a key "listings", and that "listings" is nil.

```ruby
[10] pry(#<Api::V0::ListingsController>)> params
=> #<ActionController::Parameters {"listing"=>nil, "locale"=>nil, "format"=>"json", "controller"=>"api/v0/listings", "action"=>"create"} permitted: false>
```

 Checking caller indicates the listings controller's listing_params calls the toolkits listing_params:

```
 "/home/djuber/src/forem/app/controllers/concerns/listings_toolkit.rb:40:in `listing_params'",
 "/home/djuber/src/forem/app/controllers/api/v0/listings_controller.rb:100:in `listing_params'",
 "/home/djuber/src/forem/app/controllers/concerns/listings_toolkit.rb:8:in `create'",
```

Checking the [api controller's method](https://github.com/forem/forem/blob/main/app/controllers/api/v0/listings_controller.rb#L92-L101) - it looks like this is related to a renaming (a while back) of the Listings model from the ClassifiedListings model, the code has a comment about an existing public api using "classified_listings" as the top level key for the json body, and assigns from there to listings (which is what the rest of the app uses). I understand the reasoning there - you don't want your internal refactoring/simplification to break a published api endpoint (someone might have written automation on top of it).

I think a reasonable fix for this would be to use a conditional assignment to accept either?

```ruby
        params["listing"] ||= params["classified_listing"]
```

That would set "listing" only if it were blank.

The alternate fix would be to change the api docs to reflect the legacy name, but that feels like it entrenches a requirement based on names that existed several years ago.

**Comment by djuber** [comment] 2022-03-28 15:34
@karvounis, thank you for this bug report, it really made triaging this issue fast and pleasant, since you included all the relevant information (what api request you sent, which instructions you were following, how you were running the software, what error you saw, what you expected to see).

**Closed** 2022-03-28 18:40 UTC
Labels: bug, area: API

**Comment by karvounis** [comment] 2022-03-29 06:35
Hey @djuber thank you for your swift reply and fix! That was impressive!

I am also glad that you found the bug report comprehensive and helpful.

**Comment by karvounis** [comment] 2022-03-29 06:51
I can confirm that I am able to create a listing now through the API. Cheers!
