### ISSUE TITLE
Use CSS files to switch themes

### ISSUE THREAD

**Issue by aligoren** [forem/forem#4759] opened 2019-11-09 09:28 UTC
Hi. I was reading [theming](https://github.com/thepracticaldev/dev.to/blob/master/docs/design/theming.md) documentation. I saw theme switching codes.

In the below code, there are if-else blocks to switch between themes. Each block can insert CSS codes to the dom by JavaScript. 

https://github.com/thepracticaldev/dev.to/blob/f0e367996a5296da03cf05e36bfeff6df7991be5/app/views/layouts/_user_config.html.erb#L5-L135

That's a good feature. But I wonder, what If we have 10+ themes? Will every CSS code be here in a condition block?

Instead of this, why we don't use CSS files? Using CSS files as a separated isn't easy?

I don't know anything about ERB. I'll follow the other codes. But maybe this should be good?

```erb
<% if config_body_class? %>

    this_is_user_theme_css_file_variable = config_body_class + ".css"

    <%= Rails.application.assets[this_is_user_theme_css_file_variable].to_s.html_safe %>
<% end %>
```
What do you think about that?

**Comment by Glennmen** [comment] 2019-11-09 09:41
I think the issue is that DEV does a lot of heavy page caching so that is probably why theme switching is currently being handled client-side with JS.

**Comment by aligoren** [comment] 2019-11-09 10:16
> I think the issue is that DEV does a lot of heavy pages caching so that is probably why theme switching is currently being handled client-side with JS.

Still can client-side theme switching feature. For example;

```javascript
document.addEventListeler('DOMContentLoaded', () => {
    const this_is_user_theme_css_file_variable = config_body_class + ".css";
    selectedTheme.setAttribute('href', this_is_user_theme_css_file_variable)
})
```

I'm not sure about that but would be good :). Besides this, I strongly agree with you. If the DEV does a lot of heavy pages caching, this is a thing what is the DEV has to do.

**Comment by benhalpern** [comment] 2019-11-11 19:45
We don't want to do anything that might add extra latency, but yes I think that is not necessarily a scalable approach. Currently we ship all the themes into the browser and that is kind of silly.

The second thing also adds an extra resource to wait on some of the time.

So @aligoren I think you're on to the right problem, but I think the approach that would fit most smoothly into what we do is to actually move the css itself into the asynchronous request where we currently ask for the theme body class. (`async_info/base_data`).

We fetch this info and then store it in local storage. We then calculate some stuff in `_user_config` but it's all inline and the JS is going to be the same for all users.

I think adding the css itself to `base_data` and then switching the functionality in `_user_config` is the way we get this to where it could scale to as many themes as we'd ever want, without having to store them in the page's HTML itself.

**Comment by aligoren** [comment] 2019-11-12 05:37
> We don't want to do anything that might add extra latency, but yes I think that is not necessarily a scalable approach. Currently, we ship all the themes into the browser and that is kind of silly.

Yes, currently, this is not a problem. Because there are not many themes today.

> The second thing also adds an extra resource to wait on some of the time.

After I open this issue, I remembered this. Each CSS file also means bandwidth, resource.

> So @aligoren I think you're on to the right problem, but I think the approach that would fit most smoothly into what we do is to actually move the CSS itself into the asynchronous request where we currently ask for the theme body class. (`async_info/base_data`).

Hmm, I didn't think like that :)

> We fetch this info and then store it in local storage. We then calculate some stuff in `_user_config` but it's all inline and the JS is going to be the same for all users.

Yes, I checked the **config_body_class**. Is this prevent extra queries?

> I think adding the CSS itself to `base_data` and then switching the functionality in `_user_config` is the way we get this to where it could scale to as many themes as we'd ever want, without having to store them in the page's HTML itself.

I think so too. But there is a fact "carpe diem". So, today we need this approach. But, in the future, we will have to change something. As I know so far the Dev ready for that.

Thank you very much for your detailed answer.

**Comment by cmgorton** [comment] 2021-01-22 18:51
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Closed by cmgorton** 2021-01-22 18:51 UTC
Labels: area: themes
