### ISSUE TITLE
Unexpected error on Glitch previews

### ISSUE THREAD

**Issue by Markel** [forem/forem#3261] opened 2019-06-21 16:44 UTC
**Describe the bug**
Glitch returns the error
> Unknown: Server error. An unexpected error has occurred.

when loading various Glitch iframes (based on the little testing I was able to done)

**To Reproduce**
1. Go to [this article](https://dev.to/glitch/on-glitch-this-week-4fo6) or any article including multiple glitch iframes

2. Done, the error should appear

**Expected behavior**
While the iframe loads correctly if you press _"Try again"_ it should load correctly the first time.

**Screenshots**

![Screenshot_20190621-093851_Chrome~2](https://user-images.githubusercontent.com/45839898/59937921-809e0680-9408-11e9-8fc1-8299f9ca7d31.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device: PocoPhone F1
- OS: Android 9 (Flavour: LineageOS)
- Browser: Google Chrome PWA
- Version: 75

**Additional context**
- I haven't been able to test what happens if you load a single Glitch iframe.
- I haven't investigated the Response Code Glitch provides as I'm in mobile. Knowing it could help.
- It's probably a system to avoid bots to overload the Glitch website.

**Comment by MarkelFe** [comment] 2019-06-22 01:19
Tried on Firefox 67 for Android (not PWA) and it doesn't happen, all iframes load (I guess an extra point for Firefox 😊)

**Comment by Zhao-Andy** [comment] 2019-06-25 14:22
Thanks for the bug report! We'll take a look into it.

**Comment by Zhao-Andy** [comment] 2019-06-25 15:50
Hi @MarkelFe, so I couldn't reproduce this in regular Chrome on macOS. I'll try the PWA on an Android device soon, but in the meantime could you confirm this is still an issue? I'm thinking it might have been an issue on Glitch's end.

**Comment by MarkelFe** [comment] 2019-06-25 18:17
Yes, just rechecked it and it happens again. Meanwhile Firefox works.

I also checked to uninstall the PWA and load the article on normal Android Chrome, and the bug still happens, so this is something related with Chrome for Android, not special to the PWA 👀.

**Comment by joshpuetz** [comment] 2021-01-25 16:07
Test that this doesn't happen on iOS 14. Appears to be Android only right now.

**Comment by Markel** [comment] 2021-01-25 18:06
> Appears to be Android only right now.

Or it could have been a resolved issue since then as the issue is pretty old. However it makes sense that the iOS and Android version respond differently because as far as I know they use different rendering engines (do not quote me on that). Simply, it should be checked that the issue is still present (I've switch to Firefox since so I can't do it)

**Comment by joshpuetz** [comment] 2021-01-28 15:55
Tested this on Android and it doesn't happen anymore, closing!

**Closed by joshpuetz** 2021-01-28 15:55 UTC
Labels: area: for Android, area: publishing experience, bug, ready for dev
