### ISSUE TITLE
[dev.to] Upload button in markdown editor does not react on waterfox classic

### ISSUE THREAD

**Issue by c33s** [forem/forem#11434] opened 2020-11-15 23:08 UTC
**Describe the bug**

upload image button does nothing

**Screenshots**

![image](https://user-images.githubusercontent.com/649209/99199445-71f38480-279f-11eb-872b-53e7262b9848.png)

**Desktop (please complete the following information):**

- OS, version: win
- Browser, version: waterfox **classic** 2020.10

**resulted in blog post**
https://dev.to/c33s/dear-javascript-webdevelopers-please-don-t-break-the-web-20go

**Comment by rhymes** [comment] 2020-11-16 08:54
Although semi officially we support the latest versions of Edge, Firefox, Safari and Chrome only on desktop.

I hadn't heart of Waterfox before today so I installed with `brew` both Waterfox Classic and Current. This is the outcome:

- with Waterfox Classic neither v1 nor v2 editors's buttons work
- with Waterfox Current they both work, buttons included

This makes me think that Classic is built on a version of Firefox that's not recent, though unfortunately the console doesn't display any errors to know what's exactly missing. I suspect there's a whole slew of functionality missing from Classic that's present in Current.

I can't find which versions of Firefox they each track but I suggest upgrading to `Current` if that's something you can do

**Comment by Link2Twenty** [comment] 2020-11-16 09:44
Looks like it's a known issue on their end, or at least there is an issue about it.
https://github.com/MrAlex94/Waterfox/issues/1047

**Comment by c33s** [comment] 2021-01-23 14:26
sad that a simple upload form field which works in all browsers since decades is now rocket science and needs the latest browsers. 

- https://dev.to/c33s/dear-javascript-webdevelopers-please-don-t-break-the-web-20go
- https://jeffhuang.com/designed_to_last/

**Comment by ludwiczakpawel** [comment] 2021-01-25 13:20
As @rhymes mentioned - we do our best to support most of the modern browsers. Our upload button isn't really a rocket science in any way.

TBH I have never heard of Waterfox and I've just tested it for the first time. Even though I can confirm that button doesn't work in Waterfox Classic (it does work in Waterfox Current), I'm very hesitant to blame DEV's code for this - the appearance of that upload button doesn't rely on JavaScript - it's just very basic CSS afaik. It does work in all modern browsers, including many version back.

With that being said, as of today, I don't think it's worth the effort to redo parts of our app in order to make them work in very niche browser. 

I'm closing this issue but will keep the conversation unlocked if there's anything else that needs to be added.

**Closed by ludwiczakpawel** 2021-01-25 13:20 UTC
Labels: area: images, area: publishing experience, bug
