### ISSUE TITLE
dev.to | Automatic loading when scroll down make footer inaccessible

### ISSUE THREAD

**Issue by luisfelipesdn12** [forem/forem#13870] opened 2021-05-27 13:08 UTC
**Describe the bug**

It is not exactly a bug, but it's kinda annoying. I was in the dev.to home page, viewing the posts, and when I scroll to the bottom to see the footer resources, more posts were loaded, over and over again.

**To Reproduce**

1. Go to dev.to
2. Scroll down to the bottom
3. Try to read the footer

**Expected behavior**

Something like GitHub does on the home page, when you scroll down, it just loads more if you want to.

**Screenshots**

![Peek 27-05-2021 10-06](https://user-images.githubusercontent.com/60361387/119831050-429e9c80-bed3-11eb-8b30-315d4a1711ce.gif)

**Comment by Link2Twenty** [comment] 2021-05-27 13:27
Thanks for reporting, this is a duplicate of #9034. Feel free to join the conversation over there.

**Comment by rhymes** [comment] 2021-05-27 15:32
Thanks @Link2Twenty

**Closed by rhymes** 2021-05-27 15:32 UTC
Labels: area: design
