### ISSUE TITLE
Markdown in Rails' topic description won't work

### ISSUE THREAD

**Issue by carrotfarmer** [forem/forem#13170] opened 2021-03-29 15:00 UTC
**Describe the bug**
The markdown which appears in the Rails' topic description does not work, which makes it look odd.
![bug screenshot](https://user-images.githubusercontent.com/66675022/112856288-4083b180-90cd-11eb-90ba-4560536bd9dd.png)

**To Reproduce**
Head over to [The Ruby On Rails topic](https://dev.to/t/rails)

**Comment by cmgorton** [comment] 2021-03-29 19:04
Hey @carrotfarmer ! Can you be more specific? Where is the markdown and where is it not showing up properly? 

Are you referencing the `[dev.to](/)` ?  
I think we could fix this just by making it  more explicit like `[dev.to](https://dev.to/)` instead.

**Comment by carrotfarmer** [comment] 2021-03-30 02:48
Yep I'm referencing to `[dev.to](/)`

**Comment by vishaldeepak** [comment] 2021-08-20 04:01
this looks straightforward, I'd like to work on this

**Comment by rhymes** [comment] 2021-08-20 10:16
@vishaldeepak I've assigned it to you, thanks!

**Comment by vishaldeepak** [comment] 2021-08-21 12:15
@rhymes @cmgorton  Just want to confirm, we want to markdown process the tag's `short_summary`. 
That should be something like 
```
<%= sanitize MarkdownProcessor::Parser.new(@tag_model.short_summary).finalize %>
```
I also noticed that in  some models we stored  the processed markdown in database Do you think that's something we would want to apply to short summary

**Comment by rhymes** [comment] 2021-08-22 13:50
@vishaldeepak yep, we don't plan on storing `.short_summary` as HTML. Now that I think about it, I'm not even sure `short_summary` is supposed to allow Markdown in the first place. I'll ping the team internally next week and let you know

**Comment by rhymes** [comment] 2021-08-23 12:29
Hi @vishaldeepak, sorry for the misunderstanding. I've confirmed internally that this is a feature, not a bug. At the moment we don't plan to allow Markdown and thus HTML in the tag short summary. I'm going ahead and close this. Thanks again for the patience!

**Closed by rhymes** 2021-08-23 12:29 UTC
Labels: bug, area: tags
