### ISSUE TITLE
data-verb="unfollow" is not working after refreshing also it is showing data-verb="following" in code also & in UI too

### ISSUE THREAD

**Issue by krishnadevz** [forem/forem#11533] opened 2020-11-21 11:26 UTC
**Describe the bug**
A few days ago I am just followed ex:-user(krishnadevz) on dev and then for reading new articles I refreshed that page and after some time I accidentally unfollowed ex user and then I again refreshed the page and still, it is showing `following`.

**To Reproduce**
* SignIn 
* open dashboard following section 
* and unfollow someone and then refresh it shows following 

**Expected behavior**
* Expected behavior is normal when you unfollow someone else expected is `follow` not `following` i think this internal error on dev  

**Screenshots**
![descripfeatures](https://user-images.githubusercontent.com/42638797/99875967-a6d95e80-2c19-11eb-93b1-c2375f886ce1.gif)

**Desktop:**

- OS, version: windows version 20H2 os build 19042.630
- Browser, version: firefox=83.0 (64-bit)/chrome=Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by fdoxyz** [comment] 2020-11-21 16:09
I was able to reproduce this. The AJAX request responds with `200` success and payload `{"outcome":"unfollowed"}`. The actual follow disappears but it seems like the button state remains the same for some reason.

I think it may be related to caching, because the moment you sign out and sign in again the "cached" state goes away and you should be able to now see the "Follow" button instead of "Following".

@krishnadevz if you could help us confirm that after you logout and login again the button appears correctly?

This is definitely a bug but it may live on either the Service Worker or in the cache key we use for this view. ([here](https://github.com/fdoxyz/forem/blob/master/app/views/users/show.html.erb#L14-L15))

**Comment by krishnadevz** [comment] 2020-11-21 16:28
@fdoxyz logout stuff it is fine means in dashboard I can able to see I unfollowed that example user but in UI it is behaving unexpectedly I think something related caching and UI stuff related code is behaving unexpectedly

**Comment by LE-HU** [comment] 2020-12-10 02:29
Hello,
I've been able to replicate the issue. 

Bug appears both on **Chrome** v. 87.0.4280.88 (64-bit) and **Mozilla Firefox** v. 83.0 (64-bit). 
OS: **Ubuntu** 20.04.1 LTS

Logout -> Login method fix the issue, user page no longer shows "Unfollow" button, but the right "Follow" one.
Relation to caching seems right. I'll try to look into it, not sure about the outcome as I'm quite new around here.

**Comment by LE-HU** [comment] 2020-12-11 02:51
Ok I've researched here and there, but unfortunatelly I'm not able to solve the issue by myself.

HTML change occurs once the page reloads and looks like this -
initial state:
`<button id="user-follow-butt" class="crayons-btn whitespace-nowrap follow-action-button user-profile-follow-button" data-info='{"id":270314,"className":"User"}'>Follow</button>`
changes to \/ once the data is fetched:
`<button id="user-follow-butt" class="crayons-btn whitespace-nowrap follow-action-button user-profile-follow-button showing crayons-btn--outlined" data-info='{"id":270314,"className":"User"}' data-fetched="fetched" data-verb="follow">Following</button>`

Having a look at .js files, two functions seem to me to be taking action here, both located in 
../app/assets/javascripts/initializers/initializeAllFollowButts.js'

that's:
function initializeFollowButt
function fetchButt

Not sure how the caching/service workers handle these exactly, I'll leave it up to someone more experienced as of now. Thanks!

**Comment by rhymes** [comment] 2020-12-11 09:36
Thank you so much for the review @LE-HU, this is going to be super helpful to whomever picks it up!

**Comment by aitchiss** [comment] 2021-05-13 09:23
I think this is a backend issue related to the `follows_controller` call to 

```rb
following_them_check = Follows::CheckCached.call(current_user, params[:followable_type], params[:id])
```

- we post the update to unfollow a user (and receive a successful `{"outcome":"unfollowed"}` response
- when you refresh the page you can see the call to `follows/<userid>?followable_type=User` returns 'true' when it should be 'false'

It looks to me like `CheckCached` continues to return the old value, when we should be updating/invalidating that cache when the user unfollows someone. I guess the same doesn't happen with follows (as opposed to 'unfollows') because there was no "follow" in the original cache in that case 🙃 

I'm not familiar enough with the backend to know what the best way to go about resolving this is, but let me know if I've totally got the wrong end of the stick!

**Comment by rhymes** [comment] 2021-05-13 09:43
I think you're right @aitchiss! 

When we unfollow a user here:

https://github.com/forem/forem/blob/f7293c354462e9f7d921abb80a4e8dae5242b172/app/controllers/follows_controller.rb#L112-L117

the cached value that then we check here is not expired manually:

https://github.com/forem/forem/blob/f7293c354462e9f7d921abb80a4e8dae5242b172/app/services/follows/check_cached.rb#L16-L19

**Comment by aitchiss** [comment] 2021-05-13 10:06
Thanks @rhymes! I'm going to have a quick attempt to fix this 🤨

**Closed** 2021-05-19 16:40 UTC
Labels: Forem team, area: caching, area: followers, bug, size:XS, tech: frontend
