### ISSUE TITLE
Incorporate Twitter meta_data into Embed fallback flow

### ISSUE THREAD

**Issue by msarit** [forem/forem#17054] opened 2022-03-30 14:06 UTC
For Embeds that do not have a LiquidTag defined in our codebase, we render some fallback rich-content using OpenGraph (OG) meta data.

If there is not enough OG meta data to render a sensible fallback, we render a simple A-tag.

We utilized the MetaInspectorGem for scraping OG meta data from embedded links. This gem also makes TwitterCard meta data available (see below):

```
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://takeonrules.com/images/takeonrules.wordpress.com-banner.jpg" />
<meta name="twitter:title" content="About"/>
<meta name="twitter:description" content="Jeremy Friesen&amp;rsquo;s personal blog, with a focus on table-top role-playing games."/>
<meta name="twitter:creator" content="@jeremyfriesen"/>
```

Right now, the [Embeds fallback flow](https://github.com/forem/forem/pull/17001) uses only OpenGraph meta data. In order to still render rich-content, in the absence of certain OG data, the flow should check if corresponding TwitterCard data is available and use it if so.

For example, if the `og:image` is missing, the Embed flow should check for `twitter:image` and use that if available.

The Embed flow works very well as is, but I believe adding this TwitterCard layer underscores our pod's commitment to improving the Content Experience on Forems.

**Comment by mirie** [comment] 2022-11-04 20:17
Seems like a dupe of #17144 so closing

**Closed by mirie** 2022-11-04 20:17 UTC
Labels: bug smash
