### ISSUE TITLE
Remove Unpublished content from Notifications

### ISSUE THREAD

**Issue by ankitbeniwal** [forem/forem#12314] opened 2021-01-17 16:31 UTC
**Problem**:

Once  unpublished, an article is not removed from the notifications and takes the user to a 404 page when clicked.

**Ideal Solution**:

As soon as a publisher removes an article, the link to that article should be removed from the notification list of a follower.

**Comment by atsmith813** [comment] 2021-02-11 18:29
I'm not able to reproduce this 🤔 . Does anyone have more context?

We have code in place to handle this case. Maybe a user happened to have their notifications page already open, the post was unpublished, and the user never refreshed the notifications page?

**When an article is unpublished**, we delete the notifications associated with the article:
https://github.com/forem/forem/blob/e18a6b68a733de44263479bc341dd02d66a3ad09/app/controllers/articles_controller.rb#L290-L292

I tested this locally and confirmed the notification was gone entirely.

**When an article is destroyed**, we also delete the notifications associated with the article:
https://github.com/forem/forem/blob/e18a6b68a733de44263479bc341dd02d66a3ad09/app/controllers/articles_controller.rb#L176

https://github.com/forem/forem/blob/e18a6b68a733de44263479bc341dd02d66a3ad09/app/services/articles/destroyer.rb#L13

**Comment by ankitbeniwal** [comment] 2021-02-12 01:53
I have even logged out and in multiple times but the notification is still visible to me. @atsmith813 I am attaching a screenshot for reference.

![Screenshot_20210212-071654.jpg](https://user-images.githubusercontent.com/12103073/107721407-914c7000-6d02-11eb-9701-fc7ae1c76b64.jpg)

**Comment by atsmith813** [comment] 2021-02-12 15:43
Ah, I see. Thanks for the info @ankitbeniwal!

This is in the mobile app (looks like Android?). @fdoxyz do you know what the logic is in the mobile app for this screen?

**Comment by fdoxyz** [comment] 2021-02-12 17:35
This screen on the mobile apps works the same way it would on a browser: It would just render the `/notifications` page.

I tested this with two accounts that follow each other, publishing and un-publishing does work as expected (removes the lingering notification correctly).

I looked it up on my own notifications and I also have that broken link: https://share.getcloudapp.com/7KuppBX4

Some ideas/questions on the topic:
- Is it possible that a fix for this functionality was merged/fixed _after_ this specific post from Ben was unpublished/deleted?
   -  Doesn't look like this is the case because [the references here](https://github.com/forem/forem/issues/12314#issuecomment-777698229) have been there for a long time
- Maybe the code is executing a massive delete that errored/timed-out since Ben has a lot of followers?
   - Not sure if there's a way to validate this 🤔
- Is there a chance this post was unpublished/removed in an unconventional way that bypassed the delete cascade logic?
   - cc @benhalpern in case you might remember this particular post

**Comment by atsmith813** [comment] 2021-02-12 17:43
Great call @fdoxyz, thanks for the insight! It does seem everything is working as expected and this is an edge case. Let's see what @benhalpern knows about this post in particular.

**Comment by benhalpern** [comment] 2021-02-15 15:49
@atsmith813 @fdoxyz This post was not removed in an unconventional way... I believe this is, in fact, a logical error in how we handle a certain type of case. This was me accidentally publishing a post I decided to go in a different direction with, so 100% normal case. I don't know why our pipeline for removing notifications isn't always working, but there was nothing special about this one.

**Comment by atsmith813** [comment] 2021-02-15 20:29
Would it make sense to go ahead and move the logic into a callback? So that any time an Article is unpublished (via the console, the GUI, etc) we delete the notifications?

I also wonder if part of the issue is there are a handful of articles where `published` is `nil`. I thought that might be part of the problem since we look at `true` and `false`:

```ruby
 elsif @article.saved_changes["published"] == [true, false] 
 ```
 
 But when I tried this locally, I'm not sure how it's possible to go from `nil` to `false` unless the unpublishing was done via a console. When `published` is `nil`, the article shows as a draft in the GUI so you can't "unpublish" it that way 🤔 . When testing locally, I noticed updating an article via console did _not_ delete the notifications.
 
 cc: @citizen428 @rhymes @fdoxyz for thoughts and ideas!

**Comment by citizen428** [comment] 2021-02-16 03:08
> Would it make sense to go ahead and move the logic into a callback?

I'd probably prefer a service like `Articles::Unpublish`, which is more consistent with how we do things like suspending users. `Articles::Destroyer` may be able to serve as inspiration here.

**Comment by fdoxyz** [comment] 2021-02-16 13:42
Something that might be helpful would be to create a Blazer query (or a couple) to understand how many Notifications are left linked to slugs (of articles) that don't exist anymore. We may end up finding some similarities in them that would reveal why has this happened in the past. We also might need to create a DataUpdate Script to clean them up once we understand the root cause.

I still have a few other leads to investigate a bit further soon

**Comment by rhymes** [comment] 2021-02-16 14:57
This query might help:

```sql
SELECT count(*)
FROM notifications
WHERE json_data #>> '{comment,commentable,class,name}' = 'Article'
    AND json_data #>> '{comment,commentable,path}' NOT IN (SELECT path FROM articles);
```

it might timeout in production given the size of the `notifications` table, if so ask for support to run it manually.

**Comment by atsmith813** [comment] 2021-02-25 18:15
I'm not sure this is an issue 🤔 . It may have been a one-off bug where the worker to delete notifications failed.

Currently, there aren't any notifications linked to articles that no longer exist. And we have verified the logic works.

Does anyone have any ideas on how to proceed from here? Should we close this and keep an eye on it?

**Comment by citizen428** [comment] 2021-02-26 01:49
@atsmith813 I'd keep an eye on it for a couple more days first, then close the issue. Sounds good?

**Comment by atsmith813** [comment] 2021-04-08 14:57
Closing this one out as it doesn't seem to still be an issue. Thanks, @ankitbeniwal for all the help here!

**Closed by atsmith813** 2021-04-08 14:57 UTC
Labels: Forem team, area: articles, bug, size:XS, tech: backend
