### ISSUE TITLE
feature request: show banner images on feeds

### ISSUE THREAD

**Issue by trusktr** [forem/forem#12088] opened 2020-12-31 23:49 UTC
At the moment, only the main feed show banners. For example:

![Screenshot from 2020-12-31 15-48-10](https://user-images.githubusercontent.com/297678/103431098-bbe1cf80-4b7f-11eb-9960-58f81ec8b7bc.png)

The post titled `Markdown documentation format concept` has a banner image.

And here is the tag feed for `#markdown`:

![Screenshot from 2020-12-31 15-48-27](https://user-images.githubusercontent.com/297678/103431086-a2d91e80-4b7f-11eb-8dc1-90d1871ab9bb.png)

The same post has no banner image.

**Comment by cmgorton** [comment] 2021-01-05 14:37
Thanks for opening this @trusktr . @forem/design is this a choice made by the team or should I label this a bug to be looked at?

**Comment by cmgorton** [comment] 2021-01-05 14:39
@forem/design is this a feature we would like to implement or is the lack of a banner on all feed a specific choice by design/product? Thanks for any more info.

**Comment by ludwiczakpawel** [comment] 2021-01-07 11:38
I think for now we can keep it as is. The image shows up on home page feed because it's a way of promoting some posts. But when user is browsing a specific tag, I don't think they want to be engaged or "_tricked_" in such a manner. Instead, I hypothesize that the actual "equality of posts" is much more important there than it is on home feed. It's like a rolodex with business cards - I wanna browse business cards without expectation that one of them has, for example, a different shape. 

But it's just my thinking right now - I could be easily convinced to something else :D

**Comment by trusktr** [comment] 2021-01-07 18:06
I think banners are a good for people who put more effort to stand out.

I updated the title, because now (unlike before) dev.to shows banners only for the very first post at the top of the feed.

If you want posts to be equal, then there should be no banners at all on feeds, because right now only the most popular ones get banners (if they are at the top of a feed), and that makes them unfairly get more views.

This means that the vast majority of the time, people's post banners go unused within feeds.

Feed are a great way to appeal to people, because people are visual beings. Plus it gives the opportunity to place logos or icons on a banner to give identity. This makes it easier to see and find certain posts.

For example, imagine people that post demos of webgl and other visual things. They should be visible to people who look for those sorts of posts.

Imagine if Twitter decided to show zero images or attachments on twitter feeds...

**Comment by trusktr** [comment] 2021-01-08 17:44
What if there's a config option? Users can choose to have them on all posts (that have banners), only on top posts, or on none. We can see which options people like most.

**Comment by ludwiczakpawel** [comment] 2021-01-11 08:32
> What if there's a config option? Users can choose to have them on all posts (that have banners), only on top posts, or on none. We can see which options people like most.

Eventually we will probably have something like GMail where users could choose density of the feed design. But seems like this is a bit far on the roadmap. Separately we want Admins to predefine default option for their communities, and that part, I believe, is already in progress (or maybe even already built - I apologize, I'm not super familiar with our Admin side of things).

![image](https://user-images.githubusercontent.com/108287/104158304-51395b00-53ed-11eb-86d0-fe0e8005d358.png)

> now (unlike before) dev.to shows banners only for the very first post at the top of the feed

Can please you elaborate here? DEV has always showed image on the first post of the feed - this isn't anything new.

> right now only the most popular ones get banners (if they are at the top of a feed)

That's the point of the feed. It's a place where user can find _a bit more tailored_ list of posts to read. It's based on followed tags (interests) etc. I think the lack of visual balance on the feed (for example because of the image on the first post) is actually what makes it more interesting. As far as I know, not every post can be on the top of the feed - it needs to meet certain criteria in terms of popularity etc. Therefore I think it's fair to sometimes "promote" posts that people are actively commenting on or reading.

**Comment by cmgorton** [comment] 2021-02-23 21:06
Hey @truskr  
Features tend to be subjective and might spur some debate as you can see in this issue 😄. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it. Given Pawel's response and our current roadmap I am going to close this request here but again feel free to start a conversation in forem.dev around this issue! Thanks.

**Closed by cmgorton** 2021-02-23 21:06 UTC
Labels: inquiry: needs review
