### ISSUE TITLE
Editor area not clickable

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#8785] opened 2020-06-19 01:10 UTC
Only the 27px high area where the placeholder is is clickable at first.

I recall this getting resolved while we were first deploying, but the issue is back.

<img width="700" alt="Screen Shot 2020-06-18 at 9 07 48 PM" src="https://user-images.githubusercontent.com/3102842/85086263-10a39700-b1a8-11ea-96cc-fdbebe07120f.png">

The whole area should be the `textarea` and it should be clickable.

**Comment by citizen428** [comment] 2020-06-19 03:28
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment] 2020-06-19 03:35
It seems like only `crayons-article-form__body text-padding` is the click target, but maybe all of `class="crayons-article-form__content crayons-card"` should be.

<img width="623" alt="Screen Shot 2020-06-19 at 10 29 04" src="https://user-images.githubusercontent.com/47985/85093929-b5a98880-b217-11ea-9993-ae1faa51505a.png">

**Comment by emgoto** [comment] 2020-07-18 03:16
Hi! Tried to reproduce this issue on Firefox but I couldn't, maybe it's already been fixed?

![image](https://user-images.githubusercontent.com/33337378/87843554-ed7c1c80-c8f8-11ea-968c-1e5cec02ad3a.png)

**Comment by Ridhwana** [comment] 2020-07-20 09:10
Hi @emgoto. I've done some checks and I'm confirming as per your comment above that this looks like it has been fixed. I'll be closing this issue, thanks 😊

**Closed by Ridhwana** 2020-07-20 09:10 UTC
Labels: area: publishing experience, difficulty: easy, tech: javascript, type: bug
