### ISSUE TITLE
Dev.To Android app not able to view feeds. 

### ISSUE THREAD

**Issue by zachjonesnoel** [forem/forem#14742] opened 2021-09-16 05:30 UTC
**Describe the bug**

I use Dev.To Android app for reading all the feeds and posts. And today when I tried to open the app all I see is a blank screen.

**To Reproduce**

1. On app open, feeds is empty.
2. On icon click, feeds don't refresh.
3. On pull to refresh, feeds is empty.

**Expected behavior**
On app open / click/ pull to refresh actions it should be able to call the API and fetch all feeds.

**Screenshots**
![Screenshot_2021-09-16-10-48-56-43_f41347bffa7f8365be7df3528708f315](https://user-images.githubusercontent.com/12515425/133554944-730ced2c-f5f9-4c7c-9ecc-9fabbaabac3c.jpg)

**Desktop (please complete the following information):**

- OS, version: 
- Browser, version: 

**Smartphone (please complete the following information):**

- Device: OnePlus Nord 2
- OS, version: Android 11
- Browser, version: 
- App version : 1.5.0-2 
**Additional context**

**Comment by fdoxyz** [comment] 2021-09-17 15:30
Hi @zachjonesnoel, thanks for the bug report. It's hard to tell what might've caused this problem but there's a chance this was a blip in the page load itself. Maybe it was a temporary bug that got fixed by now, because I'm not able to reproduce this after restarting the DEV Android app a few times on Android 11 too (I tried while on Wi-Fi but also on 3G network). 

Is this something that happens repeatedly on your end? Does tapping on the DEV icon or restarting the app fixes the problem?

**Comment by zachjonesnoel** [comment] 2021-09-17 16:21
Hi @fdoxyz, 
this morning (India time) when I checked it had the same issue on both Wi-Fi and mobile 4G network. But now when I tried the same app froze I killed it and opened the feed was there. 

 there's a chance this was a blip in the page load itself - 
I did suspect that but it kept happening repeatedly when using the app. Eg. I would kill and open the app, feeds show up and I read a post and go back its empty. clicking on icon and pull to refresh as well same response. This happens only when using the app for a while and then going to feed. 

 Does tapping on the DEV icon -
No, empty feed but Dev.to's coding conference poster is available.
 Restarting the app fixes the problem -
Yes, after killing the app and opening it fresh it would resolve the problem.

**Comment by zachjonesnoel** [comment] 2021-09-19 05:35
Hi @fdoxyz, not sure if something was addressed or it was just a blip because yesterday and today the app is working good. Unless you want to investigate it more, I think the issue could also be closed.

Appreciate you taking your time testing out and quick responce to my issue.

Happy coding! 👨‍💻

**Comment by citizen428** [comment] 2021-09-27 05:15
Hi @zachjonesnoel, I'll be closing this issue now, please feel free to re-open it if you experience this problem again.

**Closed by citizen428** 2021-09-27 05:15 UTC

**Comment by zachjonesnoel** [comment] 2021-09-27 17:38
Sure @citizen428 I'm currently not facing this issue I believe it was a blip.

**Comment by zachjonesnoel** [comment] 2021-10-02 14:35
Hi @citizen428 and @fdoxyz I got that blip today as the banner of Hacktoberfest was added.

![Screenshot_2021-10-02-20-03-50-39_f41347bffa7f8365be7df3528708f315.jpg](https://user-images.githubusercontent.com/12515425/135721076-9e6a36f8-5ce9-494c-8226-cb148633e3a8.jpg)
