### ISSUE TITLE
StackBlitz Liquid Tag Embed improperly sizing on mobile

### ISSUE THREAD

**Issue by johnbwoodruff** [forem/forem#1155] opened 2018-11-19 20:58 UTC
**Describe the bug**

On a mobile device the StackBlitz liquid tag slightly overflows. (see screenshot)

**To Reproduce**

1. Go to https://dev.to/johnwoodruff91/changelog-new-stackblitz-liquid-tag-187e
2. Scroll down to the embedded StackBlitz iframe
4. See how embedded content overflows to the right.

**Expected behavior**

Should properly size to 100% of the width (minus outer padding)

**Screenshots**

![img_2999](https://user-images.githubusercontent.com/5883616/48734358-7150a380-ec02-11e8-9ea1-992b0b7e6d3c.PNG)

**Smartphone (please complete the following information):**

- Device: iPhone 7s Plus
- OS: iOS 12.1
- Browser: Safari

**Comment by jbw91** [comment] 2018-11-19 21:00
@benhalpern I'm noticing that when sizing your screen down using Chrome or Safari's mobile device emulator, it sizes properly. I've only been able to reproduce this ON a device. See screenshot:

<img width="759" alt="screen shot 2018-11-19 at 1 59 28 pm" src="https://user-images.githubusercontent.com/5883616/48734677-5b8fae00-ec03-11e8-8a4e-5f840fd14137.png">

I'm not sure what's going on here, why it wouldn't be sizing properly. Will keep looking.

Also you can assign this to me if you want. :)

**Comment by jbw91** [comment] 2018-11-19 21:07
Just tested it on a Samsung Android device using Chrome, and it sizes correctly as well. Looks like it's only happening on mobile Safari webviews, whether that be through Safari itself, Chrome, or the Dev iOS app, all of which of course use Safari's webview.

![screenshot_20181119-160258](https://user-images.githubusercontent.com/5883616/48734943-30f22500-ec04-11e8-8c28-2f90c0f724fe.jpg)

Any thoughts @benhalpern? I've never seen this personally.

**Comment by jessleenyc** [comment] 2018-11-20 17:42
Thanks for flagging this. Brought it up in a meeting today and it's on @benhalpern's radar.

**Comment by Zhao-Andy** [comment] 2019-02-19 19:50
Not stale, still a valid bug.

**Comment by cmgorton** [comment] 2021-01-26 20:40
@Zhao-Andy do you know if this is still a valid bug?

**Comment by johnbwoodruff** [comment] 2021-01-26 21:24
I'm not @Zhao-Andy but I can verify it's not an issue anymore. :)

![image](https://user-images.githubusercontent.com/5883616/105907408-2bfa3e80-5fe2-11eb-9225-9a1beae33803.jpeg)

**Comment by cmgorton** [comment] 2021-01-26 21:25
Thank you @johnbwoodruff ! I appreciate the confirmation here. I will go a head and close this issue.

**Closed by cmgorton** 2021-01-26 21:25 UTC
Labels: area: publishing experience, bug, ready for dev
