### ISSUE TITLE
Notifications pane not working

### ISSUE THREAD

**Issue by agusnavce** [forem/forem#4723] opened 2019-11-04 19:43 UTC
**Describe the bug**
When I enter the notification center, i can't see any notifications.

**To Reproduce**
I saw a notification alert, clicked on it.
The notification page opened but no notifications were visible.

**Expected behavior**

To see my notifications.

**Screenshots**

![image](https://user-images.githubusercontent.com/17863261/68152380-4dc15e80-ff22-11e9-88b4-c34977cb55f4.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser: Chrome
- Version: 78

**Comment by maestromac** [comment] 2019-11-05 20:36
Hello @agusnavce , are you still experiencing this issue? can you open up your browser console and tell me what you see? If you are still experiencing this, can you try to browse dev.to without any extensions?

**Comment by agusnavce** [comment] 2019-11-11 13:25
@maestromac I'm still experiencing this issue. I've opened it on firefox wo extensions and in chrome and can't see any notifications. 
My pane:
![image](https://user-images.githubusercontent.com/17863261/68590506-6f17d280-046d-11ea-8cda-7d0a21caf0ab.png)

Console:

![image](https://user-images.githubusercontent.com/17863261/68590555-95d60900-046d-11ea-9fc9-314b6fb33503.png)

**Comment by keithrbennett** [comment] 2019-11-19 09:55
I am experiencing something similar. When I go to https://dev.to/notifications/comments while logged in, I see only blank space to the right when "Posts" or "Comments" is selected. However, when "All" is selected, I do see content to the right. I'm attaching the two screenshots.

<img width="961" alt="all" src="https://user-images.githubusercontent.com/28410/69136356-4cc92900-0aed-11ea-82ff-6fd9e4babd27.png">
<img width="1275" alt="comments" src="https://user-images.githubusercontent.com/28410/69136359-4d61bf80-0aed-11ea-92d0-3fb00372ea78.png">

**Comment by TheJaredWilcurt** [comment] 2020-01-09 03:04
Same, this has been happening for months.

Firefox (latest)
Windows

All/Comments/Posts are all empty despite having a notification alert.

**Comment by maestromac** [comment] 2020-01-23 20:06
@TheJaredWilcurt can you share with us your browser console's output?

**Comment by mstruve** [comment] 2020-11-08 16:52
@agusnavce thank you so much for reporting this! Since being reported we have updated a lot of our notification code and I have not been able to reproduce this with the new code so I am going to close this issue. If you can still reproduce this please let us know and we will reopen and look further into it! 

@TheJaredWilcurt also please check this functionality and if you are still having issues please reopen. 

Thank you both for being a part of the Forem community!

**Closed by mstruve** 2020-11-08 16:52 UTC
Labels: area: notifications, type: bug
