### ISSUE TITLE
Mention autocomplete loses styling after removing focus to the page

### ISSUE THREAD

**Issue by rhymes** [forem/forem#13464] opened 2021-04-21 13:54 UTC
**Describe the bug**

This is a bit bizarre but I noticed how the autocomplete component entirely loses its styling if you navigate away from the page, either by pressing `Cmd-Tab`/`Alt-Tab` to switch the active window or changing the active tab.

**To Reproduce**

1. Open https://dev.to/new
2. Activate the component by typing `@something`
3. Leave the dropdown open and either select another browser tab with the mouse or press ``Cmd-Tab`/`Alt-Tab` to switch the active window
4. Go back and see the component without styling

**Expected behavior**

To the component to stay where it is as it is or to be closed. 

GitHub closes the component with the tab/window loses its focus

**Screenshots**

https://user-images.githubusercontent.com/146201/115565628-d0c2aa00-a2b9-11eb-8769-013942279a9a.mov

**Desktop (please complete the following information):**

- OS, version: macOS Catalina
- Browser, version: Firefox 89beta

**Comment by Link2Twenty** [comment] 2021-04-26 13:00
Looks like the problem is with `ComboboxPopover` it thinks it's time to close (so sets the width to 0) but `closeOnClickOutsideListener`  isn't being called so `searchTerm` isn't being reset.

<https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx>

**Comment by rhymes** [comment] 2021-04-26 15:28
Great find @Link2Twenty, thank you!

**Comment by aitchiss** [comment] 2021-04-30 14:28
I think this has been fixed by #13600 (I separately noticed this and fixed it before seeing this issue 😆 ) so I'm going to close this issue - let me know if you still encounter it though!

**Closed by aitchiss** 2021-04-30 14:28 UTC
Labels: area: design, bug, ready for dev
