### ISSUE TITLE
Chat can't change to group mode

### ISSUE THREAD

**Issue by omenking** [forem/forem#14034] opened 2021-06-21 17:24 UTC
**Describe the bug**

As a moderator, I want to go to the group chat to ask a question.
When I click group it does not change, so I cannot converse
![image](https://user-images.githubusercontent.com/7776/122802860-e3deff80-d293-11eb-8236-ec95b7d509a4.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:
Chrome latest, Windows 10

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by cmgorton** [comment] 2021-06-21 18:35
I can't reproduce yet. I was able to navigate to the group tab. 
Would you be able to record a quick Loom of what you are seeing @omenking ?

**Comment by citizen428** [comment] 2021-06-22 06:33
@cmgorton It looks to me like the "direct" and "group" buttons are not actually doing anything (clicking either doesn't remove the other type), so if one has a lot of direct messages clicking "group" would indeed not bring them back.

**Comment by cmgorton** [comment] 2021-06-22 14:33
Ah ok! Thanks for the confirmation @citizen428

**Comment by cmgorton** [comment] 2021-09-09 16:59
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)

**Closed by cmgorton** 2021-09-09 16:59 UTC
Labels: area: connect
