### ISSUE TITLE
Fix width overflow/horizontal scrolling on admin.forem/Admin Docs link pages and footer copyright year

### ISSUE THREAD

**Issue by iprasandeep** [forem/forem#19403] opened 2023-04-29 12:49 UTC
**Describe the bug**
Fix width overflow on Admin Docs link pages, actually, the width is overflowing out of screen size, after visiting every links pages
for ex: https://admin.forem.com/docs/getting-started/creator-signup-and-onboarding

**To Reproduce**

Steps to reproduce the behavior: from my intuition

- There is some CSS issue in the code, when 
  1. I did class"row" width:100% it worked fine but all content was justified left side. 
  2. or we can also change the margin property of the row class. But still, it's not the approach.
  3. For the footer change 2022 to 2023.

**Expected behavior**

1. The expected behavior, all pages should be fit on-screen without any horizontal scrolling /width overflow.
2. Copyright year should be for ex: 2016 - 2023 or 2023. instead of 2022.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/52857138/235303226-80c3aaf7-0db5-42e5-8584-84d31e273a7a.png)

![image](https://user-images.githubusercontent.com/52857138/235302695-42ab4f84-c02b-4f63-a979-7e28f28c8e3d.png)

After: 
![image](https://user-images.githubusercontent.com/52857138/235303004-acae8477-8f8d-4b2f-99ec-489b189a1c19.png)
Here I just added **width:100%** to the **row class**, I know it's not the right working solution, feel free to give your suggestions.

**Desktop (please complete the following information):**

- OS, version:  Ubuntu 22.04 LTS
- Browser, version:  Chrome v 10.0.5481.177, Firefox v 112.0.2 

**Smartphone (please complete the following information):**

- Device: Redmit Note 10
- OS, version: Android 12
- Browser: Chrome

**Comment by Nitz2611** [comment] 2023-05-01 13:21
Hey, can you assign me for this?

**Comment by Nitz2611** [comment] 2023-05-01 14:27
hey assign me for this.

**Comment by mirie** [comment] 2023-09-14 01:43
Thanks for reporting! I am afraid I couldn't reproduce this so closing for now.

**Closed by mirie** 2023-09-14 01:43 UTC
