### ISSUE TITLE
Open links to externsl pages in a different tab

### ISSUE THREAD

**Issue by filipeqm94** [forem/forem#11304] opened 2020-11-07 10:32 UTC
Hello everybody, I'm Filipe and I'm somewhat new to coding and dev.to in general. Yesterday I found about the website through CodeCademy's suggestion for Coding Communities, and I couldn't help but noticing that everytime I clicked on a Link for an external page, it would use the current tab I was reading.

I think it would be a nice idea to introduce a feature where when you click on a link that directs to an external page, it would open a new tab, instead of using the one you're currently working on.

If this is an issue that doesn't bother most readers, would it be possible to make it a toggle option for opening external links in new tabs? There are amazing articles worth reading in the website and most times it's frustrating to click on something that you want to check out later and get your immersive read interrupeted.

**Comment by rhymes** [comment] 2020-11-07 12:04
Hi @filipeqm94, thanks for contributing your idea, I'm going to close this as a duplicate of https://github.com/forem/forem/issues/1716 and encourage you to leave a comment there to add to the entire discussion.

Thank you!

**Closed by rhymes** 2020-11-07 12:04 UTC
