### ISSUE TITLE
Writing Streak Progress

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#9679] opened 2020-08-07 21:28 UTC
**Is your feature request related to a problem? Please describe.**

When writing it would be nice to know how far along you are to the next streak badge.

**Describe the solution you'd like**

Have a screen that say "you are currently on a 6 weeks streak, only 2 weeks until you unlock your 8 week streak badge"

**Additional context**

I think I'm on a streak but I posted a post with a 170 hour space, so maybe the streak is broken, I'm not sure but I'd like a way to know either way.

![Worried Frog](https://media1.tenor.com/images/1f8c7736a46059a800df67a2779b3a86/tenor.gif)

**Comment by rhymes** [comment] 2020-08-08 06:29
Hi @Link2Twenty - I reckon this is sort of a duplicate of https://github.com/forem/forem/issues/9210

Let me know if it's not

**Comment by Link2Twenty** [comment] 2020-08-08 08:11
You're 100% right, I did a search for writing streak specifically not just badges 😅

**Closed** 2020-08-08 08:12 UTC
Labels: area: badges, type: feature request

**Comment by james-wallis** [comment] 2021-04-14 12:27
In case anyone comes upon this issue - I made a tool that will calculate your current writing streak for you. Hope it helps!

https://devto-writing-streak-calculator.wallis.dev
