### ISSUE TITLE
Bad regex for detecting SVG on Navigation Links

### ISSUE THREAD

**Issue by omenking** [forem/forem#14334] opened 2021-07-26 13:06 UTC
The dreaded error:

<img width="1018" alt="Screen Shot 2021-07-26 at 8 57 12 AM" src="https://user-images.githubusercontent.com/7776/126993336-98586854-0676-42de-98da-dafc584bdf8f.png">

Code in question:

```rb
class NavigationLink < ApplicationRecord
  SVG_REGEXP = /<svg .*>/i.freeze
```

Testing with rubular
<img width="955" alt="Screen Shot 2021-07-26 at 9 03 10 AM" src="https://user-images.githubusercontent.com/7776/126993412-d9c51c0a-650b-4843-8d64-9eb9ca3a3595.png">

So the problem is that the Regex expects svg text to be all on a single line:

<img width="1026" alt="Screen Shot 2021-07-26 at 9 06 04 AM" src="https://user-images.githubusercontent.com/7776/126993535-996ea229-fb5e-42d5-9ea6-13ae1ee26d47.png">

When exporting svg from illustrator it will sometimes insert a XML schema tag first.

Yep Single line formatting fixed it:

<img width="597" alt="Screen Shot 2021-07-26 at 9 11 39 AM" src="https://user-images.githubusercontent.com/7776/126994357-a23f4f06-62e7-4988-9532-748d166e89a8.png">

**Comment by rhymes** [comment] 2021-07-26 15:30
@omenking I took a quick look but I wasn't able to reproduce, can you please describe what you did and attach the media if possible?

**Comment by SiddharthShyniben** [comment] 2021-08-12 02:30
I think this can be fixed by giving the regex the `DOTALL` (`s`) flag

**Comment by SiddharthShyniben** [comment] 2021-08-12 02:32
@rhymes I think the problem is the current regex doesn't match any newlines, so if the SVG contains newlines in the `<svg>` tag, this regex doesn't match.

So this matches:
```html
<svg ...>
```

But this wont:

```html
<svg ...
     ...>

**Comment by citizen428** [comment] 2021-08-12 04:56
@SiddharthShyniben The flag to match  `.` match newlines in Ruby is `m` but otherwise, you're correct.

https://rubular.com/r/3CCXiqFPznQdkh

Do you want to make a PR? 😃

**Comment by SiddharthShyniben** [comment] 2021-08-12 05:08
@citizen428 Sure! I'll take this up

**Closed** 2021-08-13 06:46 UTC
Labels: bug, area: admin
