### ISSUE TITLE
[dev.to] Changes made to profile page URI don't overwrite the old one

### ISSUE THREAD

**Issue by nakhodkin** [forem/forem#11868] opened 2020-12-11 21:14 UTC
_created as a suggestion to do so after the short reply received from [yo@dev.to](mailto:yo@dev.to)_

The text of the original letter is as follows

> Hello there.
> 
> I’m running into some uncommon behavior with profile URL on [dev.to](https://dev.to)
> Here is what I did.
> 
> 
> Initially, I’ve had a username on [dev.to](https://dev.to) as “**nakhodkiin**” and the user profile was publicly available under the following URI: [https://dev.to/nakhodkin](https://dev.to/nakhodkiin)
> 
> Then I’ve changed my username to “**nakhodkin**” and after that profile page has become available under [https://dev.to/nakhodkin](https://dev.to/nakhodkin)
> 
> Well, the issue that, the previous URI e.g. https://dev.to/nakhodkiin is still active.
> 
> 
> Well, you get the idea, right now I’ve changed my username to “**randomguy**” then changed back to “**nakhodkin**” which means that as of now these are
> 
> [https://dev.to/nakhodkiin](https://dev.to/nakhodkiin)
> [https://dev.to/nakhodkin](https://dev.to/nakhodkin)
> [https://dev.to/randomguy](https://dev.to/randomguy)
> 
> pointing to my profile page. Idk if it’s the issue if someone for any crazy reason wanted to change her username a billion times through the automation and flood you with billion URIs somewhere on your storage system😀
> 
> 
> Thank you,
> Artem

**Comment by rhymes** [comment] 2020-12-12 08:35
Hi @nakhodin, we only store the last 2 usernames and redirect, this is a feature to prevent squatting :) 

Going to close this as it's not a bug, thanks for the reminder!

**Closed by rhymes** 2020-12-12 08:35 UTC
