### ISSUE TITLE
I cannot see the title when writing new post

### ISSUE THREAD

**Issue by tombohub** [forem/forem#12193] opened 2021-01-10 01:29 UTC
**Describe the bug**
Cannot see the title as per screenshot: http://prntscr.com/wk1bp8

**To Reproduce**

Go to dev.to
click "write a post"
start writing title

**Expected behavior**

To see the title I am writing

**Screenshots**

http://prntscr.com/wk1bp8

**Desktop (please complete the following information):**
OS : Windows 10
Browser: Chrome 87.0.4280.88 (Official Build) (64-bit)

**Comment by rhymes** [comment] 2021-01-11 08:38
Hi @tombohub, thanks for the report! I believe what you're experiencing is a variation (or the same issue) on https://github.com/forem/forem/issues/11619 - can you confirm?

**Comment by tombohub** [comment] 2021-01-12 16:02
@rhymes  it's a variation yes. Mine happens immediately when start writing title. For some reason the box inline `style` changes from 64px to 26px.  screenshot: http://prntscr.com/wlxg6r

**Comment by cmgorton** [comment] 2021-01-19 16:43
Hey @tombohub I don't have Windows so wasn't able to test this yet but can you try clearing your cache and seeing if this issue still persists for you?

**Comment by tombohub** [comment] 2021-01-19 21:21
Hello @cmgorton  yes it does, I have also tried different browser. Microsoft edge, same thing

**Comment by cmgorton** [comment] 2021-01-20 13:59
Ok thanks for letting me know!

**Comment by ludwiczakpawel** [comment] 2021-01-21 12:10
It's a duplicate of an existing issue https://github.com/forem/forem/issues/10114 so I'm closing this one.

**Closed by ludwiczakpawel** 2021-01-21 12:10 UTC
Labels: area: publishing experience, bug
