### ISSUE TITLE
Update the Color Selector on the Creator Settings Page

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#15354] opened 2021-11-11 19:50 UTC
**📖  As a Forem Creator, I want my experience to be as UI pleasing as possible, so that I feel motivated to continue with the journey.** 

_(Format:  As a [persona], I [want to], [so that])_

![](https://user-images.githubusercontent.com/108287/116532347-6d033700-a8e0-11eb-8dae-88bf6164f682.png)

**🐣TASKS**
- [ ] Update the color selector field's styling to reflect the design's styles for the color selector on the form

**_See:_** https://github.com/forem/rfcs/blob/a8d843d9a37c4105850f575f6e51faac7377a474/text/0190-admin-onboarding.md

**Comment by juliannatetreault** [comment] 2021-11-22 17:59
Hey, @ludwiczakpawel 👋  Do you happen to have the paint bucket SVG displayed on this form (the one next to the color selector)? We need it to complete this task. 😊

**Comment by ludwiczakpawel** [comment] 2021-11-22 19:17
Is this going to do anything specific? Or is it just a decoration? If it's just a decoration, please ignore and feel free to close this task :)

Originally it was intended to "launch a thing" with some predefined color options. And that has not really been designed ever. But also, from time perspective, this "idea" was probably a bit sill or at least not justified enough.

**Comment by juliannatetreault** [comment] 2021-11-22 19:23
> Is this going to do anything specific? Or is it just a decoration? If it's just a decoration, please ignore and feel free to close this task :)

As far as I know, and from what I can tell when looking at the RFC (there is no defined interaction for the color selector SVG), it appears to just be a decoration. 😊 

> Originally it was intended to "launch a thing" with some predefined color options. And that has not really been designed ever. But also, from time perspective, this "idea" was probably a bit sill or at least not justified enough.
_Ohhh_, this is excellent information! I had no idea that there were talks of having the SVG be interactive at one point. 😄 

Thank you so much for the response, @ludwiczakpawel! 🙌  I'm going to leave this issue open, as we need to may need to still tweak the color selector field's styles a bit -- I'll bring this to the Admin Experience Pod's attention to see if we can just go ahead and close this issue!

**Closed** 2021-11-23 15:21 UTC
Labels: area: admin, Forem team, tech: fullstack
