### ISSUE TITLE
Bug in IOS

### ISSUE THREAD

**Issue by RafaelM10** [forem/forem#18374] opened 2022-08-24 23:38 UTC
**Describe the bug**

<p> have the DEV.TO application installed on SO:IOS and when it enters the YEARS screen it closes automatically. I believe it is a functionality that should work normally taking the past years with the information of the posts, along with the current one we are. Now if it's a feature that isn't supposed to work, then let's have it on the cell phone.</p> 

**To Reproduce**

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/93865745/186541326-6242bd1c-7a4c-480a-8daf-8424f7a6b156.mp4

**Smartphone **

- Device: Iphone
- OS, version: 15.6.1
- App, version: 1.0.1

**Comment by amywtlin** [comment] 2022-08-30 06:05
@RafaelM10 It looks like a rather old version of the iOS app to me (current version is 1.4.4) - can you update your app to the latest version and try again?

**Comment by amywtlin** [comment] 2022-09-07 00:52
@wojtekxtx I am still unable to reproduce with my device. @wojtekxtx can you share your device and OS details?

**Comment by wojtekxtx** [comment] 2022-09-07 15:13
@amywtlin: ok. Going deep:

* iOS ( from Settings > General > About > iOS version ) : 16.0 (20A5358a)
* 256 GB

Your tits?

**Comment by mirie** [comment] 2022-11-30 18:59
@rt4914 / @fdocr : Who would be best to tackle this one?

**Comment by wojtekxtx** [comment] 2022-11-30 19:01
@mirie no idea TBH

**Comment by rt4914** [comment] 2022-12-01 11:48
@RafaelM10 @mirie @wojtekxtx 

The application displayed in the video is not the official application. It has been created by some independent developer not associated with DEV or Forem.[ Reference to unofficial app](https://apps.apple.com/br/app/devto/id1591660057?l=en)

The official application in past was [DEV Community](https://apps.apple.com/us/app/dev-community/id1439094790) and now the official app is [Forem](https://apps.apple.com/us/app/forem/id1536933197) in which users can access dev.to along with other forems like https://www.codenewbie.org/ and many more.

We highly recommend installing and using [Forem](https://apps.apple.com/us/app/forem/id1536933197)

@mirie This issue can be closed now.

**Comment by wojtekxtx** [comment] 2022-12-02 07:34
> with other forems like https://www.codenewbie.org/ and many more.

@rt4914 hehe, nice spoiler of your another in-house site; `seo` making I see :)

**Comment by mirie** [comment] 2022-12-02 16:45
Closing as won't fix

**Closed by mirie** 2022-12-02 16:45 UTC
Labels: bug, area: mobile
