### ISSUE TITLE
Accessing dev.to in browser leads to (503) error

### ISSUE THREAD

**Issue by maureento8888** [forem/forem#9776] opened 2020-08-13 18:29 UTC
**Describe the bug**

**To Reproduce**

1. Search 'dev.to mapbox vue'
2. Click on 'https://dev.to/hmintoh/how-to-mapbox-with-vue-js-2a34'
3. Wait couple seconds for loading
4. See error 503 and cute animal :) 

**Expected behavior**

I expected after clicking on the article in the results display (after finding the correct title), that the link would be able to retrieve the requested article and I would be on dev.to looking at the header of the article I requested.

**Screenshots**
This is what I encountered when the request was not completed after clicking on the dev.to article link:
![503-dev-error](https://user-images.githubusercontent.com/51500550/90172040-6e9bc780-dd70-11ea-9c5f-edc7972b13c5.png)

**Desktop (please complete the following information):**

- MacOS Catalina, 10.15.4 v.
- Safari, 13.1 v.

**Additional context**

Not the first time I've come across this issue with dev.to, but the error page with a cute picture was definitely new. I find that when I access dev.to midday (location is in Toronto, ON (GMT-4)
Thursday, August 13, 2020, 2:26 p.m.), dev.to is slow to respond and doesn't load at all.

**Comment by maureento8888** [comment] 2020-08-13 18:32
This issues (#9776) is by me!

**Comment by citizen428** [comment] 2020-08-17 03:49
Thanks for the report @maureento8888. Unfortunately, I'm not able to reproduce this. Searching for the suggested keywords and clicking through to the article works as expected. Is this still an issue for you?

**Comment by maureento8888** [comment] 2020-08-27 01:36
Nope! Not an issue now, although it sometimes hits for no particular reason and I have to wait for later for it to work again!

Thanks so much though 🙌🏼

**Comment by citizen428** [comment] 2020-08-27 04:50
Thanks for clarifying @maureento8888! I will close this issue for now, if you encounter similar problems in the future — especially if they are more persistent — please feel free to open a new one.

**Closed by citizen428** 2020-08-27 04:50 UTC
Labels: needs info
