### ISSUE TITLE
Receiving Message Notifications from Blocked User

### ISSUE THREAD

**Issue by 5t3ph** [forem/forem#9336] opened 2020-07-15 19:41 UTC
**Describe the bug**

After blocking a user, I received two notifications that they had messaged. The message area had no content, but I expected to not get notifications.

**To Reproduce**

- Blocked a user
- Blocked user sent messages
- Message notification icon showed that messages had been received

**Expected behavior**

- Minimum: No message notifications when a message is received from a blocked user
- Ideal: That the blocked user is fully prevented from even attempting to message me

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: macOS Catlina
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by jacobherrington** [comment] 2020-07-15 20:22
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by narender2031** [comment] 2020-07-17 04:53
@5t3ph I am not able to reproduce this bug locally. Can you please create a short video/gif for this bug. That will help us. Thanks.

**Comment by 5t3ph** [comment] 2020-07-25 19:45
Hi @narender2031 I'm sorry but since it was a short-lived thing that only happened twice I do not have additional artifacts to share.

Once I clicked the notification icon, I was navigated to the blocked user's name in my inbox but no message was shown. The issue was in getting any notification at all given the user was blocked.

**Comment by narender2031** [comment] 2020-09-18 05:41
@5t3ph Thanks for the feedback. I will take look at this.

**Comment by rhymes** [comment] 2020-10-01 06:57
@narender2031 were you able to find out what happened here? Thanks!

**Comment by cmgorton** [comment] 2021-09-09 16:54
I am going to close this issue since we are moving to deprecate connect. 
[Deprecating Connect Chat](https://forem.dev/foremteam/deprecating-connect-chat-2kgi)

**Closed by cmgorton** 2021-09-09 16:54 UTC
Labels: bug, area: notifications, area: connect
