### ISSUE TITLE
Link unfolding links to incorrect destination in private chat

### ISSUE THREAD

**Issue by sivaraam** [forem/forem#5674] opened 2020-01-23 18:36 UTC
**Describe the bug**
I recently tied to link to the following page in a private chat:

https://dev.to/thepracticaldev/welcome-thread-v44-3n39/comments

The link was unfolded in the rendered message and tapping on the link preview opens the following page:

https://dev.to/thepracticaldev/welcome-thread-v44-3n39

which is the blog page for the original comments page.

**To Reproduce**
1. Get a link to a comments page of a DEV post ([example](https://dev.to/thepracticaldev/welcome-thread-v44-3n39/comments))
2. Post the comments link in a private chat comment
3. Tap on the link preview corresponding to the comments link in the just posted comment.

**Expected behavior**
The link opens the comments page of the DEV post.

**Actual behavior**
The link opens the DEV post page.

**Desktop (please complete the following information):**

- OS: Lubuntu 18.04
- Browser: Firefox
- Version: 72.0.1

**Comment by cmgorton** [comment] 2021-01-28 14:50
Hey @sivaraam . I just tested this out and I was not able to reproduce this bug. I was able to send a comment link in private chat and it went to the correct link when clicked. I am going to close this issue but please let me know if it is still persisting for you. Thanks!

**Closed by cmgorton** 2021-01-28 14:50 UTC
Labels: area: connect, bug
