### ISSUE TITLE
Recent Comments section in User profile is not linked to either user’s comments or related article

### ISSUE THREAD

**Issue by crisbnp** [forem/forem#12990] opened 2021-03-14 01:22 UTC
**Describe the bug**

Recent comments section of a user profile which lists out recent comments a user has left on an article is not linked to the relevant article or the user's comment. It takes you to a page with header and footer.

**To Reproduce**

1. Go to a user profile
2. Scroll down to Recent Comments section
3. Click on an article where the user has commented
4. Note the bug - the link takes you to a page showing header and footer with no content.

**Expected behavior**

I expected to see the full article that the user has commented and the ability to scroll down to the end of the article to read comments.

**Screenshots**

![image](https://user-images.githubusercontent.com/42753366/111054334-c19f3f80-8463-11eb-95ca-a6e25af69fdb.png)

![image](https://user-images.githubusercontent.com/42753366/111054339-c7952080-8463-11eb-8f83-8eed2ff678c0.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: iOS
- OS, version: 14.4
- Browser, version: Safari

**Additional context**

**Comment by citizen428** [comment] 2021-03-15 03:54
Thanks for the report @crisbnp, but I wasn't able to reproduce this. We had some service worker issues lately, so can you please do a hard refresh and see if you still experience this problem?

**Comment by crisbnp** [comment] 2021-03-15 07:36
Hi, I can't do a hard refresh on iOS on the phone. What I did do was clear history and website data and I am still experiencing the same problem. 

I did a little bit more digging. I tried to reproduce the issue using my husband's phone - not logged in and logged in to my account, I could not reproduce the issue there. I did a bit more digging and it may have something to do with content blocker app that I've got installed called Distilled. 

The strange thing is that Distilled is also installed on my husbands phone and turned on. I could not reproduce problems there but I am still experiencing the problems with Distilled turned on. When it is turned off, I can see that it works. 

Thanks for looking into it!

**Comment by citizen428** [comment] 2021-03-16 01:47
Hmm, that's very interesting, thanks for the extra context @crisbnp!

**Comment by atsmith813** [comment] 2021-05-12 16:26
I'm unable to reproduce this either and I haven't seen additional reports of this issue. It's likely that it's the content blocker not liking how that page is rendered. Should we close this issue for now?

cc: @citizen428 @cmgorton @crisbnp

**Closed** 2021-05-12 18:33 UTC
Labels: Forem team, area: profile, bug, size:XS, tech: frontend
