### ISSUE TITLE
Can't upload images to my posts

### ISSUE THREAD

**Issue by jfbrennan** [forem/forem#12754] opened 2021-02-19 22:13 UTC
**Describe the bug**

When writing a post I try to upload an image it fails and says "The operation couldn’t be completed. Protocol error". This happens for regular image uploads and the cover image and seems to only be a Safari thing.

**To Reproduce**

Create or edit a post, try to upload an image or cover image. It will quickly fail.

**Expected behavior**

I can upload an image.

**Desktop (please complete the following information):**

- OS, version: macOS, 10.15.4 (19E287)
- Browser, version: Safari, 13.1 (15609.1.20.111.8

**Additional context**

This used to work. Seems to be a regression in the last week or two.

**Comment by rhymes** [comment] 2021-02-20 15:31
Hi @jfbrennan, thanks for the heads up! I tried but I'm able to upload images to DEV, could you provide us with the image you're trying to upload?

**Comment by cmgorton** [comment] 2021-02-22 14:28
Same for me. I was able to upload images in both the v1 and v2 editors on Safari.

**Comment by cmgorton** [comment] 2021-02-24 19:48
Hey @jfbrennan since this doesn't currently seem reproducible I am going to close this issue. If it is still happening for you can you please provide us with the image you're trying to upload and we can reopen this issue. Thanks!

**Closed by cmgorton** 2021-02-24 19:48 UTC
