### ISSUE TITLE
Blocking user in mobile Chrome does not work

### ISSUE THREAD

**Issue by ackava** [forem/forem#5622] opened 2020-01-21 03:44 UTC
I was trying to block a user whose posts appear in non English and it flooded my feed. I am on iPhone 6s, iOS 13.3, using Chrome. 

I opened three dots besides profile of the user and I clicked “Block @user”, nothing happens. I tried three four times.

**Comment by vcapretz** [comment] 2020-01-22 15:34
I just tested on web (Google Chrome) and it's also not working, I tried understanding the problem so maybe I could send a PR and checking the console I see this error: 

![Screenshot 2020-01-22 at 16 32 40](https://user-images.githubusercontent.com/14620121/72907895-ff5b7900-3d34-11ea-8bb8-b37065f14248.png)

So maybe the pack is not being loaded at all, what can be the causes of it?

**Comment by cmgorton** [comment] 2021-01-22 20:16
Hey thanks for opening this issue but this looks to be a duplicate of issue #5342. I have alerted the team about this bug and will close this issue. Any further discussion on this can be added to #5342. Thanks!

**Closed by cmgorton** 2021-01-22 20:16 UTC
Labels: area: fighting abuse, bug
