### ISSUE TITLE
"Revert new changes" in the editor does not remove the body

### ISSUE THREAD

**Issue by rhymes** [forem/forem#13324] opened 2021-04-08 18:01 UTC
**Describe the bug**

In the editor: after having added a title, tags and the content if you click on "Revert new changes" and confirmed the popup, the editor will remove the title, the tags but not the content.

**To Reproduce**

1. go to https://dev.to/new
2. fill in the title, tags and add content in the body of the article
3. click "Revert new changes" at the bottom and confirm
4. the content is still there

**Expected behavior**

The content should be removed as well

**Desktop (please complete the following information):**

- OS, version: macOS Catalina
- Browser, version: Firefox 88beta

**Comment by nickytonline** [comment] 2021-04-08 18:10
This is related to the new mention autocomplete feature.

The mention autocomplete has two inputs that it toggles between, so most likely both are not being cleared.

An end to end test should be added for this to avoid future regressions of this functionality.

**Comment by nickytonline** [comment] 2021-04-12 19:17
I did a bit of digging and the article body is getting reset, but the state in the MentionAutocomplete component is not updating it's text, because the reset data is not being updated via the `setText` function from a `useState` hook. The input is not a [controlled input component](https://reactjs.org/docs/forms.html#controlled-components). Only the initial value of the article body is set from the parent. From there, the MentionAutoComplete is an [uncontrolled form input component](https://reactjs.org/docs/uncontrolled-components.html).

https://github.com/forem/forem/blob/24a865e81f6c5a77fc69d8fb9ba8eec6f7bee40b/app/javascript/crayons/MentionAutocompleteTextArea/MentionAutocompleteTextArea.jsx#L103-L105

**Comment by aitchiss** [comment] 2021-08-30 13:23
Closing this as I believe it was fixed in #13365

**Closed by aitchiss** 2021-08-30 13:23 UTC
Labels: bug, area: publishing experience, tech: javascript
