### ISSUE TITLE
DEV Pods feed not caching properly on Forem instance

### ISSUE THREAD

**Issue by SGGregory** [forem/forem#12142] opened 2021-01-05 23:17 UTC
**Describe the bug**

This bug seems to be fundamental DEV pods caching issue that manifests itself in three ways on a Forem instance:
1. When attempting to add multiple podcasts to a Forem during the configuration process, episodes get traded between the other show (i.e. episodes from one show are listed as property of the other show). 
2. When attempting to correct the error, it results in many blank episodes. 
3. There is no visible option to delete the ones that are misfiring, so when attempting to re-add the show and unpublish the erroneous ones, the error repeats itself AND the old, improperly loaded ones are still present, despite marking `publish` as `false`

**To Reproduce**

1. Follow the **Forem Admin guide** instructions to add a podcast to a new Forem instance
2. See properly-loaded podcast
3. Add another podcast
4. See traded episodes between two shows
5. Attempt to re-upload shows and mark old shows as false
6. See caching issue across four shows

**Expected behavior**

Following Forem admin guide and in-app guidelines, it should be possible to upload more than one podcast to a Forem instance properly and see all available episodes in the feed

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: macOS Cataline, v10.15.7
- Google Chrome: Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by Zhao-Andy** [comment] 2021-01-14 15:21
This is the strangest issue, and seems pretty hard to reproduce. I followed the steps to reproduce and unfortunately it didn't work. My first impression is that there was some issue where the two specific podcasts had similar data within their respective RSS feeds, and that might have cause some conflict when our podcast reading logic that made episodes swap between each other.

Going through the reproduction steps I felt like it was pretty painful for a Forem admin to add a podcast, and this area definitely needs a new look. Will write some thoughts here to be shared internally.

For now, closing this issue since it's too hard to reproduce! 😣

**Closed by Zhao-Andy** 2021-01-14 15:21 UTC
Labels: Forem team, bug, type: forem creation
