### ISSUE TITLE
Allow external media links to be rendered

### ISSUE THREAD

**Issue by abenettt** [forem/forem#10526] opened 2020-10-02 07:35 UTC
**Is your feature request related to a problem? Please describe.**
Forem allows users to embed images into their posts and comments but sometimes users just paste a link into their posts / comments so they are not rendered correctly.

**Describe the solution you'd like**
When rendering the post or comment in the frontend we can check all the standalone links for their content type by sending a `HEAD` request against the url, should it be a media link we wrap render the image.

**Describe alternatives you've considered**
Create a new liquid tag that allows embedding of external media, this might be a cleaner solution but would not allow older posts to render external images without updating them.

**Additional context**

**Comment by rhymes** [comment] 2020-10-02 08:46
I believe this is a duplicate of https://github.com/forem/forem/issues/6369 and https://github.com/forem/forem/issues/1445 if I understand the request correctly @abenettt

**Comment by cmgorton** [comment] 2020-11-16 20:10
Hey @abenettt !

Thank you so much for this issue! Since this appears to be a duplicate of the issues Rhymes mentioned #6369 and #1445, I am going to go ahead and close this issue. Thank you again for being a part of the Forem community! We couldn't do what we do without you!

If you feel like this is actually a separate issue feel free to open an issue again.

**Closed by cmgorton** 2020-11-16 20:10 UTC
