### ISSUE TITLE
Open Dyslexic font broken on DEV Community

### ISSUE THREAD

**Issue by LayZeeDK** [forem/forem#9617] opened 2020-08-03 21:38 UTC
**Describe the bug**

I have enjoyed the Open Dyslexic font for a while. A few months ago it stopped working.

**To Reproduce**

1. Pick "Open Dyslexic" font from Settings > UX.
2. Open any article.
3. Font used is not Open Dyslexic.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 64-bit
- Version: 84

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

I tried unregistering the service worker and clearing the site data. It didn't fix the issue.

**Comment by Ridhwana** [comment] 2020-08-04 08:07
This is a duplicate of https://github.com/forem/forem/issues/9194. If there is any more information on the issue, feel free to add it there.

**Closed by Ridhwana** 2020-08-04 08:07 UTC
Labels: accessibility, area: design, type: bug
