### ISSUE TITLE
Multiple users experiencing Apple ID sign up error "Invalid curve name"

### ISSUE THREAD

**Issue by ellativity** [forem/forem#14743] opened 2021-09-16 13:39 UTC
**Describe the bug**

Several users have contacted yo@dev.to due to experiencing this error using Apple ID sign up.

**To Reproduce**

1. Go to `https://dev.to/enter?state=new-user`
2. Click on `Sign up with Apple`
3. See error:

>Could not authenticate you from Apple because "Invalid curve name".
If you haven't created an account, we recommend signing up with social authentication below. If you haven't received your confirmation email yet, click here to resend it.
Contact yo@dev.to if you continue having trouble.

**Expected behavior**

Apple ID modal

**Screenshots**

![example error](https://user-images.githubusercontent.com/76786132/133621329-17622b4e-8551-4bb5-a3b8-1b187d00bd69.png)

**Desktop (please complete the following information):**

I was able to replicate this error on
- OS, version: macOS Big Sur 11.5.2
- Browser, version: Safari Version 14.1.2 (16611.3.10.1.6)

Although different users are experiencing this error running various browsers and OS

**Comment by djuber** [comment] 2021-09-17 12:42
@ellativity this was addressed by a configuration update for dev.to yesterday, and appears to have been a problem from 2021-09-09 to 2021-09-16 based on the logs. 

The root cause was suspected to be a formatting change during another update in the authentication settings (which submit a single form for all providers).

**Closed by djuber** 2021-09-17 12:42 UTC
