### ISSUE TITLE
Giant "code zoom" icon on mobile, freezing browser

### ISSUE THREAD

**Issue by pyricau** [forem/forem#11188] opened 2020-10-30 16:26 UTC
**Describe the bug**

I published a blog post that contains code: https://dev.to/pyricau/leak-detection-android-studio-vs-leakcanary-35j5

The first time I opened it on my phone (Android Pixel 4), I saw giant pictures that look like they were the "zoom" icon that appears on code blocks. I reloaded the page and the bug was gone.

Then someone posted a screenshot with the same bug on twitter: https://twitter.com/bernaferrari/status/1322004478585933825

![Eli0ERsXgAIGBoL](https://user-images.githubusercontent.com/557033/97730942-bf7aac80-1a91-11eb-90c9-5014dc6eaf29.jpg)

Then a colleague of mine slacked me:

> Your blog post froze my browser! Very weird, massive white corner graphics at the bottom of each code block.

**To Reproduce**

1. Go to https://dev.to/pyricau/leak-detection-android-studio-vs-leakcanary-35j5 with an Android device
2. ?? Either you have the bug or you don't. I'm not sure what caused this, I can't repro, but it happened to at least 3 people.

**Comment by AJuliette** [comment] 2020-11-07 21:38
There is an older issue signaling this problem, maybe you could group yours with their ? https://github.com/forem/forem/issues/11043

**Comment by rhymes** [comment] 2020-11-08 05:26
Thanks @AJuliette for catching this, @pyricau, I'm going to close this as a duplicate of https://github.com/forem/forem/issues/11043 - please feel free to add your entry over there

**Closed by rhymes** 2020-11-08 05:26 UTC
Labels: area: design, area: mobile, type: bug
