### ISSUE TITLE
Request: RTL support

### ISSUE THREAD

**Issue by KL13NT** [forem/forem#12917] opened 2021-03-05 21:02 UTC
Is there any plan to add RTL support? GitHub manages to render RTL content using html `<div dir="rtl">`. There are multiple ways to add this, if anyone's interested. 

Proper rendering with css `direction: rtl`: 

![image](https://user-images.githubusercontent.com/20807178/110173014-b2d2e000-7e06-11eb-8027-b06fed7d8743.png)

How dev.to renders it:

![image](https://user-images.githubusercontent.com/20807178/110173060-c716dd00-7e06-11eb-845d-329bca1edfa3.png)

**Comment by citizen428** [comment] 2021-03-08 02:14
@KL13NT Thanks for the issue! Support for right-to-left (RTL) languages would most likely be added as part of our wider I18n efforts but probably at a later stage due to potentially necessary styling changes, etc.. 

In the meantime, feel free to post your request on https://forem.dev/, which would help us gauge how many other users are potentially interested in this.

**Comment by rhymes** [comment] 2021-03-08 10:05
Adding this older issue as reference as well https://github.com/forem/forem/issues/1239

**Comment by cmgorton** [comment] 2021-03-08 14:24
Hey @KL13NT thank you for this request. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it.

Since this is already a duplicate of #1239 I am going to close this issue here. Thank you again for bringing it up!

**Closed by cmgorton** 2021-03-08 14:24 UTC
Labels: needs product

**Comment by KL13NT** [comment] 2021-03-10 06:22
I started a [discussion](https://forem.dev/kl13nt/request-rtl-support-56p8) on forem.dev for anyone interested in this issue in the future.
