### ISSUE TITLE
Delete a User's Profile Picture when Changed

### ISSUE THREAD

**Issue by mstruve** [forem/forem#11583] opened 2020-11-23 20:16 UTC
### Problem

When a user changes their profile picture we still keep the original picture on our servers rather than deleting it. Ideally we would like to delete the picture so no one can access it. 

### Possible Solution

1) When a user is saved check to see if the `profile_image` field has changed. If it has, fetch the old name which is tracked by ActiveRecord during the save and delete it from our image store via CarrierWave.
2) We could offer a check box to the user when updating the profile image if they would like the old one destroyed which is how [Carrierwave actually models it](https://github.com/carrierwaveuploader/carrierwave#removing-uploaded-files).
```erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <p>
    <label>My Avatar</label>
    <%= image_tag(@user.avatar_url) if @user.avatar? %>
    <%= f.file_field :avatar %>
  </p>

  <p>
    <label>
      <%= f.check_box :remove_avatar %>
      Remove avatar
    </label>
  </p>
<% end %>
```

**Comment by Zhao-Andy** [comment] 2021-04-07 01:36
After quite a slog of investigating, I've confirmed this happens by default with Carrierwave. What we don't delete is the cached image of it through our caching service (nginx/Cloudinary).

Closing this issue since the original description is for deleting from the storage service itself.

**Closed by Zhao-Andy** 2021-04-07 01:36 UTC
Labels: area: images, area: profile, potential RFC
