### ISSUE TITLE
Profile navigation menu doesn't close on selection and focused link flickers

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#12466] opened 2021-01-28 10:50 UTC
**Describe the bug**

The bug is particularly noticeable on mobile - I've added a recording below of the experience on Android.

When you click your profile image, a dropdown menu opens with navigation options. When you tap to make a selection, the new page loads and there is a very brief flicker where "Sign out" appears to be selected, then your original selection, then "Sign out" again. The menu doesn't close until the user taps their profile image again, which on mobile means a large portion of the screen is obscured. Tapping outside of the menu on mobile does not close the menu (but it does on desktop).

**To Reproduce**

- Open a forem instance on a mobile device
- Click the avatar in the top right
- Select 'Dashboard' from the dropdown
- Observe the flickering link focus and the menu still being visible
- Try to click away from the menu and note it doesn't dismiss

**Expected behavior**

I'm open to suggestions on the UX here but I would suggest either:

- When you make a selection from the menu, the dropdown closes (in terms of focus management, sending focus back to the avatar button that opened the menu)

or

- The menu stays open, but there's no strange flicker of focus on the "Sign out" link, and tapping outside of the menu on mobile closes the dropdown

**Screenshots**

![gif showing the reproduce steps and bug described above](https://user-images.githubusercontent.com/20773163/106128176-16f2ec00-6157-11eb-88a2-1166b046a0d5.gif)

**Desktop (please complete the following information):**

N/A - on desktop the dropdown stays open but there's no strange flicker of focus and clicking outside of the dropdown closes it.

**Smartphone (please complete the following information):**

Observed on:

- Device: Pixel 5
- OS, version: Android 11
- Browser, version: Chrome 88

NB: I've observed the same behaviour both in the PWA and in Chrome browser

**Additional context**

I think this was introduced in #11509 - Header navigation dropdown accessibility

**Comment by cmgorton** [comment] 2021-01-28 20:19
This happens when you click on the settings link too. Makes using the mobile version of DEV really annoying.

**Comment by cmgorton** [comment] 2021-02-10 14:55
This issue is still occurring on some iOS phones. It also happens on the hamburger menu on Android phones when logged out. Confirmed on Android by me. Confirmed on iOS by @katiedavis

**Comment by cmgorton** [comment] 2021-02-10 14:56
@mstruve should we put this back in the Engineering Planning Funnel?

**Comment by mstruve** [comment] 2021-02-10 15:21
> Confirmed on iOS

Is this the app or through the browser? We should make sure if we are re-adding this to the funnel that any new details are added. If this is through the app I would close this issue and make a new one since an app issue is separate from a browser mobile issue.

**Comment by cmgorton** [comment] 2021-02-10 15:29
After talking with the team, I am going to create a separate issue for the Android hamburger menu I mentioned above. 

@katiedavis can you confirm if you are using a browser or if you are using the separate DEV app?

**Comment by paulkaplan** [comment] 2021-02-16 13:51
I can confirm the profile dropdown does not close when clicking the settings menu item on iOS (14.4) in both safari and the app.

For what it's worth, the settings, dashboard, and reading list all keep the dropdown open. The "write a post" item doesn't, it closes the dropdown. Not sure if that's related to the autofocus on the input or how the navigation is being done.

**Closed** 2021-02-19 22:47 UTC
Labels: Forem team, mobile, size:XS, tech: frontend
