### ISSUE TITLE
Ignore tags

### ISSUE THREAD

**Issue by jjant** [forem/forem#10213] opened 2020-09-04 20:29 UTC
**Is your feature request related to a problem? Please describe.**

This is a feature request, I'd like to ignore tags. My feed is full of articles on topics I don't care about, and they clutter content I'm actually interested in.

**Describe the solution you'd like**
Add an option to select tags you'd like not to show up in your feed.

**Describe alternatives you've considered**

A dual alternative would be to only show stuff I'm interested in, but this is more restrictive and means I won't get to see stuff I don't know about (for example, I'm not interested in languages like javascript, or begginer-aimed posts, but I'd like to see trending articles on languages I don't know about).

**Comment by rhymes** [comment] 2020-09-06 06:57
Hi @jjant thanks for the feature request, I'm closing this as a duplicate of https://github.com/forem/forem/issues/1856 - please copy your comment there so we can keep track of it and it contributes to the conversation. Thank you!

**Closed by rhymes** 2020-09-06 06:57 UTC
Labels: area: tags, type: feature request
