### ISSUE TITLE
Post editor not responsive on mobile viewport

### ISSUE THREAD

**Issue by maureento8888** [forem/forem#11230] opened 2020-11-02 14:37 UTC
**Describe the bug**

**To Reproduce**

Go to dev.to on Safari in iPhone X

Click on Profile > Dashboard

Scroll to a given post > “Edit” post

Cover image set for post is cut off slightly at bottom margin. Most importantly, the textarea is not scrollable to easily edit content markdown. Unable to freely scroll content. Need to hold cursor and drag to bottom edge of textarea just right so it doesn’t scroll too fast across content to get to section I need to edit.

**Expected behavior**

The post content should be editable and scrollable without the need to hold-and-scroll (iOS gesture)

**Screenshots**

![7F4FF02A-E4D4-421C-B94E-288C420CB177](https://user-images.githubusercontent.com/51500550/97879762-59d72c00-1cee-11eb-911d-614892354280.png)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS, version: iOS, 14.1
- Browser, version: Safari, n/a

**Additional context**

If it helps, just like GitHub does for markdown content like in these types of textarea, the content is freely scrollable in focus without needing to move the cursor to drag.

**Comment by fdoxyz** [comment] 2020-11-02 15:01
This is a bit odd as I wasn't able to reproduce the title problem from Safari (or Chrome) using an iPhone 11 on iOS 14.1

https://share.getcloudapp.com/QwukoAPp

We are definitely losing the ability to interact with the buttons at the very bottom of the screen (save changes and publish in case the post is a draft)

**Comment by ludwiczakpawel** [comment] 2021-01-11 09:54
Does this still happen?

**Comment by fdoxyz** [comment] 2021-01-11 15:33
@ludwiczakpawel I'm not able to reproduce the title being cut short or the problem in the Post body making it unable to scroll. Also given that #12113 streamlined the server vs client rendered view I think it's safe to say this problem was fixed.

The only problem I still see is in the far bottom/upper sections where a double scroll makes it a bit more difficult to reach (buttons). This is my experience in Safari with iOS 14.2

https://share.getcloudapp.com/2Nu0DJK1

I'll let you have the final say on whether this is still a problem (to be tracked in this or a new issue), or if it's okay to close this altogether.

**Comment by maureento8888** [comment] 2021-01-11 16:06
Hi, thank you for responding. It seems that I had viewed the post through Gmail’s browser and hence, when I moved to Safari, the problem went away? I suppose we can close this!

**Closed** 2021-01-11 16:46 UTC
Labels: area: design, area: mobile, area: publishing experience, tech: html/css, type: bug
