### ISSUE TITLE
Styling on rendered podcast liquid tags when browsing in light mode

### ISSUE THREAD

**Issue by GaProgMan** [forem/forem#3588] opened 2019-07-30 22:29 UTC
**Describe the bug**

When a post uses the podcast liquid tag:

```
{% podcast url-for-episode-here %}
```

and it is viewed in light mode (i.e. dark mode is disabled), the styling on the rendered podcast component means that the component cannot be seen - white text on a white background. Please see the Screenshots section for a visual on this issue.

**To Reproduce**

1. Ensure that you are using dev.to in light mode
1. Open the following url in a chrome-based browser or Firefox: [https://dev.to/dotnetcoreblog/the-net-core-podcast-episode-30-reflections-on-net-with-pablo-santos-and-phil-haack-257e](https://dev.to/dotnetcoreblog/the-net-core-podcast-episode-30-reflections-on-net-with-pablo-santos-and-phil-haack-257e)
1. Scroll down to the rendered podcast liquid tag; it will be displayed with white text on a white background
1. Swap to dark mode for dev.to
1. Refresh the page (may not be necessary)
1. Scroll down to the rendered podcast liquid tag; it will be displayed with white text on a dark background.

**Alternate steps to reproduce**

1. Create a dev.to article which contains a podcast liquid tag similar to the following: `{% podcast https://dev.to/dotnetcorepodcast/reflections-on-net-with-pablo-santos-and-phil-haack %}`
1. Preview the post in light mode; the podcast liquid tag will be rendered as white text on a white background
1. Preview the post in dark mode; the podcast liquid tag will be rendered as white text on a dark background.

**Expected behavior**

The rendered podcast liquid tag-based component does not have white text on a dark background when the page is viewed in light mode. There should be sufficient contrast such that the text and controls are easy to see and interact with.

The fix should not affect behaviour in dark mode.

**Screenshots**

In light mode:
![styling on podcast liquid tags light mode](https://user-images.githubusercontent.com/1607732/62169427-1427f880-b320-11e9-99d2-e9899cf89b43.jpg)

the same component, when viewed in dark mode:
![styling on podcast liquid tags dark mode](https://user-images.githubusercontent.com/1607732/62169498-49cce180-b320-11e9-95c4-fffe8e3f26e5.jpg)
**Desktop:**

- OS: Pop!Os 19.04
- Browser: Brave & Firefox
- Version: Brave 0.66.101 - Chromium 75.0.3770.142 (Official Build) (64-bit); Firefox 68.01

Output from `lsb_release -a`:

``` bash
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.04
Release:	19.04
Codename:	disco
```

**Comment by jordykoppen** [comment] 2019-08-02 21:56
Thanks! I created a PR for it. My first contribution to dev.to 😄

**Comment by benhalpern** [comment] 2019-08-18 18:55
I actually discovered that the issue is that we have "background patterns" on podcasts which are not always set correctly and if not, we get this situation of white on white.

The issue is actually ultimately with our podcast _validation_ where we allow podcasts to have inaccurate details.

@jordykoppen I closed your PR, because the issue is actually a bit different and related to invalid entries which shouldn't be allowed. I think the best solution is to make the validations more strict.

And one deeper yak shave. Currently we take the "color hex" for podcasts without the pound, and elsewhere we include the pound symbol to start. This inconsistency has been nagging, but if it's changed in the data it would need to also change in the view. That's just a note. If we were to make it accurate everywhere (or create a scenario where the view could take _with or without_ a pound symbol for now, that would also be nice.

**Comment by mrsantons** [comment] 2020-10-01 00:06
Could I claim this?

**Comment by nickytonline** [comment] 2020-10-01 00:10
I’ve assigned this to you @mrsanton. Happy Hacktoberfest Eve!

**Comment by cmgorton** [comment] 2021-03-23 15:34
Hey @mrsantons is this an issue you are still working on?

**Comment by oryanmoshe** [comment] 2021-05-05 09:30
Can't reproduce.
Was it solved already?

**Comment by cmgorton** [comment] 2021-05-05 13:11
I am going to try to reproduce with some other podcasts. I know at least as far as a few weeks ago this was still an issue. If I can reproduce it did you want to be assigned to it @oryanmoshe ?

**Comment by cmgorton** [comment] 2021-05-05 15:41
While trying to reproduce this I found a new bug instead. Created an issue here https://github.com/forem/forem/issues/13667

Added it to the bug smash list if anyone wants to work on it. I am going to go a head and close this issue since it is no longer reproducible.

**Closed** 2021-05-05 15:41 UTC
Labels: area: themes, bug, bug smash, good first issue, ready for dev
