### ISSUE TITLE
Twitter liquid tag buttons misaligned

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#12884] opened 2021-03-03 17:12 UTC
**Describe the bug**

When using a Twitter liquid tag, the "engagement" icons (the like/retweet/reply buttons below the tweet) content overflow out of the bounding box that contains them. This might be related directly to https://github.com/forem/forem/issues/12772, but since that issue is more broad, I am opening this issue to specifically focus on the twitter engagement icons so that the bug related to these icons in particular is documented.

Please note that this happens in both preview and draft/published mode:
<img width="946" alt="Screen Shot 2021-03-03 at 9 02 56 AM" src="https://user-images.githubusercontent.com/6921610/109843829-5bfbb980-7c00-11eb-826e-736a5fd17d69.png">

<img width="847" alt="Screen Shot 2021-03-03 at 9 03 12 AM" src="https://user-images.githubusercontent.com/6921610/109843818-59995f80-7c00-11eb-8dd8-501eb2722fb5.png">

**To Reproduce**

Use the Twitter liquid tag embed in any post on Forem. Preview the post or publish/save as a draft. You'll see this bug in both instances.

**Expected behavior**

These buttons should not overflow from the box -- they should be contained within them :)

**Comment by omkz** [comment] 2021-03-03 17:26
Hi @vaidehijoshi, I am interested in fixing this issue.

**Comment by cmgorton** [comment] 2021-03-03 17:46
Hey @omkz it looks like this is a duplicate of #12519 which has already been assigned to someone. You can keep an eye on that issue and see if the contributor is still working on the issue. Thanks!


@vaidehijoshi since this is a duplicate I am going to close this one here.

**Closed by cmgorton** 2021-03-03 17:46 UTC

**Comment by vaidehijoshi** [comment] 2021-03-03 19:45
Ah, thanks @cmgorton! Didn't realize that we had a specific issue for the action buttons already :)
