### ISSUE TITLE
Published date does not update after unpublish/re-publish

### ISSUE THREAD

**Issue by jennapederson** [forem/forem#5934] opened 2020-02-06 15:01 UTC
**Describe the bug**

The `published_at` date/time does not get reset after a post is unpublished and then later re-published.

**To Reproduce**

1. Create and publish a new post.
1. Note the `Article.published_at` or check the time element in the HTML of the published for `itemprop=datePublished` (correct at this point)
1. Go to Edit the post
1. Press the `...` in the header to get to Additional Config/Settings
1. Press Unpublish Post button
1. Republish the post by going back to Edit and then press Publish button at the bottom of the page
1. 1. Note the `Article.published_at` or check the time element in the HTML of the published for `itemprop=datePublished` (incorrect - the date/time has not changed)

**Expected behavior**

I expect that after unpublishing and republishing, the date is updated to the new publish date.

I had accidentally pressed the publish button thinking I could schedule a post in the future and it published it. I unpublished it thinking when I went to publish it the next day that it would have the correct date reflected.

**Screenshots**

![image](https://user-images.githubusercontent.com/552757/73948126-30ec4c80-48be-11ea-8b5c-9734abb4316e.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser: Chrome
- Version: 79.0.3945.130

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Note that this is different than editing an already published post where the `Article.published_at` should not be updated (currently working).

Two possible solutions:
1. Adjust this [line](https://github.com/thepracticaldev/dev.to/blob/bae7ee8b73231629498e47650b661f1d3c021c52/app/models/article.rb#L622) to also set `published_at` when it was not `published` but now is `published` regardless of whether `published_at` was set.
1. Unset `published_at` when article is updated and not `published`.

**Comment by maestromac** [comment] 2020-02-11 23:09
Thanks for this issue @jennapederson ! Technically speaking, this is working as intended. Something we might want to avoid is letting a user accidentally re-publish an old (1 year+) article. Perhaps @benhalpern have better idea of this.

**Comment by mstruve** [comment] 2020-11-08 17:01
As @maestromac mentioned, this is working as intended. The idea here is that we don't want people to unpublish/republish older content to boost it back to the top of the feed and suddenly show up in the latest feed when the article might have been written a year ago. For this reason, I am going to go ahead and close this issue. 

If this problem occurs in the future, please don't hesitate to reach out to yo@dev.to for assistance to fix your article published date. 

Please let me know if that makes sense or if you have any questions. Thanks so much for being a part of the Forem community!!!

**Closed by mstruve** 2020-11-08 17:01 UTC
Labels: tech: ruby, type: bug, type: discussion
