### ISSUE TITLE
Posts series within an org not taken into account when published by a different author

### ISSUE THREAD

**Issue by buinauskas** [forem/forem#15857] opened 2021-12-22 07:06 UTC
Apologies if this has been raised and closed in the past.

A post considered not to be part of the series within an org when published by a different person. Consider these two:
- https://dev.to/vinted/vinted-search-scaling-chapter-3-elasticsearch-index-management-3jb5
- https://dev.to/vinted/vinted-search-scaling-chapter-4-query-log-1me0

Both of these posts are under the same series, but one of these is not part of the series due to a different author.

Are series limited by a single person who started it or perhaps it could be considered org-wide as well?

**Comment by djuber** [comment] 2021-12-22 16:02
@buinauskas Thanks for the report. I can reproduce this locally. I'm not sure if it's been reported before (I'll check for closed issues).

Steps to recreate in a local environment:

- as user 1 create an organization
- as user 1, create two posts in a series (either selecting the hexagon to expose the series name, or by setting a series: attribute in the front matter, depends on your editor version)
- as user 2, join the organization
- as user 2, author a post in the series
- view the series, it has 2 (not 3) articles, and belongs to user 1 (the url of the series will be /user_1/series/:series_id, in my case this was http://localhost:3000/admin_mcadmin/series/2)
- view the organization and confirm all three posts were present

Checking the db/console, it looks like the _post_ is assigned to the organization when the organization is set by the author, but the _series_ is assigned to the user only (and not to the organization).

The Collection model in the code supports assignment of an organization, but checking DEV's data I see only one series (out of 14,000+) that includes an organization, which may have been manually set by our team. That series contains no articles so that might have been a failed test to do the same thing you're trying to do here. 

My suspicion before looking into the code much is that something like this is happening: 
- series are being created when saving a post but assigned to the post author
- posts are being assigned both a user/author and an organization
- posts submitted with the same series tag but another author are having the series ignored (it's not found, and not created)

The [article creation](https://github.com/forem/forem/blob/main/app/services/articles/creator.rb#L61-L65) code looks like it's related (the `Collection.find_series(series, user)` call is passing the user, not the organization), and the [find_series](https://github.com/forem/forem/blob/main/app/models/collection.rb#L12-L14) implementation is blind to organizations. 

The [Articles::Attributes](https://github.com/forem/forem/blob/main/app/services/articles/attributes.rb#L24-L27) code is only used for updates (not creation) but does have a lookup very similar to the creator method.

I suspect a fix for this (assuming it's expected that a series can belong to the organization when the author assigned the post to the organization) is that Collection's `find_series` method should accept an optional organization, and leverage that when creating and looking up series by name. It's possible there's more room for confusion that not and that fully determining the right way to do this may take more team input on our side. For example, if the user has an existing series, and authors a single post for the organization in that series, should the series name be ignored (not added to the authors series, but yes added to the organizations posts), or the series be added to the organization, after which other members of the organization can add to the series?

It's possible that the "belongs to organization" functionality of collections/series was never fully fleshed out, Ben's original description of the release in https://dev.to/ben/changelog-create-series-of-posts-4o63 indicates it was built into the model, but had no UI support, and it may have been incompletely specified, especially with respect to Organizations but added as-is at the time to provide more functionality.

**Comment by djuber** [comment] 2021-12-22 16:15
One supporting idea that "series can't really belong to organizations, even if they're associated with them" is that (1) Collections belong to a user (always) but may belong to an organization (optional),  (2) the CollectionsController looks up the series by the user name (and there's no way to look at an organization's series).

Additionally, it looks like the second contributor created their own series with the same name (names aren't globally unique, only unique per user), 

It does look _possible_ in theory to cross post onto another user's series, but when I tried to just assign the collection_id to the user_2 article in the back end, a validation blocked the change:

```
 @errors=
  [#<ActiveModel::Error attribute=collection_id, type=must be one you have permission to post to, options={}>]>
```

That comes from https://github.com/forem/forem/blob/main/app/models/article.rb#L686-L690 and explicitly checks the user id:

```ruby
  def validate_collection_permission
    return unless collection && collection.user_id != user_id

    errors.add(:collection_id, "must be one you have permission to post to")
  end
```

My current feeling understanding is series belong to users, not organizations, and it would be a larger change than just looking up by organization id when saving a post to overcome that. 

This does feel underdocumented (the organization/author distinction in the editor looks very well supported, the series name is a little tucked away in the settings, and the interaction between them appears to be unclear, and in your case surprising).

**Comment by djuber** [comment] 2021-12-22 16:20
https://github.com/forem/forem/discussions/15320 it looks like we have a feature request that effectively covers the same ground (not organization centric, but "allow two users to contribute to one series"). 

I'm going to close this in favor of the existing discussion about this feature request, for the moment it looks like this is not possible.

**Closed by djuber** 2021-12-22 16:20 UTC
