### ISSUE TITLE
Image vertical align problem on many liquid tags

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12772] opened 2021-02-22 19:47 UTC
**Describe the bug**

Image line heights or vertical align are messed up across liquid tags in general.

**To Reproduce**

Visit a post with liquid tags like github or tweets

**Expected behavior**

Images should be aligned with text in general. You'll know it when you see it.

**Screenshots**

<img width="576" alt="Screen Shot 2021-02-22 at 2 13 57 PM" src="https://user-images.githubusercontent.com/3102842/108757723-368ff100-7518-11eb-8d3d-dc4bbb2ce978.png">

<img width="667" alt="Screen Shot 2021-02-22 at 2 14 24 PM" src="https://user-images.githubusercontent.com/3102842/108757761-4576a380-7518-11eb-93f7-04680f39e5f3.png">

**Comment by vaidehijoshi** [comment] 2021-03-05 23:41
@cmgorton I think that between https://github.com/forem/forem/issues/12519 and https://github.com/forem/forem/pull/12836...this issue will be covered by 2 different members of the community?

If I'm understanding that correctly, should we remove this from our cycle work and take the `Forem team` tag off of it? 🤔 Let me know if I'm missed something!

**Comment by cmgorton** [comment] 2021-03-05 23:58
This was picked up by someone in the community but they decided they were not comfortable sign the cla. So another community member picked it up. So in short, yes the Forem team label can be removed.

**Comment by vaidehijoshi** [comment] 2021-03-23 17:15
@cmgorton From what I can tell, this has been resolved. Here are some screenshots of me testing this out on DEV, and the alignment issue on twitter + github liquid tags no longer seems to be reproducible:

<img width="915" alt="Screen Shot 2021-03-23 at 10 13 25 AM" src="https://user-images.githubusercontent.com/6921610/112188800-8d90f080-8bc0-11eb-96ff-3b59ff3005ce.png">
<img width="930" alt="Screen Shot 2021-03-23 at 10 13 43 AM" src="https://user-images.githubusercontent.com/6921610/112188810-8ff34a80-8bc0-11eb-94da-1d6fcb6fffc2.png">

**Comment by cmgorton** [comment] 2021-03-23 17:18
Awesome. I am going to go a head and close this issue then. Thanks for testing it @vaidehijoshi

**Closed by cmgorton** 2021-03-23 17:18 UTC
Labels: area: liquid tags, bug, size:XS, tech: frontend
