### ISSUE TITLE
Unavoidable connect notification badge

### ISSUE THREAD

**Issue by 4lch4** [forem/forem#1210] opened 2018-11-28 03:28 UTC
**Describe the bug**
No matter where I go on the site or what I do, there's a notification badge as if I have an unread message in the **Connect** feature:

![Image_1](https://thepracticaldev.s3.amazonaws.com/i/t0z6r5tzzqc1i9zuwvl7.png)

**To Reproduce**
I'm not certain these steps will reproduce it but after my investigation into the bug [with some help from @benhalpern][0]:

1. Join a group like the group for mentors.
2. When there is a notification badge like above, leave the group.

**Expected behavior**
I'd expect for me to go to the Connect page and there be a message, if not, then there should be no notification badge.

**Screenshots**
I posted a screenshot of what I'm actually seeing above, but here's a screenshot of what I see after I click on the button and go to the Connect page:
![Test2](https://i.imgur.com/7deJ6uV.png)

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Pro build number 17134
- Browser: Chrome 
- Version: 70.0.3538.102 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
Ben initially suggested going to `/chat_channels?state=unopened` to locate the culprit and it appears the Mentors groups channel is what's causing it:

```
[
  {
    "id": 31201,
    "slug": "mentors",
    "channel_name": "Mentors",
    "channel_type": "invite_only",
    "last_opened_at": "2018-10-13T03:27:22.619Z",
    "last_message_at": "2018-11-18T15:16:00.595Z",
    "adjusted_slug": "mentors",
    "membership_id": 79646,
    "description": "Chat amonst mentors"
  }
]
```

Also, I don't recall this happening when I first reported this issue but when I click on the button with the notification (to go to Connect, I'm not sure how to phrase it) it directs me to `dev.to/connect/mentors` which is empty. You can see the results of this in the 2nd screenshot I attached above.

[0]: https://dev.to/ben/comment/6npm

**Comment by Zhao-Andy** [comment] 2018-11-29 16:39
I think the issue that you left the channel but didn't get a chance to clear the notifications before you left. Not sure if we're handling this already, but we should mark all messages read when a person leaves a channel.

I've updated your individual read receipts in the Mentors channel and marked them as read.

**Comment by Alcha** [comment] 2018-11-30 00:33
Thank you so much @Zhao-Andy! I've had this notification for a couple months now it feels so I'm glad to be rid of it 😅

If was comfortable enough with the codebase I'd take a crack at this myself but I think I'd do more harm than good. That said, I'll still tinker with it to see if I can't get anything working and submit a PR if so.

Otherwise, if anyone else wants to fix this then don't stop on my account.

**Comment by Alcha** [comment] 2018-12-06 20:05
Hey @Zhao-Andy, sorry for the ping, but the badge is back.

To verify this wasn't an issue with cookies or cached data in Chrome, I installed Firefox and logged in there to see if the badge would appear and it has:

![Badge_Image](https://lh3.googleusercontent.com/-EbafXK7QJGo/XAmAnUvgzeI/AAAAAAAAY50/3CIDG76tkFgZTjfNS_t26m5d-Fsf4Ug7ACHMYCw/s0/2018.12.06-20.03-1a.png)

You don't have to go out of your way to mark it as read again for me, especially if it's going to just pop back up again, I only wanted it noted just in case.

**Comment by Zhao-Andy** [comment] 2018-12-06 21:57
Oh great, that's good to know. Thanks for the heads up. I've cleared it again since the channel is a slow moving one anyway. 👍

**Comment by Alcha** [comment] 2018-12-08 02:01
Awesome, thank you much 😊

**Comment by benhalpern** [comment] 2019-01-10 23:02
This is a weird one. I'm surprised this is still an issue because I thought it had been dealt with. Hard to reproduce. We'll have some more bandwidth to get to the bottom of this in this quarter.

**Comment by Alcha** [comment] 2019-04-16 16:24
This issue is still present for me... I'ts not the end of the world, but I felt it important to note so the bot doesn't just close it and y'all think this has been resolved.

The best I can come up with reproducing it, I was in the mentors chat group and I received a message while in that group. I left the group without opening the message, and the badge has been there ever since.

**Comment by jmfayard** [comment] 2019-12-27 06:10
I have exactly the same issue @Zhao-Andy @4lch4 

I was in the Tag Moderators group and left it - because I don't like group chat that much. 

Now I have multiple times a day a fake chat notification. 

Here is my `/chat_channels?state=unopened` 

```json
[{"id":51923,"slug":"tag-moderators","channel_name":"Tag Moderators","channel_type":"invite_only","last_opened_at":"2019-12-18T14:36:43.187Z","last_message_at":"2019-12-24T16:49:02.093Z","adjusted_slug":"tag-moderators","membership_id":172646,"description":null}]
```

**Comment by Zhao-Andy** [comment] 2020-01-07 21:58
Hi @4lch4, so sorry for the delay, I've since updated your channel status. @jmfayard I've also fixed it for you.

Let me know if this still is an issue for either of you!

**Comment by 4lch4** [comment] 2020-01-08 07:24
Thanks @Zhao-Andy, it's gone! I appreciate it so much 😄

**Comment by rhymes** [comment] 2020-08-08 06:26
Closing this as I don't think it's still an issue. Let me know if I was wrong

**Closed by rhymes** 2020-08-08 06:26 UTC
Labels: area: notifications, ready for dev, tech: ruby, type: bug
