### ISSUE TITLE
Non-breaking lines in code snippet (breaks responsiveness)

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#15144] opened 2021-10-20 17:50 UTC
**Describe the bug**
There is a code snippet with a long url causing the width of the page to be greater than 100vw (on mobile)

**To Reproduce**

1. Go to https://dev.to/keshavs759/box-shadow-vs-drop-shadow-in-css-cep (on mobile)
2. See issue

**Expected behavior**

**Screenshots**
![Screenshot_20211020-184415.png](https://user-images.githubusercontent.com/3534427/138144339-82d848a4-6bbd-45f2-9ea2-5b53f68f3e85.png)

![Screenshot_20211020-184422.png](https://user-images.githubusercontent.com/3534427/138144355-c098b22c-f6d7-4095-8612-7c5c3a877091.png)

**Additional context**

I don't recall seeing this issue before so perhaps something has changed with snippets?

**Comment by aitchiss** [comment] 2022-01-18 12:58
This is an interesting one - I tried reproducing locally with the same code snippet, but with no luck, which makes me wonder if something has been corrected in the meantime 🤔 

One thing I notice is that the published post linked here has the code snippet wrapped in 

```html
<pre class="highlight html">
</pre>
```

When locally if I publish the same code snippet, it's wrapped in:

```html
<div class="highlight js-code-highlight">
  <pre class="highlight html">
    ...
  </pre>
</div>
```

The extra surrounding `div` is what allows the CSS to target `div.highlight .highlight` where `overflow: auto` is set and prevents the text extending beyond the container.

I'm not sure why the markdown parser didn't create the extra containing `div` when this post was saved, but I _think_ whatever caused it might now be resolved 🤔

**Comment by Link2Twenty** [comment] 2022-01-18 13:07
It looks like the user wrote the article without setting a language and then added it with an edit, not sure if that makes a difference.

**Comment by aitchiss** [comment] 2022-02-16 17:16
I'm going to go ahead and close this one, as I can't reproduce with the same markdown as in the original post where we noticed it (and I'm hopeful this means it's fixed).

If anyone spots it again we can open it back up! Thanks for your help investigating this one @Link2Twenty ❤️

**Closed by aitchiss** 2022-02-16 17:16 UTC
Labels: bug, area: publishing experience
