### ISSUE TITLE
Cannot Fetch API due to CORS error from Forem API

### ISSUE THREAD

**Issue by vatana7** [forem/forem#21228] opened 2024-08-24 17:18 UTC
**Describe the bug**
I cannot fetch data from forem api with api-key

**To Reproduce**
```javascript
await fetch("https://dev.to/api/articles/me", {
    headers: {
      "api-key": token
    },
    method:"GET",
    mode:"cors"
  }).then((res) => console.log(res));
```

**Expected behavior**
To be able to fetch data

**Screenshots**
<img width="764" alt="image" src="https://github.com/user-attachments/assets/0df4413a-73a0-41b1-8902-e7a93b0c5543">

**Desktop (please complete the following information):**

- OS, version: Mac Sonoma 14.5
- Browser, version: Version 127.0.6533.120 (Official Build) (arm64)

**Comment by Raushan998** [comment] 2024-08-24 17:32
Hey @vatana7 You can cors-proxy to resolve this. Attaching the some key reference for you.
https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347

**Comment by benhalpern** [comment] 2024-08-26 12:45
@vatana7 The endpoint you're listing should not be used on the frontend due to exposing your API key.

You can use non-key-dependant endpoints on the frontend. Use workarounds such as @Raushan998 described at your own risk. It is not advised.

I'll close this issue for now because this is expected behavior.

**Closed by benhalpern** 2024-08-26 12:45 UTC
Labels: bug

**Comment by vatana7** [comment] 2024-08-28 02:59
Thank you for your answer, appreciate it @benhalpern
