### ISSUE TITLE
API Images now blocked

### ISSUE THREAD

**Issue by wyattdave** [forem/forem#21295] opened 2024-09-27 16:56 UTC
**Describe the bug**
Ive been using the api to link back from my site but now all of the images are returning:
"This asset is blocked. Contact dev.to if this is a mistake."

**To Reproduce**
1. Navigate to "https://dev.to/api/articles/latest?username=wyattdave&per_page=3"
2. Open "cover_image"-"https://media.dev.to/cdn-cgi/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Fiyqm0ol7dr65gochkfbn.png"

**Expected behavior**

Image to load

**Screenshots**

![image response](https://github.com/user-attachments/assets/1e9d0736-3882-4418-b59f-637b188a8cbf)
![api response](https://github.com/user-attachments/assets/52f0385c-a4d0-4413-a207-ea4a9a4db14d)

**Desktop (please complete the following information):**

- Windows 11 (Arm)
- Chrome, Edge

**Smartphone (please complete the following information):**

- Android:
- 14
- Chrome

**Additional context**

**Comment by Theyashsawarkar** [comment] 2024-09-28 21:06
i am experiencing the same issue , i have been going mad about it . thank god i found this otherwise i would have kept doing non sensical things !!

**Comment by calumk** [comment] 2024-09-29 19:33
Duplicate of : https://github.com/forem/forem/issues/21292

**Closed** 2024-10-02 17:14 UTC
Labels: bug
