### ISSUE TITLE
Editor: Allow ad-hoc switching between ‘basic’ and ‘rich’

### ISSUE THREAD

**Issue by jhermann** [forem/forem#6763] opened 2020-03-21 23:22 UTC
From what I observed, the system remembers the global editor setting (UX › Writing) when you create a post. There is no way to change this afterwards (that I found). Changing the global setting has no effect on existing articles.

## Proposed feature
Place a switch to the *other* mode near the `Preview` button, possibly remembering the change for this article, or changing the global default each time. If the latter, definitely open *any* post according to that global setting (no per-post mode).

Another improvement would be to display the front matter in a text box when you open the "···" menu in the rich editor.

**Comment by rhymes** [comment] 2020-03-22 14:50
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment] 2020-03-22 14:56
A bit of context: the reason why the editor remembers which version one used for an article is that not all features of the `basic` editor are available in the `rich` editor (in the rich editor one can't change the publication date for example or the description).

The discussions in these two issues contain more context:

- https://github.com/thepracticaldev/dev.to/issues/4219
- https://github.com/thepracticaldev/dev.to/issues/2639

**Comment by cmgorton** [comment] 2021-01-22 21:36
Given that this is intended behavior due to the issues Rhymes mentioned above I am going to go a head and close this issue. If you would like to discuss it further you can open a post on [forem.dev](forem.dev)

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Closed by cmgorton** 2021-01-22 21:36 UTC
Labels: area: publishing experience, type: feature request
