### ISSUE TITLE
Inline code is vertically misaligned

### ISSUE THREAD

**Issue by GrahamBorland** [forem/forem#4579] opened 2019-10-24 16:39 UTC
**Describe the bug**

In the default theme, inline code appears a couple of pixels too low, relative to normal text.

**To Reproduce**

1. Write a post with some inline code snippets.
2. Preview the post.
3. Notice that the code snippets are visibly lower than the rest of the text.

**Expected behavior**

The inline code should be vertically aligned with the normal text.

**Screenshots**
![image](https://user-images.githubusercontent.com/5768767/67506549-29919200-f685-11e9-921d-ba863c8cb65a.png)

**Desktop (please complete the following information):**

- OS: macOS 10.14.6 (18G103)
- Browser: Chrome 
- Version: 78.0.3904.70 (Official Build) (64-bit)

**Comment by yogeshktm** [comment] 2021-01-07 11:15
Hey 

I don't see a issue here. since inline code requires highlighting it needs a 2 or 3px padding inside. It looks perfect for me in mac chrome.

screenshot:
<img width="1280" alt="Screenshot 2021-01-07 at 4 36 48 PM" src="https://user-images.githubusercontent.com/3961774/103885988-d4fdf980-5106-11eb-96c6-6a6bc84a1c4f.png">

    OS: macOS 10.14.6 (18G103)
    Browser: Chrome
    Version 87.0.4280.88 (Official Build) (x86_64)

i prefer we can close this as not a bug. Discussions are welcome.

**Comment by nickytonline** [comment] 2021-01-07 18:43
Thanks for filing the issue @GrahamBorland. I'm trying to replicate this on my Mac, but it seems fine.

![image](https://user-images.githubusercontent.com/833231/103930975-8ee86c00-50ed-11eb-927a-181050bdca09.png)

![image](https://user-images.githubusercontent.com/833231/103930915-79734200-50ed-11eb-99c3-5a19f42ef8ca.png)

Here's my specs
Chrome: Version 87.0.4280.88 (Official Build) (x86_64)
macOs: 10.15.7

I'm not on Mojave, so maybe that is a difference, but @yogeshktm appears to be on the same OS version as you without issues. I see you're on an older version of Chrome (78 from Oct. 2019). Maybe that's the differentiating factor.

**Comment by GrahamBorland** [comment] 2021-01-07 19:27
My Chrome was fully up to date when I reported the bug back in October 2019. 😆 

All seems fine now, so I agree this can be closed. Thanks!

**Closed** 2021-01-07 20:28 UTC
Labels: area: publishing experience, tech: html/css, type: bug
