### ISSUE TITLE
Copy-to-clipboard not working from sidebar

### ISSUE THREAD

**Issue by VarunBarad** [forem/forem#4545] opened 2019-10-22 14:04 UTC
**Describe the bug**
The "copy post link to clipboard" from the side bar is not working.

Tested on:
- Desktop (works)
- Mobile
- Android app

**To Reproduce**
1. Go to [https://dev.to/aleccool213/how-to-make-money-from-your-software-blog-without-hosting-ads-cjn](https://dev.to/aleccool213/how-to-make-money-from-your-software-blog-without-hosting-ads-cjn) (any article should work)
2. Click on `...` on the left-hand sidebar
3. That will open a menu
4. Click on the Article link presented there
5. It should copy the article link to clipboard but doesn't

**Expected behavior**
The url for the article shown should be copied to the clipboard.

**Current behavior**
The clipboard isn't affected at all.

**Smartphone (please complete the following information):**
- Device: OnePlus 6
- OS: Android Pie (9)
- Browser:
  - Firefox - Version 68.1.1
  - Google Chrome - Version 77.0.3865.116

**Additional context**
I tested it and it works on Google Chrome (Version - 77.0.3865.120) on Microsoft Windows.
**Edit:** For some reason it started working on Firefox on Windows after a PC restart 🤷‍♂ 

Following are related issues and PRs I found across this and the android app repository.
- [https://github.com/thepracticaldev/DEV-Android/issues/58](https://github.com/thepracticaldev/DEV-Android/issues/58)
- [https://github.com/thepracticaldev/DEV-Android/pull/60](https://github.com/thepracticaldev/DEV-Android/pull/60)
- #4543

**Comment by rhymes** [comment] 2019-10-22 14:26
Additional info: Firefox 70 and Chrome 77 on macOS 10.14.6 both work

**Comment by rclanan** [comment] 2019-10-22 22:13
I just tested this on a desktop:
* OS: Windows 10 Pro, version 1809, 64-bit
* Browsers: 
	- Firefox 69.0.3 - 64-bit
	- Firefox 70.0 - 64-bit

and it appears to be functioning properly.

**Comment by VarunBarad** [comment] 2019-10-23 03:19
For some reason it started working on Firefox on Windows after a system restart 🤷‍♂

**Comment by rclanan** [comment] 2019-10-23 04:50
When in doubt, restart! :)

**Comment by rhymes** [comment] 2019-10-23 12:12
I'm closing this since the OP verified the feature is working again!

**Comment by VarunBarad** [comment] 2019-10-23 17:19
It works only on desktop, still doesn't work on the mobile browsers as I originally mentioned.

**Comment by Zhao-Andy** [comment] 2019-10-23 17:37
Hmm, reproduced it on mobile... Will test in development.

**Comment by baneDD** [comment] 2019-10-23 19:19
Tested working in iOS on Safari 13.0, Chrome 77.0.3865.103, Brave 1.11.4 (19.08.29.21) and Firefox 19.1 (16203)

**Comment by rhymes** [comment] 2020-10-01 08:20
I think this has since been fixed now

**Closed by rhymes** 2020-10-01 08:20 UTC
Labels: ready for dev, tech: javascript, type: bug
