### ISSUE TITLE
Edit and Preview label issues when adding or editing a post

### ISSUE THREAD

**Issue by SandeepBalachandran** [forem/forem#10860] opened 2020-10-15 07:27 UTC
---
Name: Bug report
---

**Describe the bug**
The **Edit** and **Preview** labels multiply upon clicking on those simultaneously during  editing the post.

**To Reproduce**
* Go to write a post
* Click on **Preview** label either adding the content of the post or not. ( Now **Preview**  label  will  be changed to **PreviewPreview**)
* Click  on **Edit** label
* Again click on **Preview** label (Now **Edit** will be changed to **EditEdit**)

**Expected behavior**
* Only needs to show **Edit** and **Preview** labels once during any event.

**Screenshots**
[Screenshot](https://i.ibb.co/Kr5FhCz/bug.png)

**Desktop**

- OS: Windows 10 Home
- Browser: Google Chrome
- Version:85

**Additional context**
* If this issue is already submitted kindly close.
* Let me know the suggestions to improve bug reporting if i am missing something.

**Comment by akshayymahajan** [comment] 2020-10-17 04:38
Hey @SandeepBalachandran, I tried the steps that you mentioned but could not reproduce the issue.

**Comment by SandeepBalachandran** [comment] 2020-10-17 10:12
> Hey @SandeepBalachandran, I tried the steps that you mentioned but could not reproduce the issue.

Hi @akshayymahajan , I retested it and simultaneously clicked both labels .  The result is available  below.
  
[Screenshot](https://i.ibb.co/fD6JnMc/simultaneous.png)

Os, Browser, Version are the same mentioned earlier.

**Comment by akshayymahajan** [comment] 2020-10-19 08:52
I have been trying to reproduce on Chrome 86 on macOS 10.15.7 and this is the result

![2020-10-19 14 18 44](https://user-images.githubusercontent.com/8535863/96423013-65b6ee80-1216-11eb-98c0-282b3723a096.gif)

**Comment by SandeepBalachandran** [comment] 2020-10-19 13:08
That is  quite unfortunate . If that the case ,the bug has something to do with my client.
 
![chrome-capture](https://user-images.githubusercontent.com/17725953/96454562-a96f1f80-1239-11eb-923f-902b3b6f51e2.gif)

**Comment by ludwiczakpawel** [comment] 2021-01-11 09:29
@SandeepBalachandran does it still happen to you? Do you have any JS errors in console maybe?

**Comment by SandeepBalachandran** [comment] 2021-01-11 15:10
@ludwiczakpawel  Hi there, Checked again now. Nothing particularly  going on in console. In fact console is empty when triggering the events .

The elements section can be seen below for some reference

![image](https://user-images.githubusercontent.com/17725953/104198481-482ba680-544c-11eb-8456-3723e0fbd2ca.png)

**Comment by ludwiczakpawel** [comment] 2021-01-11 15:32
Hah, so that does still happen to you?! Oh my..

Can you maybe try to empty your cache?

**Comment by SandeepBalachandran** [comment] 2021-01-11 15:56
@ludwiczakpawel  One thing i noticed right now which I havent mentioned before, I have been using a different user directory for the  current session of the chrome.  When i switched to the default user directory ( The directory which set itself upon installation) things worked as intented. That seems like a good trace to track it down.

**Comment by ludwiczakpawel** [comment] 2021-01-11 16:48
What exactly do you mean by "user directory"?

**Comment by SandeepBalachandran** [comment] 2021-01-11 17:11
@ludwiczakpawel  Honestly i am not quite sure about how it is relevant and connected to our issue here. Let me know if there is any
#### User data directory
*  Default user data directory  can be overridden  by passing ```--user-data-dir```  command-line flag to the chrome binary followed by location in order to get our custom location for storing files.
* Reference - [Chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#overriding-the-user-data-directory)

**Comment by ludwiczakpawel** [comment] 2021-01-12 10:10
It's really weird. I'll keep investigating since I can't repro that on my local env 👀

**Comment by SandeepBalachandran** [comment] 2021-01-12 10:24
@ludwiczakpawel  Hoping that you have been trying to reproduce the issue in chrome the way i mentioned.

**Comment by ludwiczakpawel** [comment] 2021-01-12 10:34
After another thought... Since this is happening only when you manually and intentionally change User Dara Directory and you've confirmed it works for default one, I don't think we can consider this as an actual bug. 

User directory contains some cookies related data and likely other stuff that potentially could be important for some views (like `/new`) since some of them heavily rely on cache etc.

When users "customize" their default browser behavior (either by installing 3rd party plugins that affect sites rendering or overwriting some default settings) we (as a site) can't really control the outcome. We try to keep things as bullet-proof as possible but it's not always easy. And in some cases effort to make it bullet-proof is not worth it.

For this reason, I'm leaning towards closing this issue, but I'll keep the conversation open if you wanna add something in. 
Also, one last thing, you could try to clear your cache and/or cookies after switching to the different user directory. I hope it helps!

**Closed by ludwiczakpawel** 2021-01-12 10:34 UTC
Labels: area: design, area: publishing experience, type: bug

**Comment by SandeepBalachandran** [comment] 2021-01-12 10:56
I mean like i said before i am not sure whether this behaviour is  caused by altering data directory or not?  In my understanding changing directory does not affect anything other than location for the client.

**Have you reproduced  the behaviour in your side?**  I think we could confirm the reason if you / someone could reproduce.

I added the issue not to  increase the issue counter. It was out of curiosity. This behaviour (not calling issue or bug) is sitll there whether the thread is in a different state (open/close).   Still curious to know what was the culprit behind. Because as far as i remember other sites are not showing any strange behaviours while accessing from user data directory altered client.

As mentioned will update the status once i am able to check it in a cache / cookie cleared custom user data directory altered client.
