### ISSUE TITLE
Footer appears twice on dev.to for unauthenticated users

### ISSUE THREAD

**Issue by justin22** [forem/forem#9629] opened 2020-08-04 16:47 UTC
**Describe the bug**

Website footer appears twice, one below the other in some scenarios. 

**To Reproduce**

1. Go to homepage
2. Click on 'see all' for listings from the right side
3. In the listings page, click on create or manage actions. 
4. The login page will be the next, and there are 2 footers in the page

**Expected behavior**

1. There should be only 1 footer

**Screenshots**

![UN2XLVgk](https://user-images.githubusercontent.com/3507241/89320994-f5311480-d69f-11ea-9863-665f02995134.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Edge
- Version:

**Comment by rhymes** [comment] 2020-08-05 14:17
Hi @justin22, I can't reproduce, it might have been a temporary caching issues. Does it still happen for you?

**Comment by justin22** [comment] 2020-08-05 14:23
Yes, It sill happens. I tried in incognito now. 
Note: I do not have an account in dev.to, I'm trying as un-authenticated user.
Issue is on the page once landed, https://dev.to/listings/new. 
and if I try a hard refresh once I'm on this page, the footer appears only once. So may be caching issue.

**Comment by rhymes** [comment] 2020-08-05 14:53
@justin22 thanks for the tip! I can reproduce it now:

![double_footer](https://user-images.githubusercontent.com/146201/89427949-1d6e5100-d73c-11ea-955d-5fd2308fc1db.gif)

**Comment by sai-bhargav** [comment] 2020-08-07 05:52
Hey,

In `app/views/devise/registrations/_registration_form.html.erb:59` 
changing `<div style="height:300px" />` to `<div style="height:300px"></div>`  fixes the issue. 
wanted to check my understanding, because I'm not entirely sure why it seems to work.

my obervation so far is, self-closing tag for div is not a valid HTML format (from https://validator.w3.org/nu/). Since its an open tag, it searches for a closing tag giving it scope to render the footer page.

Do correct me if i'm wrong.

Note: My setup is running on older version(ruby 2.6.2 and node 12.13)

**Comment by rhymes** [comment] 2020-08-07 09:18
@sai-bhargav seems to be working for me, do you want to contribute a PR?

**Closed** 2020-08-07 13:07 UTC
Labels: area: caching, type: bug
