### ISSUE TITLE
Markdown code in a code block breaks the UI

### ISSUE THREAD

**Issue by bokovhu** [forem/forem#21280] opened 2024-09-12 11:28 UTC
**Describe the bug**

I tried to write Markdown code in an article. This example Markdown code happens to include a code block as well.

In GitHub Markdown, you can use more than three backticks, so that this issue can be evaded. On dev.to, it just breaks the UI.

**To Reproduce**

Try to post the following article text (or just preview it):

``````
It is absolutely a use-case to include _Markdown code_ inside a _code block_. For example, I could say you need to write your `README.md` file with the following content:

`````markdown
# Hello

This is a tutorial on how to use markdown.

Code blocks

```js
export default {}
```

`````

And then the whole article is bugged.
``````

**Expected behavior**

The longer backticked code block's beginning and end is matched correctly, so we can have code block in a markdown code block.

**Screenshots**

![forem-markdown-bug](https://github.com/user-attachments/assets/21b427b8-d8c5-412c-bb59-0e0005679af4)

**Desktop (please complete the following information):**

- OS, version: Windows 11
- Browser, version: Google Chrome, Version 128.0.6613.137 (Official Build) (64-bit)

**Comment by yousefmarey12** [comment] 2024-09-13 00:27
@bokovhu 

Hello, I will do whatever I can to work on this issue.

**Comment by yousefmarey12** [comment] 2024-09-15 17:37
@forem-team

I am 99% of where the problem is, but since I haven't worked with Ruby nor RegEx that much, it will take a bit of time to handle it. The problem is [here](https://github.com/forem/forem/blob/main/app/services/markdown_processor/parser.rb#L128).

```ruby
def escape_liquid_tags_in_codeblock(content)
      # Escape codeblocks, code spans, and inline code
      content.gsub(/[[:space:]]*~{3}.*?~{3}|[[:space:]]*`{3}.*?`{3}|`{2}.+?`{2}|`{1}.+?`{1}/m) do |codeblock|
        codeblock.gsub!("{% endraw %}", "{----% endraw %----}")
        codeblock.gsub!("{% raw %}", "{----% raw %----}")
        if codeblock.match?(/[[:space:]]*`{3}/)
          "\n{% raw %}\n#{codeblock}\n{% endraw %}\n"
        else
          "{% raw %}#{codeblock}{% endraw %}"
        end
      end
    end
```
The problem is that, it shouldn't be 3 ticks or tildes matches 3 ticks or tildes. It should be **at least** 3 ticks (N) matches the **at least** the same amount of ticks. I know there has to be a `{3,}` and not a `{3}`. However, `{3,}` is broad, meaning that 5 opening ticks can be paired with 4 closing ticks which is not correct. I don't know and I don't think that it's possible to write a regular expression of N opening ticks (not necessarily 3, but at least 3) ticks has **at least** N ticks. (I tried ChatGPTing it, but it failed). I would be open to any suggestions or if anyone wants to take it from here, that would be okay as well.

Thanks

**Comment by yousefmarey12** [comment] 2024-09-17 21:44
@bokovhu 

I [PRed](https://github.com/forem/forem/pull/21288) the problem in case you want to take a look at it.

**Closed** 2024-10-03 17:56 UTC
Labels: bug
