### ISSUE TITLE
WARNING required, while trying to navigate out of current page (or reload) while writing

### ISSUE THREAD

**Issue by dillionmegida** [forem/forem#4074] opened 2019-09-20 13:41 UTC
**Is your feature request related to a problem? Please describe.**
While writing an article (on mobile), I unintentionally clicked the DEV logo (which is also a link). This redirected me out of the page without a warning (like "you'll lose your current changes").

**Describe the solution you'd like**
Two solutions to this which I'd like is
- A warning alert which allows the user to decide whether to leave the page while writing or stay.
- An auto drafting feature which saves the article as the user writes and deletes the draft when the user publishes it.

Thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by Zhao-Andy** [comment] 2019-09-20 13:48
Thanks for the issue. We currently have autosave for drafts. If you leave the page, you should be able to navigate back to "WRITE A POST" (`/new`) or your draft post via your dashboard, and see your draft available in the editor.

Closing since this should be solved, but let us know if you have any questions!

**Comment by dillionmegida** [comment] 2019-09-20 13:58
I've tried this before and I just did it again.

I wrote testing, then clicked the dev logo. I went to my dashboard but didn't see it. I also clicked on Write Post, but I got a blank page.

**Comment by Zhao-Andy** [comment] 2019-09-20 13:59
Hmm alright. Could we get your device and browser information?

**Comment by dillionmegida** [comment] 2019-09-20 14:02
64-bit Operating System, Windows 10, Intel Pentium Processor

Google Chrome - Version 76.0.3809.132

**Comment by Glennmen** [comment] 2019-09-20 14:08
@Zhao-Andy I wanted to add that I am not seeing it in my dashboard (`/dashboard`) as a draft, but indeed it is still available when I go back to `/new`.

macOS 10.14.6
Brave Version 0.68.138 Chromium: 77.0.3865.75

**Comment by Zhao-Andy** [comment] 2019-09-20 14:16
Thanks @Glennmen :)

@dillionmegida I can't seem to reproduce on my Windows 10 Chrome browser. When visiting "WRITE A POST" (`/new`), it will autosave any changes you have made. Those changes will be kept in `/new` for you to revisit in that same browser session. Note that our autosave feature currently doesn't handle different sessions / new tabs all that well (see https://github.com/thepracticaldev/dev.to/issues/3670 for more info).

It won't create a new draft for you though. When you'd like to save the draft and have it available in any browser session (saved into database), you'll have to hit "SAVE DRAFT" to save an actual draft into your dashboard `/dashboard`.

Hope that explains the feature! Since I can't reproduce this, I'll be closing this issue. Let us know if you have any questions though.

**Comment by Glennmen** [comment] 2019-09-20 14:18
@Zhao-Andy In the original issue he said `on mobile` but when you asked his device information he said `Windows 10`, could it be storage handling on mobile browser?

**Comment by Zhao-Andy** [comment] 2019-09-20 14:19
Not sure, but I also tested on Android Chrome + iPhone Chrome and couldn't reproduce it.

**Comment by dillionmegida** [comment] 2019-09-20 15:08
Well, those are the issues I'm experiencing both on my mobile device and desktop browser.

However, my little contribution to Dev.to is to include a WARNING as stated above or an autosave for drafts. I'm always getting a blank page in /new.

I wrote an article and was just on the conclusion part when I mistakenly hit the DEV logo. I had to start afresh. 

I do hope my contribution is given due consideration.

**Comment by Zhao-Andy** [comment] 2019-09-20 15:58
I think that's fair. Do you mind leaving a screenshot or a gif of the issue? You can also email it to yo@dev.to if you'd like. My guess is that it might be a device specific issue.

**Comment by dillionmegida** [comment] 2019-09-21 20:53
I'm having issues loading a gif.

Since someone already confirmed the /new for  retrieving saved drafts, I guess that solves it. It's probably a device or network issue.

But my contribution still remains. I think a warning is more preferable to avoid network, device or any other issues.

**Comment by cmgorton** [comment] 2021-01-12 17:41
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!

**Closed by cmgorton** 2021-01-12 17:41 UTC
Labels: area: publishing experience, type: discussion, type: feature request
