### ISSUE TITLE
Profile sidebars overflow Header

### ISSUE THREAD

**Issue by madzadev** [forem/forem#11202] opened 2020-10-31 08:04 UTC
**Describe the bug**
Profile sidebars overflow header.

**To Reproduce**
Open any profile and scroll down.

**Expected behavior**
Header is at the top at all times. 

**Screenshots**
![111](https://user-images.githubusercontent.com/42511917/97774386-00d98d80-1b60-11eb-825b-0dffb006f4dc.gif)

**Desktop (please complete the following information):**

- OS, version: Win10, 64bit
- Browser, version: Chrome, 86.0.4240.111

**Comment by Shadow-Scientist** [comment] 2020-10-31 12:29
Yes. I also noticed it yesterday. It's overflowing even when I sign out.

![Signout](https://user-images.githubusercontent.com/61514752/97779219-deb72e00-1ba6-11eb-8c88-efe55335a545.png)

**Comment by zippytyro** [comment] 2020-10-31 15:02
Was about to open an issue about this.

**Comment by bntzio** [comment] 2020-10-31 15:49
There's the fix ^

**Comment by citizen428** [comment] 2020-11-02 04:32
Thanks @bntzio, I assigned you the issue so nobody else accidentally starts working on this.

**Comment by ludwiczakpawel** [comment] 2020-11-02 07:17
Hey @bntzio , we've reassigned this issue to be handled internally since its caused by some bigger code refactoring shipped recently and because it affects some broader plans for our frontend codebase we want to be sure its gonna be solved according to our plan. I hope you don't mind and I also really appreciate your contribution here!

**Comment by maximelafarie** [comment] 2020-11-02 09:43
I made a PR to fix this: #11222 🤘 The issue is explained in the PR 😉.

**Comment by rhymes** [comment] 2020-11-02 09:44
@maximelafarie I think the PR number is wrong 😊

**Comment by maximelafarie** [comment] 2020-11-02 09:45
Thank you @rhymes you're right! 😁 I edited it!

**Comment by ludwiczakpawel** [comment] 2020-11-02 09:47
hey @maximelafarie , thanks for contribution although this time we've decided to tackle this one internally by ourselves:

> its caused by some bigger code refactoring shipped recently and because it affects some broader plans for our frontend codebase we want to be sure its gonna be solved according to our plan. I hope you don't mind and I also really appreciate your contribution here!

Check #11229 .

**Comment by maximelafarie** [comment] 2020-11-02 09:50
Thank you for your answer @ludwiczakpawel! I'm so dumb I read your last comment too late! 😅 
Good luck buddies! 🖖

**Closed** 2020-11-02 10:07 UTC
Labels: Forem team, area: design, type: bug
