### ISSUE TITLE
[Mod] Can't send message, err Node

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#14372] opened 2021-07-28 00:21 UTC
**Describe the bug**
When you went to send a Sloan message (only Mod tool), a bug is apparear.

**To Reproduce**

1. Go to a random post
2. Send a Sloan message (or custom message?)
3. See the error

**Expected behavior**
No errors and redirect to the comment.

**Screenshots**
![IMG_20210728_021842.jpg](https://user-images.githubusercontent.com/14293805/127243858-d7a6f345-767f-43f8-96d0-a7e11ed2a2e8.jpg)

**Smartphone :**

- Device: Xiaomi 
- OS, version: 10
- Browser, version: DEV Android App **1.5.0-2**

**Comment by djuber** [comment] 2021-07-28 17:30
Hi Thomas,

I'm able to replicate this locally (from a desktop, it does not appear to be related to the android app at all and is a server generated error from the moderation comment processing).

I'm looking further into this.

Local recreation setup:
- ensure a user has been set as a mascot (send as sloan will use the mascot's user id for the comment) http://localhost:3000/admin/customization/config
- set your user http://localhost:3000/admin/moderation/mods?state=tag_moderator to be a tag moderator
- http://localhost:3000/admin/content_manager/tags (possibly that step needs to happen here but will show on the mods list).
- http://localhost:3000/admin/advanced/response_templates create one or more mod_comment templates

I was able to get this error when I linked to another article (the " 🔗 Welcome to DEV + Link to "How to Write Your 1st Post on DEV" 🔗 " moderator template contains a link to ` {% link https://dev.to/chrisachard/how-to-write-your-first-post-on-dev-c3k %}`)

I was able to successfully send as sloan when I used a moderator template that only included text and emojis, and was able to recreate the error above when I added a `{% link ... %}` tag to a template and tried to use that.

![send-as-mod](https://user-images.githubusercontent.com/1237369/127368401-90ae3d3c-edfe-4db0-9c48-5b90d4f7d540.png)
![step-2](https://user-images.githubusercontent.com/1237369/127368475-25a31d7a-52e7-4345-9382-ab76dd1fc04d.png)
![error-message](https://user-images.githubusercontent.com/1237369/127368611-d12a3a69-b234-4613-841e-fa379ef92b99.png)


The request made was this

```
POST	http://localhost:3000/comments/moderator_create
{ 
  "response_template":{"id":"3"},
  "comment":{
    "body_markdown":"",
    "commentable_id":"6",
    "commentable_type":"Article",
    "parent_id":false
  }
}
```

And the server generated response was what is shown in the error popup. 

```
{"error":"error","status":"There was an error in your markdown: Requires a Node, NodeSet or String argument, and cannot accept a NilClass.\n(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)\n"}
```

Inserting the same template (insert, submit as myself) also causes the same error - it looks like there's a problem with the template body markdown (on our end, in the  database for the stored response template), and not the comment as mod/sloan functionality specifically.

**Comment by thomasbnt** [comment] 2021-07-28 17:54
Thanks for this precision @djuber

**Comment by djuber** [comment] 2021-07-28 18:28
A minimal reproduction case (this doesn't require moderation at all)

- pick an article in your site, save the url to the clipboard

Create a comment on an article with this body - your url will differ but the key is to add a link to an article as a comment (the failing response template does this)

```
{% link http://localhost:3000/rep_walton_stracke/it-s-a-battlefield-dolor-quibusdam-1075 %}
```

Observe the generated comment preview works as expected (user profile image on the left, article title on the top, tags on the bottom) 

Submit the comment and observe the error.

I believe this is related to [a recent PR](https://github.com/forem/forem/pull/14262) -  since the `Comment#shorten_urls!` is trying
to set a Nokogiri::XML::Element (the `anchor` item in the each block) with inner_html = nil (which is unable to be coerced to html ) and that was very recently committed (so this might have been working fine until this week for you).

We probably want to skip that assignment when there's nothing to assign.

**Comment by ellativity** [comment] 2021-07-28 19:29
@djuber Just to confirm, we don't need to make changes to our comment templates (we share some with the CodeNewbie Forem) because all the changes will be handled by this bugfix, right? 

Is there anything we should bear in mind creating comment templates in future?

**Closed** 2021-07-30 10:27 UTC

**Comment by djuber** [comment] 2021-07-30 13:57
@ellativity - that's correct - there should be no issue with or changes needed to either the existing templates or sending comments in the future - the bugfix was for a recent regression in how links were shortened (where the "link" tag could not be used any longer) and the reported issue was tied to the comment markdown content, rather than the fact that a moderator template had been used.

**Comment by thomasbnt** [comment] 2021-07-30 13:58
Thanks @djuber for fixed that ! 💪🏼😎
