### ISSUE TITLE
article-show-more-dropdown is partially hidden in draft post view

### ISSUE THREAD

**Issue by veerreshr** [forem/forem#14195] opened 2021-07-11 22:23 UTC
**Describe the bug**

A Part of article-show-more-dropdown is hidden under the App bar. When every I try to open a draft post and click on show more on the left side, I don't properly see the pop up menu(dropdown) for share options. 

**To Reproduce**

1. Create a draft post
2. Open the post from dashboard(Not edit, just open)
3. Click on 3 dots(show more)
4. You see a part of pop up menu is hidden behind App bar

**Expected behavior**

When I click 3 dots(show more), I expect the pop up to be either over the app bar(on top of app bar) or it can be displayed in downward direction.

**Screenshots**

![Screenshot (286)](https://user-images.githubusercontent.com/59141533/125211080-68380780-e2c1-11eb-9f9c-487400c4236b.png)

https://user-images.githubusercontent.com/59141533/125211432-ebf2f380-e2c3-11eb-87ba-461315297e5f.mp4

**Desktop :**

- OS, version: Windows 10
- Browser, version: Brave, Version 1.26.74 Chromium: 91.0.4472.124

**Possible Solution**

Making the dropdown render in downward direction.

![Screenshot (287)](https://user-images.githubusercontent.com/59141533/125211317-2d36d380-e2c3-11eb-9850-e52e98c8cdb3.png)
If given a chance I could Implement this or any other changes you suggest.

**Comment by rhymes** [comment] 2021-07-12 10:41
Hi @veerreshr, thank you for the report! I'm going to close this as a duplicate of https://github.com/forem/forem/issues/14195 :-)

**Closed by rhymes** 2021-07-12 10:41 UTC

**Comment by veerreshr** [comment] 2021-07-12 11:27
@rhymes I did not get how it's a duplicate of same issue ? Could you confirm it please. When ever I click on duplicate link you provided, that is leading to the same this issue, I'm not sure how it's a duplicate.

**Comment by Link2Twenty** [comment] 2021-07-12 11:30
I think @rhymes pasted the wrong issue number. It's the same as this issue #13195

**Comment by rhymes** [comment] 2021-07-12 11:31
Thank you @Link2Twenty! Changed the link!
