### ISSUE TITLE
Sometimes doesn't load a listing

### ISSUE THREAD

**Issue by K-Sato1995** [forem/forem#3118] opened 2019-06-11 06:02 UTC
**Describe the bug**

When I click a listing on `newest listings`,
![image](https://user-images.githubusercontent.com/32632542/59247195-830a9e80-8c59-11e9-843b-9e922c1aea40.png)

Sometimes I get a black screen like the screenshot below and I have to refresh the page to load the listing.
![image](https://user-images.githubusercontent.com/32632542/59247176-738b5580-8c59-11e9-90c4-4ac665863135.png)

**To Reproduce**

**Expected behavior**

Load the clicked listing and show it on the screen.
**Screenshots**

Screenshots are given above.

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version:Version 74.0.3729.169 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment] 2019-06-11 07:24
If you can reproduced it, can you check if there's anything logged in the developer console? Thanks!

**Comment by K-Sato1995** [comment] 2019-06-11 07:50
This is what i got in the console.

![image](https://user-images.githubusercontent.com/32632542/59253342-ecde7480-8c68-11e9-96cc-2f1ca62df0f9.png)
![image](https://user-images.githubusercontent.com/32632542/59253350-f49e1900-8c68-11e9-99cd-4adf4f829a35.png)

**Comment by nickytonline** [comment] 2020-09-30 19:29
That JS error is because the user infromation which is stored on the `<body />` tag in the attribute `data-user` has a string value of `"undefined"`. You can see it in action in the browser dev tools console if you do `JSON.parse("undefined")`. So the real issue, is why is the user information undefined.

![image](https://user-images.githubusercontent.com/833231/94730631-84ba1300-0331-11eb-8c7c-47daad2d9f23.png)

**Comment by ludwiczakpawel** [comment] 2021-01-25 14:07
It doesn't seem like happening anymore and the issue itself seems to be pretty outdated as well so I'm closing it.

**Closed by ludwiczakpawel** 2021-01-25 14:07 UTC
Labels: area: listings, bug, ready for dev
