### ISSUE TITLE
homepage nav-search username or anything CTRL-V pasting is auto hiding not able to search 

### ISSUE THREAD

**Issue by krishnadevz** [forem/forem#11535] opened 2020-11-22 06:29 UTC
**Describe the bug**
In dev.to homepage upper nav search bar, I am just searching my another account username but after pasting that username in search after approximately 0.22 sec that username is getting automatically hide but one thing if I press CTRl+V+Enter it is working.

**To Reproduce**
* Open Dev.to homepage
* paste any username in the nav search bar 
* and after approximately 0.2 sec that username is automatically hiding 

**Expected behavior**
* Expected is proper search with that username or article name as it is there 

**Screenshots**
![descripfeaturess](https://user-images.githubusercontent.com/42638797/99896805-0ab36400-2cba-11eb-9380-4881d73cc9ca.gif)

**Desktop:**

- OS, version: windows version 20H2 os build 19042.630
- Browser, version: firefox=83.0 (64-bit)/chrome=Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by rhymes** [comment] 2020-11-23 09:03
This is an odd error, I tried with Firefox and Chrome on macOS but I can't reproduce this :(

**Comment by krishnadevz** [comment] 2020-11-23 10:11
> 
> 
> This is an odd error, I tried with Firefox and Chrome on macOS but I can't reproduce this :(

the first time it works fine but the second time do paste it is happening to me again I think this issue is related to a UI bug I never saw this kind of bug before . :(

**Comment by ludwiczakpawel** [comment] 2021-01-11 09:57
@krishnadevz I can't repro that either. We've been doing some refactoring around the search field in last few weeks, so can you maybe check again whether that still happens to you?

**Comment by cmgorton** [comment] 2021-01-26 20:31
I am unable to reproduce this either. I am going to close this issue but @krishnadevz if you confirm it is still happening I will open it back up. Thanks!

**Closed by cmgorton** 2021-01-26 20:31 UTC
Labels: area: design, bug
