### ISSUE TITLE
I can't write exactly the order number list item in markdown.

### ISSUE THREAD

**Issue by thangphan37** [forem/forem#14563] opened 2021-08-22 00:24 UTC
**Describe the bug**
I'd like to write a list item like `1->2->3`. But it turns out the order of the list item behaves `1->1->2`.

**To Reproduce**
If I add a code block between `First item` and `Second item`  as below the bug will happen.
```
1. First item
npx create-next-app --typescript(a code block)
2. Second item
3. Third item
```

**Expected behavior**
The order of the list item works exactly.

**Screenshots**
![Order Bug](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/z1qajrj0o9o3bxs04jmf.png)

**Desktop (please complete the following information):**

- OS, version: mac OS Big Sur v11.2.1
- Browser, version: Chrome

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by rhymes** [comment] 2021-08-22 13:54
I can reproduce

**Comment by citizen428** [comment] 2021-08-23 04:53
This is a Markdown feature, you can use any number for ordered lists, Markdown will take care of the correct numbering automatically. This allows you to e.g. write every item in the raw markdwon as `1. Something` which means you can reorder them without having to worry about the numbering. Your issue it that because of the codeblock the Markdown parser thinks you're starting a new list. To avoid this, everything that belongs to a list item needs to be indented by for spaces:

I wrote the following [draft post](https://dev.to/citizen428/list-demo-4ee2-temp-slug-9740323?preview=3ec457638d35fd401c0591e99af5f987f7a61090ed7237b3058c3e087a98e805408074bcccdd6d64e41395a73e68e29fb59c543957cacb6a1b363388):

```
Not working:

1. Something
```
code
```
2. Something else

Working:

1. Something
    ```
    code
    ```
2. Something else
```

Here's how it renders in preview:

![image](https://user-images.githubusercontent.com/47985/130391721-aa34e5dc-07d5-4b2d-82de-be31fdf50471.png)

**Comment by rhymes** [comment] 2021-08-23 09:58
Hi @thangphan37, given @citizen428's explanation up here I'm going ahead and close this as it's a feature. Thanks for the heads up turned into a learning opportunity for me :)

**Comment by thangphan37** [comment] 2021-08-23 12:07
Thank you for your explanation 😀. The order of the list item worked well. 
But I still confuse about the markdown layout that is rendered using four spaces. It's shrunk.
It's so nice if it can render as the way not using four spaces. 😊

**Comment by citizen428** [comment] 2021-08-24 02:54
Hmm, good point, maybe we could unify this a bit. Wondering what @aitchiss thinks about this?

**Comment by aitchiss** [comment] 2021-08-24 16:26
Yeah I think we can/should tweak this in the CSS. 

At the minute, we have some styles that are applied to `div.highlight`, which targets code blocks _not_ inside list items. And then we have styles that target `li pre.highlight` which do target the code blocks in lists. The padding is missing from the latter.

https://github.com/forem/forem/blob/0c6c5c55a161f42e854fd840554c723effe65628/app/assets/stylesheets/components/syntax.scss#L14-L46

**Closed** 2021-08-25 15:24 UTC
Labels: bug, area: publishing experience
