### ISSUE TITLE
Indicator for "Pinned post" not visible for signed-in users

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#16675] opened 2022-02-23 16:30 UTC
**Describe the bug**

The indicator that a post is "pinned" has disappeared.

**To Reproduce**

- Pin a post
- See that it is not visible for signed in. Is for signed out.

This Forem currently has a pinned post: https://www.coss.community/

**Expected behavior**

Pinned post indicator remains visible.

**Comment by aitchiss** [comment] 2022-02-23 16:46
Potentially related to the refactor in https://github.com/forem/forem/pull/16574?

**Comment by msarit** [comment] 2022-04-18 13:27
So on forem.dev, whether signed-in or signed-out, I can see the Pinned Post. However, the text changes; when signed-in, the text is "Pinned post" and when signed-out, the text is "Pinned".

I am not seeing the behavior described in this ticket.

![Screen Shot 2022-04-18 at 9 20 56 AM](https://user-images.githubusercontent.com/32520970/163814822-396bf802-1645-4b2c-aec0-b1852e0b45c2.png)

![Screen Shot 2022-04-18 at 9 20 39 AM](https://user-images.githubusercontent.com/32520970/163814803-c438a9a8-b78b-40b8-874b-f965474e85d2.png)

**Comment by aitchiss** [comment] 2022-04-19 09:52
Hey @msarit it looks like some details weren't updated here following [a slack discussion on the same](https://forem-team.slack.com/archives/CAA200SH5/p1645633485432509).

This bug appears to be intermittent and is only happening _sometimes_. We have yet to establish the exact reproduce steps, which should be the first phase of tackling this issue.

**Comment by maestromac** [comment] 2023-05-08 20:05
Closing this since it's in inconsistent to reproduce state.

**Closed by maestromac** 2023-05-08 20:05 UTC
Labels: bug, changelog: rollup
