### ISSUE TITLE
Cannot Accept Terms of Service on Mobile

### ISSUE THREAD

**Issue by BobbyMcWho** [forem/forem#17876] opened 2022-06-09 20:11 UTC
Using an iPhone 11 with iOS 15.5, Safari as the browser, I am unable to dismiss this forem app modal, therefore rendering me unable to click the continue button after accepting TOS. 

I'm also unable to click the link to open the app either. 

<img src="https://user-images.githubusercontent.com/6934825/172935520-724c6633-79c5-45b8-b6cc-d76c9b410f28.png" height="400">

**Comment by fdocr** [comment] 2022-06-09 22:32
Thank you for the report @BobbyMcWho. I can confirm this happens to me as well on Safari for mobile.

This one is a little weird because it only happens during onboarding (not on any other view in dev.to or other Forem instances). When I tap on the `X` button I see a tooltip come up:

![IMG_3F6D5E5CE4C9-1](https://user-images.githubusercontent.com/6045239/172955525-5c64c6c8-9763-4bc5-a1df-4bb1508768d2.jpeg)

This means the `onclick` event isn't triggering properly ([this one here](https://github.com/forem/forem/blob/main/app/javascript/runtimeBanner/RuntimeBanner.jsx#L124-L127)) and it's displaying the tooltip instead. Safari is known for having some special behaviors when it comes to taps on screen, but the weirdest thing to me here is that it only happens during onboarding.

cc @aitchiss maybe you have an idea why this could be happening? I feel like we've run into this before at some point but can't recall exactly what might be happening.

**Comment by BobbyMcWho** [comment] 2022-06-10 00:08
I wonder if it has to do with the FocusTrap that's present on the Onboarding component

**Comment by aitchiss** [comment] 2022-06-10 07:15
> I wonder if it has to do with the FocusTrap that's present on the Onboarding component

This would be my guess too - this banner is technically outside of the "modal" so the trap is likely blocking any interaction with it.

In terms of solutions - I don't think we need to trap focus in the onboarding context 🤔  It looks like a modal, but it isn't really. As in, we use modal classes to style the content area, but it doesn't appear over any other page content, so doesn't really need the focus trap management.

I'm hopeful that if we remove the focus trap, there shouldn't be any negative impact to the keyboard accessibility and this problem should be fixed 🤞

**Comment by fdocr** [comment] 2022-06-10 15:21
Awesome thank you both for the help here! I just sent in a PR that I believe fixes this issue

**Closed** 2022-06-13 14:23 UTC
Labels: bug, area: new user experience
