### ISSUE TITLE
Forem.dev: Load error while creating a new account

### ISSUE THREAD

**Issue by brandonleboeuf** [forem/forem#10356] opened 2020-09-16 21:22 UTC
## New Account Creation error ##
When signing up for a new account on Forem.dev, content would not fully load and I was unable to properly select the initial settings for my account. The problem persisted even after a page refresh.

The checkboxes for User Agreement and Terms of Use would not display and were not accessible through the tab key either.

The subsequent pages also had a problem fully loading.

<img width="1249" alt="Screen Shot 2020-09-17 at 11 38 44 AM" src="https://user-images.githubusercontent.com/54607186/93513325-8b309f80-f8da-11ea-9457-a77c3660fbe9.png">

<img width="1249" alt="Screen Shot 2020-09-17 at 11 39 11 AM" src="https://user-images.githubusercontent.com/54607186/93513343-908dea00-f8da-11ea-808a-fff4b3f98749.png">

##To Reproduce##

1. Navigate to https://forem.dev/enter?state=new-user

2. Click "Create account"

3. Select "Continue with GitHub"

**versions**
- OS, version: Catalina Version 10.15.5
- Browser, version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by afairlie** [comment] 2020-09-19 15:12
Hey! 

Just wanted to echo that I'm getting this error also. I'm not able to access the account I just made because the Continue button is disabled (I can't see checkboxes when I navigate to Terms and Conditions and Code of Conduct), and I keep getting redirected to the the first screenshot dialogue box when I try to refresh or login again. I reproduced this behaviour in another browser, as well.

I'm looking to make my first contribution to Forem, but I see this issue hasn't been assigned a difficulty level yet. Is this something I could work on, or should I start with an easier issue? 

Thanks!

**Comment by brandonleboeuf** [comment] 2020-09-19 16:40
Using developer tools, the first issue can be corrected  by setting the <input> CSS properties to:

- border: var(--border-width) solid black;

- -webkit-apperance: button;

<img width="1251" alt="visible_checkbox" src="https://user-images.githubusercontent.com/54607186/93671890-9101be80-fa5b-11ea-9b73-41543a51c397.png">
<img width="1251" alt="visible_box check" src="https://user-images.githubusercontent.com/54607186/93671894-93641880-fa5b-11ea-9d0c-24cd3ccfc2af.png">

**Comment by afairlie** [comment] 2020-09-21 13:59
thanks @brandonleboeuf !

**Comment by fdoxyz** [comment] 2020-09-22 13:57
Thank you offering your help here @afairlie. I think this issue goes hand in hand with #10408 because the styles aren't being built/served correctly in other forems, like forem.dev.

At the moment this is being tackled from the systems side as it would be fixed by building/serving the assets properly.

**Comment by ludwiczakpawel** [comment] 2020-09-23 07:44
It should be now fixed.

**Closed by ludwiczakpawel** 2020-09-23 07:44 UTC
Labels: area: new user experience, area: systems, type: bug, type: forem creation
