### ISSUE TITLE
Small non-scrollable textarea when editing a post

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#6949] opened 2020-03-30 14:31 UTC
**Describe the bug**
When editing a post, the textarea is too small, and it's not possible to scroll through all the contents.

**To Reproduce**
1. Go to your post's page, e.g. https://dev.to/lightalloy/improve-your-sleep-as-a-developer-21a9
2. Click on "edit"
3. See that the height of the textarea is "limited" and it's not possible to scroll through post's content. There is no vertical scroll in the browser.
It's possible to put the cursor inside the textarea and go through the post's content by pressing up and down arrows on the keyboard.

The same problem sometimes appears when writing a new post (clicking "write a post")

The bug doesn't appear consistently. The problem disappears on refresh.
I wasn't able to reproduce in Chrome, though I'm not sure because en error is not consistent.

Console output includes an error on `backend.js:32:13210`
```
TypeError: r is undefined 
```
When this error occurs, and I edit the post's text, with each symbol added or removed a new error appears in the console on `backend.js:32:14094`:
```
Error: Expected to find root ID. 
```

**Expected behavior**
The textarea should have enough rows, and there should be a vertical scroll in the browser. It should be possible to scroll through your post's content.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/30115/77923345-01006a80-72ab-11ea-9e27-6dfbf62a7a61.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: Firefox Developer
- Version: 75.0b11 (64-bit)

**Comment by lightalloy** [comment] 2020-03-30 14:33
To our amazing contributors: issues labeled "type: bug" are always up for grabs, but for feature requests, please wait until we add a ready for dev before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our contributors' guide.

**Comment by rhymes** [comment] 2020-03-30 15:06
Would this be related to https://github.com/thepracticaldev/dev.to/issues/6752 as well?

**Comment by lightalloy** [comment] 2020-03-31 09:02
I doubt it's related because #6752 describes that there is a main scroll, but it's not convenient. In this case, there is no main scroll which is the main problem.

**Comment by citizen428** [comment] 2020-04-01 03:25
Interesting, I was not able to reproduce this with Firefox Devloper Edition 75.0b11 on macOS 10.15.4. I know you mentioned that the bug doesn't appear consistently, but I don't remember ever encountering it.

**Comment by ludwiczakpawel** [comment] 2021-01-25 14:00
I'm closing this issue because the UI of this view has significantly changed since this issues was reported and I believe it's not longer valid.

**Closed by ludwiczakpawel** 2021-01-25 14:00 UTC
Labels: area: publishing experience, bug
