### ISSUE TITLE
Rate limiting new posts for users

### ISSUE THREAD

**Issue by GeorgeColdham** [forem/forem#3091] opened 2019-06-10 12:55 UTC
**Is your feature request related to a problem? Please describe.**
I occasionally find my feed clogged with posts that I guess are bots? Or users trying to push users off site.

**Describe the solution you'd like**
Rate limit users posts per hour. Perhaps loosen limits for people who have old enough accounts and/or enough post interactions.

**Describe alternatives you've considered**
Creating a bot to filter out any similarly titled articles?

**Additional context**
Example of my latest feed:
![Screenshot 2019-06-10 at 13 49 14](https://user-images.githubusercontent.com/21260083/59196458-a7497b00-8b86-11e9-9363-89cb654f27f0.png)

Examples of users who have been created today and have posted 15+ posts each within the last 40 minutes:
![Screenshot 2019-06-10 at 13 53 46](https://user-images.githubusercontent.com/21260083/59196744-656d0480-8b87-11e9-9535-766f09ed34e6.png)
![Screenshot 2019-06-10 at 13 54 07](https://user-images.githubusercontent.com/21260083/59196747-67cf5e80-8b87-11e9-86ba-fccb72cffe8b.png)
![Screenshot 2019-06-10 at 13 54 16](https://user-images.githubusercontent.com/21260083/59196752-6a31b880-8b87-11e9-94b3-216f78cc9e14.png)

![Screenshot 2019-06-10 at 14 00 23](https://user-images.githubusercontent.com/21260083/59197026-24292480-8b88-11e9-9d16-02f23bd8ee18.png)
![Screenshot 2019-06-10 at 14 00 35](https://user-images.githubusercontent.com/21260083/59197031-25f2e800-8b88-11e9-834d-8c9864311c0a.png)

**Comment by benhalpern** [comment] 2019-06-10 18:27
This makes sense. We currently have a ratelimit but it's super loose. Let's tighten it up for new users and ensure the error message about the ratelimiting is clear (I'd be less worried about false positives if we at least had clearer messaging for the end user.

It also might make sense to auto-generate a "report" `feedback_message` to be sent to our support channel whenever someone hits the ratelimit. It will help us deal more quickly with spam and pay better attention to any possible false positives.

**Comment by GeorgeColdham** [comment] 2019-06-11 12:21
Im just starting to look into this as my first contribution here. I have a couple of questions.

- What would be a good rate limit for new users? Im thinking ~4 posts an hour?
- How do you define a new user? Account age, number of posts, number of ❤️'s, etc?

**Comment by GeorgeColdham** [comment] 2019-06-12 13:04
I have a working rate limiter for new articles. My preference at this point would be to implement these changes asap, then raise a couple of new tickets for the other points that were addressed by @benhalpern.

These being:
- Report accounts that hit the rate limit to the support channel
- Limit this to new users

**Comment by jessleenyc** [comment] 2019-08-01 15:01
Hey @GeorgeColdham, noticed you closed your PR here. Are you still interested in working on the issue?

**Comment by tamcv** [comment] 2020-04-24 13:17
Hi @jessleenyc @GeorgeColdham
Is this issue available to pick up? I would like to make my first contribution for dev.to.

**Comment by rhymes** [comment] 2020-04-24 13:28
Hi @tamcv, first and foremost: thank you for offering to work on this. The issue is available, we have added some rate limiting in the past which is around 9 posts (where 9 is a configurable option) each 30 seconds which might be too wide of a net frankly.

We might want to discuss what we want to achieve exactly before you set out writing code.

I'm ccing @mstruve @jessleenyc and @benhalpern which should provide additional information.

ps. if you could wait until we merge https://github.com/thepracticaldev/dev.to/pull/7444/ it'd be grand as it's going to impact the structure of the code anyway.

**Comment by tamcv** [comment] 2020-04-24 14:03
Sure @rhymes, I can learn somethings from your PR in the meantime.
By the way, I would like to propose the new limit tiers structure based on users contribution as the following:
1. Tier 1:
   - Conditions: `Time.now - created_at < 1.day`
   - Limitation:  `30 comments / hour`, `5 posts / hour`
1. Tier 2:
   - Conditions: `(current_posts * 2 + interactions) < 5`
   - Limitation:  `60 comments / hour`, `10 posts / hour`
2. Tier 3:
   - Conditions: `5 <= (current_posts * 2 + interactions) < 50`
   - Limitation:  `120 comments / hour`, `20 posts / hour`
so on for tiers 3, 4, 5 till tier has limitation is unlimited. 
(Need you guys help to define the conditions above number...)

And we should keep the current rate limitings ( 9 post/30s & 9 comments/30s) to avoid spamming from high-tier users too

**Comment by mstruve** [comment] 2020-04-27 20:05
I don't think it should ever be unlimited bc there is no reason for it except that it opens us up to script abuse. If someone is providing quality content to the site then it is very, very likely they are not cranking out hundreds of comments or posts an hour. If they are then that is something we need to work with them to create a better workflow bc right now we are not optimized for that.  

These limits are a combination of what we think users actually need to contribute easily and without issues to the DEV community, while at the same time keeping in mind our ability to process all of the new content on the backend. If we end up in situations where users need the ability to publish A LOT more then we need to re-evaluate our code paths and likely write new ones to help make that happen.

**Comment by mstruve** [comment] 2020-08-19 16:39
Given that we now have rate-limiting on article creation I think we can close this issue. https://github.com/forem/forem/blob/master/app/services/rate_limit_checker.rb#L87

**Closed** 2020-08-19 16:39 UTC
Labels: area: fighting abuse, area: publishing experience, hacktoberfest, ready for dev, tech: ruby
