### ISSUE TITLE
Offline mode triggered when uBlock Origin is active

### ISSUE THREAD

**Issue by mbifulco** [forem/forem#6497] opened 2020-03-06 13:05 UTC
**Describe the bug**
Using Chrome 80.0.3987.132 for MacOS (Catalina) - Dev.to's offline mode is displayed when I'm online.  Refreshing / hard refreshing doesn't make a difference.  This only seems to happen while I'm logged in, and is triggered most often when I navigate to an article from my notifications feed.

**To Reproduce**
1. Install [uBlock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) adblock extension for chrome.
1. Log in to dev.to
1. Navigate to [notifications](https://dev.to/notifications)
1. click on a notification to get to an article
1. see offline mode

**Expected behavior**
Having an adblocker activated shouldn't cause offline mode to display

**Screenshots**
<img width="1440" alt="Pasted_Image_3_6_20__8_02_AM" src="https://user-images.githubusercontent.com/1844496/76085865-df001a80-5f80-11ea-85e7-8d1f25926f93.png">

<img width="1440" alt="Pasted_Image_3_6_20__8_03_AM" src="https://user-images.githubusercontent.com/1844496/76085898-f5a67180-5f80-11ea-8ce0-9541e3ea6ab7.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 80.0.3987.132

**Additional context**
I realize there's a caveat in the bug report template here explaining that I should deactivate extensions before creating an issue -- _but_ I'm guessing uBlock is fairly common for the dev.to audience, and this issue seems like it may have more to do with site implementation details than a misbehaving extension.

**Comment by maestromac** [comment] 2020-03-06 14:50
Hey @mbifulco , I have ublock installed on my Chrome and I'm able to access dev.to regularly. Did you happen to apply a special configuration to your ublock? 

I also think there's potential that this service worker caching bug. Can you try unregistering our service worker via the Chrome console then restart Chrome ?
![image](https://user-images.githubusercontent.com/15793250/76093912-c2b7aa00-5f8f-11ea-8891-457693391e6b.png)

**Comment by mbifulco** [comment] 2020-03-06 15:12
Hi there @maestromac - I don't have a special configuration on uBlock.  Unregistering the service worker and restarting chrome didn't quite fix things for me, unfortunately:

When I first unregister the service worker and reload the browser, the page will load correctly, but only once.  I suspect your suspicion might be right, then, that this has to do with the SW - as soon as it loads again and runs I can no longer load other articles on dev

**Comment by maestromac** [comment] 2020-03-06 16:08
@mbifulco Is it only the notifications page you are having an issue with? Do you see any errors in your Chrome console?

**Comment by mbifulco** [comment] 2020-03-06 19:01
Hey @maestromac - so I'm trying to get a more detailed understanding of what's going on, but here's what I've come to observe.  It seems like [_this_ link](https://dev.to/attacomsian/are-ad-blockers-blocking-google-analytics-1e5j), specifically, when clicked on from my notifications page does not work

![image](https://user-images.githubusercontent.com/1844496/76113495-3f5b8000-5fb2-11ea-8514-9207f4ee099c.png)

When I hover over the link, it looks like a pre-navigation `get` request is failing to fetch that page:
![image](https://user-images.githubusercontent.com/1844496/76113569-64e88980-5fb2-11ea-8244-283e9f3049db.png)

Similarly, the _first_ time I click that link, nothing happens in the UI, presumably because that fetch failed.  The _second_ time I click, however, I'm redirected to the URL for that page (`https://dev.to/attacomsian/are-ad-blockers-blocking-google-analytics-1e5j`), but am shown the offline drawing component.

At that time, I see the following error in the console:
![image](https://user-images.githubusercontent.com/1844496/76113730-a7aa6180-5fb2-11ea-8dee-e569acb205f0.png)

Given that the error above ☝️ seems to be coming from react devtools, I disabled the extension to see if it may have been the culprit, however I still get the same behavior.

Finally, back on the notifications page, if I refresh with `Command + Shift + R`, I see:
![image](https://user-images.githubusercontent.com/1844496/76113468-34a0eb00-5fb2-11ea-9524-396e9ade2e63.png)

**Comment by rhymes** [comment] 2020-03-06 19:38
I saw the offline page as well in Firefox - with https://dev.to/attacomsian/are-ad-blockers-blocking-google-analytics-1e5j - but it disappeared after a few refreshes

**Comment by maestromac** [comment] 2020-03-06 20:53
Thank you for providing all those info @mbifulco . I'm not really sure what's causing this issue 😕 . I'm gonna need a bit more time to try to reproduce this.

**Comment by mbifulco** [comment] 2020-03-06 20:58
No problem. I've got a reasonable workaround for now. Happy to hop on a call to screen share if you want to investigate from my environment specifically

**Comment by Rafi993** [comment] 2020-06-15 13:21
I have faced Issue similar to this before when working on other projects. The reason it is happening is because the url contains the word **google-analytics** https://dev.to/attacomsian/are-ad-blockers-blocking-google-analytics-1e5j. I was able to reproduce this issue by installing ublock origin in brave browser.

https://www.reddit.com/r/uBlockOrigin/comments/9j0mer/ublock_origin_blocks_our_websites_search_results/

**Comment by Rafi993** [comment] 2020-06-15 13:27
replacing '-' with '+' or any other characters in url would fix this ex:
https://www.google.com/search?q=google+analytics&oq=google+analytics

**Comment by mstruve** [comment] 2021-03-18 23:25
Closing since offline mode and the service worker has been removed so this should no longer be an issue.

**Closed by mstruve** 2021-03-18 23:25 UTC
Labels: bug

**Comment by Rafi993** [comment] 2021-03-19 03:06
> Closing since offline mode and the service worker has been removed so this should no longer be an issue.

But won't the article URL still be blocked?

**Comment by rhymes** [comment] 2021-03-19 11:32
@Rafi993 they would likely need to manually unregister the service worker so that they can pick up the new one that has no caching or offline status
