### ISSUE TITLE
Cannot resize images inside the editor (rich+markdown, v2 editor)

### ISSUE THREAD

**Issue by technoglot** [forem/forem#13604] opened 2021-04-30 15:14 UTC
**Describe the bug**

I noticed that an image I typically embed at the end of my posts was too large. I had already resized it to my liking in the past. I attempted to resize it again today (using width and height inside the img tag), but it simply would not become smaller. I am using the Rich + Markdown editor.

**To Reproduce**

First, make sure you are using the Rich + Markdown editor. 

Then click "Write a post" and paste the snippet below inside the post body. 
```
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.l3HipxlvUp5qFm_eF-nyXwHaEL%26pid%3DApi&f=1"></a>
```

Preview the post. Image should look like this:
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.l3HipxlvUp5qFm_eF-nyXwHaEL%26pid%3DApi&f=1"></a>

Then try to resize the image by setting the width and height. For example:
```
<img width=25 height=25 src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.l3HipxlvUp5qFm_eF-nyXwHaEL%26pid%3DApi&f=1"></a>
```

Preview the post again. Image should be much smaller now:
<img width=25 height=25 src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.l3HipxlvUp5qFm_eF-nyXwHaEL%26pid%3DApi&f=1"></a>

The behavior showcased above, does NOT work inside the editor. Changes do NOT reflect either. Previewing the post before and after the change yields the same image size somehow.

**Expected behavior**

Given that I add an image (using the img tag) to a post inside the editor and I attempt to resize it, the image should be resized accordingly.

**Screenshots**

See explanation above.

**Desktop (please complete the following information):**

- OS, version: Windows 10 Pro
- Browser, version: Chrome, Version 90.0.4430.93

**Additional context**

This was previously working just fine. Today I noticed the image was much larger than it is supposed to be. Nothing I tried had any effect whatsoever.

**Comment by technoglot** [comment] 2021-05-02 04:25
Hello, just checking in. Any updates you can share on this issue's status?

**Comment by cmgorton** [comment] 2021-05-04 14:47
Hey @technoglot this isn't currently a feature we allow people to do in the editor. We don’t allow people to decide the size of the image and we try limit what we allow users to do with html tags for security reasons. 
If you would like to see this as a potential feature in the future you can create a feature request on [forem.dev](https://forem.dev/). We use [forem.dev](https://forem.dev/) to discuss features and get feedback from our product team. 

You can see some examples of feature requests over there in this [post](https://forem.dev/foremteam/let-s-discuss-3-a-roundup-of-feature-requests-5e2e). 


I am going to close this issue since we realized this is not a bug but I am happy to help you create a post on forem.dev if you need any help! Thanks.

**Closed by cmgorton** 2021-05-04 14:47 UTC
Labels: area: images, area: publishing experience
