### ISSUE TITLE
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"

### ISSUE THREAD

**Issue by emartindev** [forem/forem#9761] opened 2020-08-12 23:54 UTC
**Describe the bug**
When using Forem Docker, I get the following errors when doing: Run bin/container-setup<br />
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'rails' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1

**To Reproduce**

**Expected behavior**
Working Forem

**Screenshots**
`sudo bin/container-setup
Building the Forem container image!
This will take a while if you are building the container for the first time.
bundle uses an image, skipping
yarn uses an image, skipping
db uses an image, skipping
redis uses an image, skipping
elasticsearch uses an image, skipping
sidekiq uses an image, skipping
seed uses an image, skipping
webpacker uses an image, skipping
Building rails
Step 1/31 : FROM quay.io/forem/ruby:2.7.1
 ---> 08eb0dc31868
Step 2/31 : USER root
 ---> Using cache
 ---> 5959c04d2f01
Step 3/31 : RUN curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo &&     dnf install -y bash curl git ImageMagick iproute less libcurl libcurl-devel                    libffi-devel libxml2-devel libxslt-devel nodejs pcre-devel                    postgresql postgresql-devel ruby-devel tzdata yarn                    && dnf -y clean all                    && rm -rf /var/cache/yum
 ---> Using cache
 ---> a98c3e01a8d0
Step 4/31 : ENV APP_USER=forem
 ---> Using cache
 ---> 0170f974b618
Step 5/31 : ENV APP_UID=1000
 ---> Using cache
 ---> 323507509645
Step 6/31 : ENV APP_GID=1000
 ---> Using cache
 ---> e6aec20edd67
Step 7/31 : ENV APP_HOME=/opt/apps/forem/
 ---> Using cache
 ---> 4b811b682c75
Step 8/31 : RUN mkdir -p ${APP_HOME} && chown "${APP_UID}":"${APP_GID}" "${APP_HOME}"
 ---> Using cache
 ---> 9bfe1cb8dc3c
Step 9/31 : RUN groupadd -g "${APP_GID}" "${APP_USER}" &&     adduser -u "${APP_UID}" -g "${APP_GID}" -d "${APP_HOME}" "${APP_USER}"
 ---> Using cache
 ---> 8e2eb9bd3c12
Step 10/31 : ENV BUNDLER_VERSION=2.1.4
 ---> Using cache
 ---> bddf47850510
Step 11/31 : RUN gem install bundler:"${BUNDLER_VERSION}"
 ---> Using cache
 ---> 57282b384809
Step 12/31 : ENV GEM_HOME=/opt/apps/bundle/
 ---> Using cache
 ---> 014813265694
Step 13/31 : ENV BUNDLE_SILENCE_ROOT_WARNING=1 BUNDLE_APP_CONFIG="${GEM_HOME}"
 ---> Using cache
 ---> e349d63af633
Step 14/31 : ENV PATH "${GEM_HOME}"/bin:$PATH
 ---> Using cache
 ---> 71e644630c7a
Step 15/31 : RUN mkdir -p "${GEM_HOME}" && chown "${APP_UID}":"${APP_GID}" "${GEM_HOME}"
 ---> Using cache
 ---> 08d0ff28deef
Step 16/31 : ENV DOCKERIZE_VERSION=v0.6.1
 ---> Using cache
 ---> e37a582aa490
Step 17/31 : RUN wget https://github.com/jwilder/dockerize/releases/download/"${DOCKERIZE_VERSION}"/dockerize-linux-amd64-"${DOCKERIZE_VERSION}".tar.gz     && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-"${DOCKERIZE_VERSION}".tar.gz     && rm dockerize-linux-amd64-"${DOCKERIZE_VERSION}".tar.gz
 ---> Using cache
 ---> df8a97a6c294
Step 18/31 : WORKDIR "${APP_HOME}"
 ---> Using cache
 ---> 5f6495a298f4
Step 19/31 : USER "${APP_USER}"
 ---> Using cache
 ---> a625081c3506
Step 20/31 : COPY ./.ruby-version "${APP_HOME}"
 ---> Using cache
 ---> 3e3f028dd6ef
Step 21/31 : COPY ./Gemfile ./Gemfile.lock "${APP_HOME}"
 ---> Using cache
 ---> dc19ce03caef
Step 22/31 : RUN bundle config build.sassc --disable-march-tune-native
 ---> Using cache
 ---> ec8a3a7d1345
Step 23/31 : RUN bundle check || bundle install --jobs 20 --retry 5
 ---> Using cache
 ---> 8043205cb2d9
Step 24/31 : COPY ./package.json ./yarn.lock ./.yarnrc "${APP_HOME}"
 ---> Using cache
 ---> b03e185bd32c
Step 25/31 : COPY ./.yarn "${APP_HOME}"/.yarn
 ---> Using cache
 ---> b7a263e7be17
Step 26/31 : RUN yarn install
 ---> Running in 8007a895f260
yarn install v1.22.4
[1/5] Validating package.json...
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'rails' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1`

**Desktop (please complete the following information):**

- OS, version: Ubuntu 18.04
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I've tried and looked at issue case #9746 extensively & https://yarnpkg.com/en/docs/cli/install to help with this issue

**Comment by rhymes** [comment] 2020-08-13 06:18
Closing this as a duplicate of https://github.com/forem/forem/issues/9746 

Thanks @emartindev, could you copy your comment over there?

**Closed by rhymes** 2020-08-13 06:18 UTC
