### ISSUE TITLE
[Bug] Analytics graphs aren't changing

### ISSUE THREAD

**Issue by lucianojung** [forem/forem#13557] opened 2021-04-28 08:01 UTC
**Describe the bug**

When I go to the Analytics Page and change the time span from week to month or infinity all the graphs aren't changing

**To Reproduce**

Go to Dashboard -> Analytics
Change Week to Month or Infinity
See the graphs aren't changing

**Expected behavior**

If i change the time span i also want to see the graphs change

**Screenshots**

![image](https://user-images.githubusercontent.com/33691403/116365431-8b483480-a805-11eb-9483-c994772ff37d.png)
![image](https://user-images.githubusercontent.com/33691403/116365491-94d19c80-a805-11eb-9d5d-0effbedd34b5.png)
![image](https://user-images.githubusercontent.com/33691403/116365518-9d29d780-a805-11eb-8a63-ae6d32dbdeba.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Microsoft Edge Version 90.0.818.49 (Offizielles Build) (64-Bit)

**Smartphone (please complete the following information):**

- Device: Redmi Note 8
- OS, version: MIUI Global 11,.0.12
- Browser, version: Microsoft Edge

**Additional context**

 -

**Comment by aitchiss** [comment] 2021-04-30 14:25
I think this may have been fixed by #13598 - can you let us know if the issue is persisting for you still?

**Comment by lucianojung** [comment] 2021-04-30 15:31
Thanks, the bug seems to be fixed.

**Closed** 2021-04-30 15:52 UTC

**Comment by aitchiss** [comment] 2021-05-01 08:56
Awesome! Thanks for confirming @lucianojung 😄
