### ISSUE TITLE
Scheduled post wasn't published

### ISSUE THREAD

**Issue by nfrankel** [forem/forem#19028] opened 2023-01-30 17:31 UTC
**Describe the bug**

I scheduled a post and it wasn't published.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by michael-tharrington** [comment] 2023-01-31 14:17
Hey @nfrankel! Sorry to hear that this happened. I've shared your issue with the team and the want to know the following:
- Which articles failed to publish?
- Which editor do they use (basic markdown or the rich + markdown)?
- Did they edit the post (save as draft) after scheduling to publish?
- If they remember anything about for when they were scheduling to publish (date/time)

**Comment by nfrankel** [comment] 2023-01-31 14:20
* Articles failed to publish: https://dev.to/nfrankel/api-design-patterns-5208 and https://dev.to/nfrankel/2022-in-retrospective-1b0m. I've published them manually
* Please check
* I don't remember but it might have been the case
* I think on a Thursday

**Comment by michael-tharrington** [comment] 2023-01-31 14:33
Gotcha! I just clicked in to edit your articles and you used the rich + markdown editor.

**Comment by mirie** [comment] 2023-02-03 20:02
@lightalloy What would be helpful to debug this? The articles are already published but looking to understand what could have happened/how we can understand the cause.

**Comment by lightalloy** [comment] 2023-02-06 11:07
It's hard to say now, because the articles are published already. We don't update an article at the moment of "publication": if the `published_at` was set correctly and it was not saved as draft, the article starts "appearing" in the feed as soon the time (`published_at`) is in the past.
I suppose that the articles were initially saved as draft: it's possible to create a scheduled draft.

**Comment by mirie** [comment] 2023-02-08 16:31
Closing this issue as we don't have any more debugging information to resolve this particular issue. We haven't seen any other schedule to publish problems.

**Closed by mirie** 2023-02-08 16:31 UTC
