### ISSUE TITLE
Comments page: nested comments are shown in a random order

### ISSUE THREAD

**Issue by osde8info** [forem/forem#5545] opened 2020-01-16 15:37 UTC
**Describe the bug**

nested comments are shown in a random order

**To Reproduce**

create a post 
add comments to comments to comments

example
https://dev.to/osde8info/will-desktop-side-rendering-dsr-be-the-next-big-thing-for-static-websites-39fp

**Expected behavior**

comments even when nested should always be shown in DATE order

**Screenshots**

nested comments are shown in a random order

**Desktop (please complete the following information):**

- OS: xubunutu 18
- Browser: ff 72 
- Version: latest

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

https://dev.to/osde8info/will-desktop-side-rendering-dsr-be-the-next-big-thing-for-static-websites-39fp

**Comment by rhymes** [comment] 2020-01-16 15:59
Hi @osde8info, the order is supposed to be by score, not random.

I think I've isolated a possible culprit:

https://github.com/thepracticaldev/dev.to/blob/c7de0d762b38aba5ebe547d9697b770cebb60b5b/app/views/comments/index.html.erb#L89-L106

`Comment.tree_for` orders by `score DESC`:

https://github.com/thepracticaldev/dev.to/blob/c7de0d762b38aba5ebe547d9697b770cebb60b5b/app/models/comment.rb#L109-L111

but `CommentsHelper.tree_for` doesn't seem to order:

https://github.com/thepracticaldev/dev.to/blob/c7de0d762b38aba5ebe547d9697b770cebb60b5b/app/helpers/comments_helper.rb#L27-L29

I might be on the right or the wrong path here, I haven't debugged the issue yet.

**Comment by krzysiek1507** [comment] 2020-10-23 17:57
It looks like `order(:id)` works but probably the system was meant to show the low score comments at the bottom? I guess we could change it to `order(score: :desc, id: :asc` but it still might look weird.

**Comment by cmgorton** [comment] 2021-03-30 14:07
This looks like it is working appropriately and as designed. I am going to go a head and close this issue for now but we can always reopen it if it continues to be a problem.

**Closed by cmgorton** 2021-03-30 14:07 UTC
Labels: area: comments, bug, ready for dev
