### ISSUE TITLE
markdown: some custom attributes render as errors

### ISSUE THREAD

**Issue by bennypowers** [forem/forem#857] opened 2018-10-08 13:47 UTC
**Describe the bug**
for this markdown:

```markdown
```html
<!-- <app-detail> template -->
<app-route route="[[route]]"
    data="{{routeData}}"
    pattern="/:editing"></app-route>

<item-detail hidden$="[[routeData.editing]]"></item-detail>
<item-editor hidden$="[[!routeData.editing]]"></item-editor>

<paper-checkbox checked="{{routeData.editing}}">Editing</paper-checkbox>
``\`
```
(minus the 'escaping' slash in the last line)

The following is rendered:

<img width="719" alt="screenshot 2018-10-08 16 42 55" src="https://user-images.githubusercontent.com/1466420/46612523-7dcce100-cb19-11e8-9630-a49bceef24b8.png">

**Expected behavior**
I would expect that even non-standard attributes render as-is.
Consider the same snippet rendered on github:

```html
<!-- <app-detail> template -->
<app-route route="[[route]]"
    data="{{routeData}}"
    pattern="/:editing"></app-route>

<item-detail hidden$="[[routeData.editing]]"></item-detail>
<item-editor hidden$="[[!routeData.editing]]"></item-editor>

<paper-checkbox checked="{{routeData.editing}}">Editing</paper-checkbox>
```

Where if you inspect the rendered output of one of the attributes:

```html
<span class="pl-e">hidden$</span>
```

**Screenshots**
Please see above.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Any
- Version Accessed Mon 8 Oct 2018

**Comment by benhalpern** [comment] 2018-10-08 14:29
This is approved for community contributions, we'll schedule to get to it if nobody jumps on it.

**Comment by Zhao-Andy** [comment] 2019-01-08 18:41
Not stale; this bug is still reproducible.

**Comment by rhymes** [comment] 2019-09-23 12:40
unstale

**Comment by mstruve** [comment] 2021-01-25 19:24
Given we [use a gem in order to parse markdown into HTML](https://github.com/vmg/redcarpet) is this something we can fix in our codebase or is this something that would have to be fixed within the gem we use?

**Comment by mstruve** [comment] 2021-02-01 15:26
Removed from planning funnel as this edge case is DEV specific and I think our team's time would be better focused on more Forem wide improvements and fixes.

**Comment by Miguel-Enrique13** [comment] 2021-02-11 18:51
@cmgorton - Could you assign this issue to me and @Oghenebrume50

**Comment by cmgorton** [comment] 2021-02-11 18:56
@Miguel-Enrique13 I assigned you to this issue. For some reason it will not allow me to assign @Oghenebrume50. I will try again in a bit but for now I know you both will be working on this. Thanks.

**Comment by Miguel-Enrique13** [comment] 2021-02-18 21:32
So I've looked into this issue and it seems that this issue must be fixed within the Redcarpet gem. Anytime an attribute selector ($, ^ ,* , etc) is present the `<span class="err">` is rendered. 
[Here](https://github.com/forem/forem/blob/66e4747d3fb01bf354123763bed9dd80fb390bf8/app/services/markdown_processor/parser.rb#L24) is where the content is rendered to HTML and the `<span class="err">` first shows up.
The Redcarpet gem is an open-source project so the issue could be brought up there to be fixed.

**Comment by cmgorton** [comment] 2021-02-19 18:01
Thank you for investigating this @Miguel-Enrique13 ! I am going to add the blocked label to this for now so we know we need to look in to the Redcarpet gem before anyone can proceed with this.

**Comment by cmgorton** [comment] 2021-02-26 15:22
Since this is currently blocked I am going to close this issue. We can reopen it if/when the issue in Redcarpet that is blocking this is fixed. Thanks!

**Closed by cmgorton** 2021-02-26 15:22 UTC
Labels: area: publishing experience, blocked, bug
