### ISSUE TITLE
Duplication of onboarding process

### ISSUE THREAD

**Issue by leewynne** [forem/forem#14614] opened 2021-08-28 13:40 UTC
**Describe the bug**

When going through the onboarding process for a few different production forems, the onboarding process happens twice.

**To Reproduce**

I reproduced this recently on Nick's vscode tips forem. I signed up through Safari on Mac and once I agreed to everything, the process started again and successfully completed the second time. I have had this on other forems during mobile sign up.

**Expected behavior**

A single process for onboarding

**Comment by djuber** [comment] 2021-08-28 14:09
This may be a duplicate report of the issue in https://github.com/forem/forem/issues/14483 

It's definitely happening (I've seen it myself when signing in to development environments on the first user login).

**Comment by citizen428** [comment] 2021-08-30 04:02
> (I've seen it myself when signing in to development environments on the first user login

As commented on the other issue, me too. I started investigating, found something I thought might be promising and now I can't reproduce the onboarding loop anymore, at least I couldn't last Friday 🤦‍♂️

**Comment by cmgorton** [comment] 2021-08-30 16:57
Thanks for posting Lee and confirming you have experienced this issue. I am going to close this one since it is a duplicate.

**Closed by cmgorton** 2021-08-30 16:57 UTC
