### ISSUE TITLE
Won't Remove Cover Image

### ISSUE THREAD

**Issue by shadowtime2000** [forem/forem#10726] opened 2020-10-08 04:05 UTC
**Describe the bug**
I can't remove a cover image for a post.

**To Reproduce**
1. Create a Post
2. Add some random content
3. Add a cover image
4. Publish
5. Go into edit and click `remove` for cover image
6. Save

**Expected behavior**
It would remove the cover image

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 85.0.4183.121 (Official Build) (64-bit) (cohort: Stable)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**
Happened on [this post](https://dev.to/shadowtime2000/getting-started-with-denopack-5gk2)

**Comment by citizen428** [comment] 2020-10-08 05:56
This seems to be a duplicate of #6914, so I'll close this issue here. Thanks for the report though @shadowtime2000!

**Closed by citizen428** 2020-10-08 05:56 UTC
