### ISSUE TITLE
Profile banner text is merged in the box

### ISSUE THREAD

**Issue by joshi-chinmay** [forem/forem#4712] opened 2019-11-03 19:49 UTC
**Describe the bug**

Information on the right panel is merged inside the panel.
To know more check my profile - [link](https://dev.to/joshichinmay)

**To Reproduce**

I had URLs for every link present in the settings.
Linkedin, Facebook, Stackoverflow... This made two-lined layout on the profile page.
Later, I removed Facebook, Instagram from the links. Since then, my profile looks weird.

**Expected behavior**
Profile info panel should have some padding.

**Screenshots**
<img width="987" alt="Screenshot 2019-11-03 at 10 17 56 AM" src="https://user-images.githubusercontent.com/16207311/68091043-061ad400-fe49-11e9-91d6-172dcc9bd377.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 78.0.3904.70 (Official Build) (64-bit)

**Comment by joshi-chinmay** [comment] 2019-11-03 19:50
If this is accepted, I can work on it.

**Comment by rhymes** [comment] 2019-11-03 22:30
Hi, thanks for the report! Could you link your profile? It might help understand what's going on by inspecting with the dev tools 😊

**Comment by joshi-chinmay** [comment] 2019-11-03 23:43
Ohh yeah. I should have done that!
[Here](https://dev.to/joshichinmay) you go.

**Comment by rhymes** [comment] 2019-11-04 12:15
@joshi-chinmay thank you and please go ahead!

**Comment by Math3v** [comment] 2020-02-24 07:23
@rhymes Can this one be closed? It looks like it's fixed.

**Comment by rhymes** [comment] 2020-02-24 09:03
@Math3v I don't think it is, if you click on the OP's profile - https://dev.to/joshichinmay - you'll notice how it's still cutout for them:

![profile](https://user-images.githubusercontent.com/146201/75139401-cffdaa80-56ec-11ea-82d5-cfd7f6a631ac.gif)

**Comment by joshi-chinmay** [comment] 2020-02-26 00:32
I was checking the code, and in general, it looked a bit complicated. I haven't received time to work on it yet. But I will fix it.

**Comment by emgoto** [comment] 2020-07-18 11:42
This may be fixed now - I can't reproduce it:

![image](https://user-images.githubusercontent.com/33337378/87851806-86358b00-c93f-11ea-90ec-1532e9a629a7.png)

**Comment by ludwiczakpawel** [comment] 2020-09-09 09:36
Fixed.

**Closed by ludwiczakpawel** 2020-09-09 09:36 UTC
Labels: ready for dev, tech: html/css
