### ISSUE TITLE
Question/Feature Request: How to find out who "hearted" or "unicorned" a post?

### ISSUE THREAD

**Issue by c33s** [forem/forem#217] opened 2018-05-21 19:05 UTC
in my notification i only get a 
```
"Name of Person"  and 4 others reacted to "my post title" with readinglist like like like unicorn like
```
who are the 4 others? they may also write interesting posts i want to look at.

**Comment by Zhao-Andy** [comment] 2018-05-22 17:54
Hey @c33s, thanks for feedback! We're going to backlog this for now. :)

**Comment by c33s** [comment] 2018-10-16 18:47
unstale

**Comment by jessleenyc** [comment] 2018-10-30 21:54
Yeah, this makes sense. If a post gets a lot of engagement, how should we display these names? Thought on this @benhalpern?

**Comment by j-f1** [comment] 2019-02-14 18:15
Is there a way to see which posts I’ve ❤️ed or 🦄ed?

**Comment by maestromac** [comment] 2019-02-14 18:36
@j-f1 There currently isn't a way to view ❤️ed or 🦄ed history but feel free to make a separate feature request for it!

**Comment by j-f1** [comment] 2019-02-14 19:29
⏩ https://github.com/thepracticaldev/dev.to/issues/1806

**Comment by c33s** [comment] 2019-05-16 08:07
not stale

**Comment by AlbertoPdRF** [comment] 2020-06-16 09:12
I'll start working on this issue!

**Comment by rhymes** [comment] 2020-06-16 09:22
@AlbertoPdRF how do you propose to tackle this?

**Comment by AlbertoPdRF** [comment] 2020-06-16 09:28
I have thought about creating a new page on `/:username/:slug/reactions` with a tab (just like on [the dashboard](https://dev.to/dashboard)) for each reaction type, and listing users on each tab similarly to how it's done on [the followers section](https://dev.to/dashboard/user_followers) of the dashboard. How does that sound?

**Comment by jessleenyc** [comment] 2020-06-26 14:17
Hey @AlbertoPdRF, thanks for sharing your thought process behind this. I see that I marked the issue as 'ready for dev' a year ago but I'm triple checking with the team that this is still a feature we'd like implemented -- will get back to you asap.

**Comment by AlbertoPdRF** [comment] 2020-06-26 15:09
Sounds good!

**Comment by AlbertoPdRF** [comment] 2020-07-22 07:26
Hey team, any update on this?

**Comment by Link2Twenty** [comment] 2020-10-08 15:28
@rhymes this is the same issue as #160 I imagine we can close one of them

**Comment by rhymes** [comment] 2020-10-09 10:31
Closing this as duplicate of #160

**Closed by rhymes** 2020-10-09 10:31 UTC
Labels: difficulty: medium, ready for dev, type: feature request
